using System;
using System.Collections.Generic;
using Helpers;
using TaleWorlds.Core;
using TaleWorlds.Localization;
using TaleWorlds.ObjectSystem;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.LogEntries
{
	// Token: 0x02000342 RID: 834
	public class ChildbirthLogEntry : LogEntry, IEncyclopediaLog, IChatNotification
	{
		// Token: 0x06003247 RID: 12871 RVA: 0x000D154C File Offset: 0x000CF74C
		internal static void AutoGeneratedStaticCollectObjectsChildbirthLogEntry(object o, List<object> collectedObjects)
		{
			((ChildbirthLogEntry)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x06003248 RID: 12872 RVA: 0x000D155A File Offset: 0x000CF75A
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			collectedObjects.Add(this.Mother);
			collectedObjects.Add(this.NewbornHero);
		}

		// Token: 0x06003249 RID: 12873 RVA: 0x000D157B File Offset: 0x000CF77B
		internal static object AutoGeneratedGetMemberValueNewbornHero(object o)
		{
			return ((ChildbirthLogEntry)o).NewbornHero;
		}

		// Token: 0x0600324A RID: 12874 RVA: 0x000D1588 File Offset: 0x000CF788
		internal static object AutoGeneratedGetMemberValueMother(object o)
		{
			return ((ChildbirthLogEntry)o).Mother;
		}

		// Token: 0x17000C02 RID: 3074
		// (get) Token: 0x0600324B RID: 12875 RVA: 0x000D1595 File Offset: 0x000CF795
		// (set) Token: 0x0600324C RID: 12876 RVA: 0x000D159D File Offset: 0x000CF79D
		[SaveableProperty(143)]
		public Hero NewbornHero { get; private set; }

		// Token: 0x17000C03 RID: 3075
		// (get) Token: 0x0600324D RID: 12877 RVA: 0x000D15A6 File Offset: 0x000CF7A6
		public bool IsVisibleNotification
		{
			get
			{
				return true;
			}
		}

		// Token: 0x17000C04 RID: 3076
		// (get) Token: 0x0600324E RID: 12878 RVA: 0x000D15A9 File Offset: 0x000CF7A9
		public override ChatNotificationType NotificationType
		{
			get
			{
				return base.CivilianNotification(this.Mother.Clan);
			}
		}

		// Token: 0x17000C05 RID: 3077
		// (get) Token: 0x0600324F RID: 12879 RVA: 0x000D15BC File Offset: 0x000CF7BC
		public override CampaignTime KeepInHistoryTime
		{
			get
			{
				return CampaignTime.Days(Campaign.Current.Models.PregnancyModel.PregnancyDurationInDays * 2f);
			}
		}

		// Token: 0x17000C06 RID: 3078
		// (get) Token: 0x06003250 RID: 12880 RVA: 0x000D15DD File Offset: 0x000CF7DD
		// (set) Token: 0x06003251 RID: 12881 RVA: 0x000D15E5 File Offset: 0x000CF7E5
		public bool NeedsNewLogEntryForTwin { get; private set; }

		// Token: 0x17000C07 RID: 3079
		// (get) Token: 0x06003252 RID: 12882 RVA: 0x000D15EE File Offset: 0x000CF7EE
		// (set) Token: 0x06003253 RID: 12883 RVA: 0x000D15F6 File Offset: 0x000CF7F6
		public Hero NewLogTwin { get; private set; }

		// Token: 0x06003254 RID: 12884 RVA: 0x000D15FF File Offset: 0x000CF7FF
		public ChildbirthLogEntry(Hero mother, Hero newbornHero)
		{
			this.Mother = mother;
			this.NewbornHero = newbornHero;
		}

		// Token: 0x06003255 RID: 12885 RVA: 0x000D1615 File Offset: 0x000CF815
		public override string ToString()
		{
			return this.GetEncyclopediaText().ToString();
		}

		// Token: 0x06003256 RID: 12886 RVA: 0x000D1622 File Offset: 0x000CF822
		public TextObject GetNotificationText()
		{
			return this.GetEncyclopediaText();
		}

		// Token: 0x06003257 RID: 12887 RVA: 0x000D162A File Offset: 0x000CF82A
		public bool IsVisibleInEncyclopediaPageOf(MBObjectBase obj)
		{
			return obj == this.Mother;
		}

		// Token: 0x06003258 RID: 12888 RVA: 0x000D1638 File Offset: 0x000CF838
		public TextObject GetEncyclopediaText()
		{
			TextObject textObject;
			if (this.NewbornHero != null)
			{
				textObject = GameTexts.FindText("str_notification_give_birth_single_child", null);
			}
			else
			{
				textObject = GameTexts.FindText("str_notification_give_birth_single_stillborn", null);
			}
			StringHelpers.SetCharacterProperties("MOTHER", this.Mother.CharacterObject, textObject, false);
			return textObject;
		}

		// Token: 0x04000E2D RID: 3629
		[SaveableField(140)]
		public readonly Hero Mother;
	}
}
