using System;
using System.ComponentModel;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.GauntletUI.Data;
using TaleWorlds.GauntletUI.Layout;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets;
using TaleWorlds.MountAndBlade.ViewModelCollection.FaceGenerator;

namespace TaleWorlds.MountAndBlade.GauntletUI.AutoGenerated1
{
	// Token: 0x02000019 RID: 25
	public class FaceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_19_FaceGenGrid__DependendPrefab : ListPanel
	{
		// Token: 0x06000583 RID: 1411 RVA: 0x0002DB77 File Offset: 0x0002BD77
		public FaceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_19_FaceGenGrid__DependendPrefab(UIContext context)
			: base(context)
		{
		}

		// Token: 0x06000584 RID: 1412 RVA: 0x0002DB80 File Offset: 0x0002BD80
		public void CreateWidgets()
		{
			this._widget = this;
			this._widget_0 = new ScrollbarWidget(base.Context);
			this._widget.AddChild(this._widget_0);
			this._widget_0_0 = new Widget(base.Context);
			this._widget_0.AddChild(this._widget_0_0);
			this._widget_0_1 = new ImageWidget(base.Context);
			this._widget_0.AddChild(this._widget_0_1);
			this._widget_1 = new ScrollablePanel(base.Context);
			this._widget.AddChild(this._widget_1);
			this._widget_1_0 = new Widget(base.Context);
			this._widget_1.AddChild(this._widget_1_0);
			this._widget_1_0_0 = new NavigatableGridWidget(base.Context);
			this._widget_1_0.AddChild(this._widget_1_0_0);
			this._widget_1_1 = new Widget(base.Context);
			this._widget_1.AddChild(this._widget_1_1);
		}

		// Token: 0x06000585 RID: 1413 RVA: 0x0002DC84 File Offset: 0x0002BE84
		public void SetIds()
		{
			this._widget_0.Id = "VerticalScrollbar";
			this._widget_0_1.Id = "VerticalScrollbarHandle";
			this._widget_1_0.Id = "ClipRect";
			this._widget_1_0_0.Id = "Grid";
		}

		// Token: 0x06000586 RID: 1414 RVA: 0x0002DCD4 File Offset: 0x0002BED4
		public void SetAttributes()
		{
			base.WidthSizePolicy = SizePolicy.StretchToParent;
			base.HeightSizePolicy = SizePolicy.StretchToParent;
			base.StackLayout.LayoutMethod = LayoutMethod.HorizontalRightToLeft;
			base.DoNotUseCustomScaleAndChildren = true;
			this._widget_0.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_0.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_0.SuggestedWidth = 8f;
			this._widget_0.HorizontalAlignment = HorizontalAlignment.Right;
			this._widget_0.VerticalAlignment = VerticalAlignment.Center;
			this._widget_0.MarginTop = 15f;
			this._widget_0.MarginBottom = 15f;
			this._widget_0.AlignmentAxis = AlignmentAxis.Vertical;
			this._widget_0.Handle = this._widget_0_1;
			this._widget_0.MaxValue = 100f;
			this._widget_0.MinValue = 0f;
			this._widget_0_0.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_0_0.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_0_0.SuggestedWidth = 4f;
			this._widget_0_0.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_0_0.Sprite = base.Context.SpriteData.GetSprite("BlankWhiteSquare_9");
			this._widget_0_0.Color = new Color(0.3529412f, 0.2509804f, 0.2f, 1f);
			this._widget_0_0.AlphaFactor = 0.2f;
			this._widget_0_1.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_0_1.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_0_1.SuggestedHeight = 10f;
			this._widget_0_1.SuggestedWidth = 8f;
			this._widget_0_1.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_0_1.Brush = base.Context.GetBrush("FaceGen.Scrollbar.Handle");
			this._widget_1.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_1.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_1.AutoHideScrollBars = true;
			this._widget_1.ClipRect = this._widget_1_0;
			this._widget_1.InnerPanel = this._widget_1_0_0;
			this._widget_1.VerticalScrollbar = this._widget_0;
			this._widget_1_0.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_1_0.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_1_0.ClipContents = true;
			this._widget_1_0_0.WidthSizePolicy = SizePolicy.CoverChildren;
			this._widget_1_0_0.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_1_0_0.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_1_0_0.ColumnCount = 5;
			this._widget_1_0_0.DefaultCellHeight = 112f;
			this._widget_1_0_0.DefaultCellWidth = 112f;
			this._widget_1_0_0.MinIndex = 1001;
			this._widget_1_0_0.MaxIndex = 2000;
			this._widget_1_1.DoNotAcceptEvents = true;
			this._widget_1_1.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_1_1.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_1_1.SuggestedWidth = 576f;
			this._widget_1_1.SuggestedHeight = 57f;
			this._widget_1_1.HorizontalAlignment = HorizontalAlignment.Right;
			this._widget_1_1.PositionXOffset = 13f;
			this._widget_1_1.VerticalAlignment = VerticalAlignment.Bottom;
			this._widget_1_1.Sprite = base.Context.SpriteData.GetSprite("General\\CharacterCreation\\character_creation_scroll_gradient");
		}

		// Token: 0x06000587 RID: 1415 RVA: 0x0002E000 File Offset: 0x0002C200
		public void DestroyDataSource()
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				if (this._datasource_Root_TaintTypes != null)
				{
					this._datasource_Root_TaintTypes.ListChanged -= this.OnList_datasource_Root_TaintTypesChanged;
					for (int i = this._widget_1_0_0.ChildCount - 1; i >= 0; i--)
					{
						Widget child = this._widget_1_0_0.GetChild(i);
						((FaceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_26_ItemTemplate)child).OnBeforeRemovedChild(child);
						((FaceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_26_ItemTemplate)this._widget_1_0_0.GetChild(i)).DestroyDataSource();
					}
					this._datasource_Root_TaintTypes = null;
				}
				this._datasource_Root = null;
			}
		}

		// Token: 0x06000588 RID: 1416 RVA: 0x0002E15B File Offset: 0x0002C35B
		public void SetDataSource(FaceGenVM dataSource)
		{
			this.RefreshDataSource_datasource_Root(dataSource);
		}

		// Token: 0x06000589 RID: 1417 RVA: 0x0002E164 File Offset: 0x0002C364
		private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x0600058A RID: 1418 RVA: 0x0002E172 File Offset: 0x0002C372
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x0600058B RID: 1419 RVA: 0x0002E181 File Offset: 0x0002C381
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x0600058C RID: 1420 RVA: 0x0002E190 File Offset: 0x0002C390
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x0600058D RID: 1421 RVA: 0x0002E19F File Offset: 0x0002C39F
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x0600058E RID: 1422 RVA: 0x0002E1AE File Offset: 0x0002C3AE
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x0600058F RID: 1423 RVA: 0x0002E1BD File Offset: 0x0002C3BD
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000590 RID: 1424 RVA: 0x0002E1CC File Offset: 0x0002C3CC
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000591 RID: 1425 RVA: 0x0002E1DB File Offset: 0x0002C3DB
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000592 RID: 1426 RVA: 0x0002E1EA File Offset: 0x0002C3EA
		private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
		{
			if (propertyName == "TaintTypes")
			{
				this.RefreshDataSource_datasource_Root_TaintTypes(this._datasource_Root.TaintTypes);
				return;
			}
		}

		// Token: 0x06000593 RID: 1427 RVA: 0x0002E20C File Offset: 0x0002C40C
		public void OnList_datasource_Root_TaintTypesChanged(object sender, ListChangedEventArgs e)
		{
			switch (e.ListChangedType)
			{
			case ListChangedType.Reset:
			{
				for (int i = this._widget_1_0_0.ChildCount - 1; i >= 0; i--)
				{
					Widget child = this._widget_1_0_0.GetChild(i);
					((FaceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_26_ItemTemplate)child).OnBeforeRemovedChild(child);
					Widget child2 = this._widget_1_0_0.GetChild(i);
					((FaceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_26_ItemTemplate)child2).SetDataSource(null);
					this._widget_1_0_0.RemoveChild(child2);
				}
				return;
			}
			case ListChangedType.Sorted:
			{
				for (int j = 0; j < this._datasource_Root_TaintTypes.Count; j++)
				{
					FacegenListItemVM bindingObject = this._datasource_Root_TaintTypes[j];
					this._widget_1_0_0.FindChild((Widget widget) => widget.GetComponent<GeneratedWidgetData>().Data == bindingObject).SetSiblingIndex(j, false);
				}
				return;
			}
			case ListChangedType.ItemAdded:
			{
				FaceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_26_ItemTemplate faceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_26_ItemTemplate = new FaceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_26_ItemTemplate(base.Context);
				GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(faceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_26_ItemTemplate);
				FacegenListItemVM facegenListItemVM = this._datasource_Root_TaintTypes[e.NewIndex];
				generatedWidgetData.Data = facegenListItemVM;
				faceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_26_ItemTemplate.AddComponent(generatedWidgetData);
				this._widget_1_0_0.AddChildAtIndex(faceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_26_ItemTemplate, e.NewIndex);
				faceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_26_ItemTemplate.CreateWidgets();
				faceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_26_ItemTemplate.SetIds();
				faceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_26_ItemTemplate.SetAttributes();
				faceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_26_ItemTemplate.SetDataSource(facegenListItemVM);
				return;
			}
			case ListChangedType.ItemBeforeDeleted:
			{
				Widget child3 = this._widget_1_0_0.GetChild(e.NewIndex);
				((FaceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_26_ItemTemplate)child3).OnBeforeRemovedChild(child3);
				return;
			}
			case ListChangedType.ItemDeleted:
			{
				Widget child4 = this._widget_1_0_0.GetChild(e.NewIndex);
				((FaceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_26_ItemTemplate)child4).SetDataSource(null);
				this._widget_1_0_0.RemoveChild(child4);
				break;
			}
			case ListChangedType.ItemChanged:
				break;
			default:
				return;
			}
		}

		// Token: 0x06000594 RID: 1428 RVA: 0x0002E3A8 File Offset: 0x0002C5A8
		private void RefreshDataSource_datasource_Root(FaceGenVM newDataSource)
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				if (this._datasource_Root_TaintTypes != null)
				{
					this._datasource_Root_TaintTypes.ListChanged -= this.OnList_datasource_Root_TaintTypesChanged;
					for (int i = this._widget_1_0_0.ChildCount - 1; i >= 0; i--)
					{
						Widget child = this._widget_1_0_0.GetChild(i);
						((FaceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_26_ItemTemplate)child).OnBeforeRemovedChild(child);
						Widget child2 = this._widget_1_0_0.GetChild(i);
						((FaceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_26_ItemTemplate)child2).SetDataSource(null);
						this._widget_1_0_0.RemoveChild(child2);
					}
					this._datasource_Root_TaintTypes = null;
				}
				this._datasource_Root = null;
			}
			this._datasource_Root = newDataSource;
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._datasource_Root_TaintTypes = this._datasource_Root.TaintTypes;
				if (this._datasource_Root_TaintTypes != null)
				{
					this._datasource_Root_TaintTypes.ListChanged += this.OnList_datasource_Root_TaintTypesChanged;
					for (int j = 0; j < this._datasource_Root_TaintTypes.Count; j++)
					{
						FaceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_26_ItemTemplate faceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_26_ItemTemplate = new FaceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_26_ItemTemplate(base.Context);
						GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(faceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_26_ItemTemplate);
						FacegenListItemVM facegenListItemVM = this._datasource_Root_TaintTypes[j];
						generatedWidgetData.Data = facegenListItemVM;
						faceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_26_ItemTemplate.AddComponent(generatedWidgetData);
						this._widget_1_0_0.AddChildAtIndex(faceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_26_ItemTemplate, j);
						faceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_26_ItemTemplate.CreateWidgets();
						faceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_26_ItemTemplate.SetIds();
						faceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_26_ItemTemplate.SetAttributes();
						faceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_26_ItemTemplate.SetDataSource(facegenListItemVM);
					}
				}
			}
		}

		// Token: 0x06000595 RID: 1429 RVA: 0x0002E6A0 File Offset: 0x0002C8A0
		private void RefreshDataSource_datasource_Root_TaintTypes(MBBindingList<FacegenListItemVM> newDataSource)
		{
			if (this._datasource_Root_TaintTypes != null)
			{
				this._datasource_Root_TaintTypes.ListChanged -= this.OnList_datasource_Root_TaintTypesChanged;
				for (int i = this._widget_1_0_0.ChildCount - 1; i >= 0; i--)
				{
					Widget child = this._widget_1_0_0.GetChild(i);
					((FaceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_26_ItemTemplate)child).OnBeforeRemovedChild(child);
					Widget child2 = this._widget_1_0_0.GetChild(i);
					((FaceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_26_ItemTemplate)child2).SetDataSource(null);
					this._widget_1_0_0.RemoveChild(child2);
				}
				this._datasource_Root_TaintTypes = null;
			}
			this._datasource_Root_TaintTypes = newDataSource;
			this._datasource_Root_TaintTypes = this._datasource_Root.TaintTypes;
			if (this._datasource_Root_TaintTypes != null)
			{
				this._datasource_Root_TaintTypes.ListChanged += this.OnList_datasource_Root_TaintTypesChanged;
				for (int j = 0; j < this._datasource_Root_TaintTypes.Count; j++)
				{
					FaceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_26_ItemTemplate faceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_26_ItemTemplate = new FaceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_26_ItemTemplate(base.Context);
					GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(faceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_26_ItemTemplate);
					FacegenListItemVM facegenListItemVM = this._datasource_Root_TaintTypes[j];
					generatedWidgetData.Data = facegenListItemVM;
					faceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_26_ItemTemplate.AddComponent(generatedWidgetData);
					this._widget_1_0_0.AddChildAtIndex(faceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_26_ItemTemplate, j);
					faceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_26_ItemTemplate.CreateWidgets();
					faceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_26_ItemTemplate.SetIds();
					faceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_26_ItemTemplate.SetAttributes();
					faceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_26_ItemTemplate.SetDataSource(facegenListItemVM);
				}
			}
		}

		// Token: 0x0400016B RID: 363
		private ListPanel _widget;

		// Token: 0x0400016C RID: 364
		private ScrollbarWidget _widget_0;

		// Token: 0x0400016D RID: 365
		private Widget _widget_0_0;

		// Token: 0x0400016E RID: 366
		private ImageWidget _widget_0_1;

		// Token: 0x0400016F RID: 367
		private ScrollablePanel _widget_1;

		// Token: 0x04000170 RID: 368
		private Widget _widget_1_0;

		// Token: 0x04000171 RID: 369
		private NavigatableGridWidget _widget_1_0_0;

		// Token: 0x04000172 RID: 370
		private Widget _widget_1_1;

		// Token: 0x04000173 RID: 371
		private FaceGenVM _datasource_Root;

		// Token: 0x04000174 RID: 372
		private MBBindingList<FacegenListItemVM> _datasource_Root_TaintTypes;
	}
}
