using System;
using System.Collections.Generic;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.Core;
using TaleWorlds.Core.ImageIdentifiers;
using TaleWorlds.Library;
using TaleWorlds.Localization;

namespace TaleWorlds.CampaignSystem.BarterSystem.Barterables
{
	// Token: 0x020004A6 RID: 1190
	public class ItemBarterable : Barterable
	{
		// Token: 0x17000EE3 RID: 3811
		// (get) Token: 0x06004C25 RID: 19493 RVA: 0x001822C4 File Offset: 0x001804C4
		public override string StringID
		{
			get
			{
				return "item_barterable";
			}
		}

		// Token: 0x06004C26 RID: 19494 RVA: 0x001822CB File Offset: 0x001804CB
		public ItemBarterable(Hero ownerHero, Hero otherHero, PartyBase ownerParty, PartyBase otherParty, ItemRosterElement itemRosterElement, int averageValueOfItemInNearbySettlements)
			: base(ownerHero, ownerParty)
		{
			this._itemElement = itemRosterElement;
			this._averageValueOfItemInNearbySettlements = averageValueOfItemInNearbySettlements;
			this._otherParty = otherParty;
			this._otherHero = otherHero;
		}

		// Token: 0x17000EE4 RID: 3812
		// (get) Token: 0x06004C27 RID: 19495 RVA: 0x001822F4 File Offset: 0x001804F4
		public ItemRosterElement ItemRosterElement
		{
			get
			{
				return this._itemElement;
			}
		}

		// Token: 0x17000EE5 RID: 3813
		// (get) Token: 0x06004C28 RID: 19496 RVA: 0x001822FC File Offset: 0x001804FC
		public override int MaxAmount
		{
			get
			{
				return this._itemElement.Amount;
			}
		}

		// Token: 0x17000EE6 RID: 3814
		// (get) Token: 0x06004C29 RID: 19497 RVA: 0x00182318 File Offset: 0x00180518
		public override TextObject Name
		{
			get
			{
				return this._itemElement.EquipmentElement.Item.Name;
			}
		}

		// Token: 0x17000EE7 RID: 3815
		// (get) Token: 0x06004C2A RID: 19498 RVA: 0x00182340 File Offset: 0x00180540
		public int ItemValue
		{
			get
			{
				return this._averageValueOfItemInNearbySettlements;
			}
		}

		// Token: 0x06004C2B RID: 19499 RVA: 0x00182348 File Offset: 0x00180548
		public override int GetUnitValueForFaction(IFaction faction)
		{
			return MathF.Round(Campaign.Current.Models.BarterModel.GetBarterPenalty(faction, this, this._otherHero, this._otherParty).ResultNumber * (float)this.ItemValue);
		}

		// Token: 0x06004C2C RID: 19500 RVA: 0x0018238C File Offset: 0x0018058C
		public override void CheckBarterLink(Barterable parentLinkedBarterable)
		{
		}

		// Token: 0x06004C2D RID: 19501 RVA: 0x00182390 File Offset: 0x00180590
		public override ImageIdentifier GetVisualIdentifier()
		{
			return new ItemImageIdentifier(this._itemElement.EquipmentElement.Item, "");
		}

		// Token: 0x06004C2E RID: 19502 RVA: 0x001823BD File Offset: 0x001805BD
		public override string GetEncyclopediaLink()
		{
			return "";
		}

		// Token: 0x06004C2F RID: 19503 RVA: 0x001823C4 File Offset: 0x001805C4
		public override void Apply()
		{
			if (this._otherParty != null)
			{
				base.OriginalParty.ItemRoster.AddToCounts(this._itemElement.EquipmentElement, -base.CurrentAmount);
				this._otherParty.ItemRoster.AddToCounts(this._itemElement.EquipmentElement, base.CurrentAmount);
				return;
			}
			ItemRosterElement itemRosterElement = new ItemRosterElement(this._itemElement.EquipmentElement, base.CurrentAmount);
			GiveItemAction.ApplyForHeroes(base.OriginalOwner, this._otherHero, in itemRosterElement);
		}

		// Token: 0x06004C30 RID: 19504 RVA: 0x00182453 File Offset: 0x00180653
		internal static void AutoGeneratedStaticCollectObjectsItemBarterable(object o, List<object> collectedObjects)
		{
			((ItemBarterable)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x06004C31 RID: 19505 RVA: 0x00182461 File Offset: 0x00180661
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x04001531 RID: 5425
		private readonly ItemRosterElement _itemElement;

		// Token: 0x04001532 RID: 5426
		private readonly Hero _otherHero;

		// Token: 0x04001533 RID: 5427
		private readonly PartyBase _otherParty;

		// Token: 0x04001534 RID: 5428
		private readonly int _averageValueOfItemInNearbySettlements;
	}
}
