using System;
using System.ComponentModel;
using System.Numerics;
using TaleWorlds.CampaignSystem.ViewModelCollection.Encyclopedia.List;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.GauntletUI.Data;
using TaleWorlds.GauntletUI.GamepadNavigation;
using TaleWorlds.GauntletUI.Layout;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets.Party;

namespace SandBox.GauntletUI.AutoGenerated1
{
	// Token: 0x0200006E RID: 110
	public class EncyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaClanPageVM_Dependency_4_EncyclopediaFilterGroup__InheritedPrefab : Widget
	{
		// Token: 0x06001901 RID: 6401 RVA: 0x000B69E8 File Offset: 0x000B4BE8
		public EncyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaClanPageVM_Dependency_4_EncyclopediaFilterGroup__InheritedPrefab(UIContext context)
			: base(context)
		{
		}

		// Token: 0x06001902 RID: 6402 RVA: 0x000B69F4 File Offset: 0x000B4BF4
		public virtual void CreateWidgets()
		{
			this._widget = this;
			this._widget_0 = new NavigationScopeTargeter(base.Context);
			this._widget.AddChild(this._widget_0);
			this._widget_1 = new NavigationAutoScrollWidget(base.Context);
			this._widget.AddChild(this._widget_1);
			this._widget_2 = new PartyHeaderToggleWidget(base.Context);
			this._widget.AddChild(this._widget_2);
			this._widget_2_0 = new ListPanel(base.Context);
			this._widget_2.AddChild(this._widget_2_0);
			this._widget_2_0_0 = new ImageWidget(base.Context);
			this._widget_2_0.AddChild(this._widget_2_0_0);
			this._widget_2_0_1 = new TextWidget(base.Context);
			this._widget_2_0.AddChild(this._widget_2_0_1);
			this._widget_2_0_2 = new ImageWidget(base.Context);
			this._widget_2_0.AddChild(this._widget_2_0_2);
			this._widget_3 = new NavigatableListPanel(base.Context);
			this._widget.AddChild(this._widget_3);
		}

		// Token: 0x06001903 RID: 6403 RVA: 0x000B6B18 File Offset: 0x000B4D18
		public virtual void SetIds()
		{
			this._widget_2.Id = "HeaderToggle";
			this._widget_2_0.Id = "Description";
			this._widget_2_0_0.Id = "CollapseIndicator";
			this._widget_3.Id = "Filters";
		}

		// Token: 0x06001904 RID: 6404 RVA: 0x000B6B68 File Offset: 0x000B4D68
		public virtual void SetAttributes()
		{
			base.HeightSizePolicy = SizePolicy.CoverChildren;
			base.WidthSizePolicy = SizePolicy.StretchToParent;
			base.DoNotAcceptEvents = true;
			this._widget_0.ScopeID = "EncyclopediaFilterGroupScope";
			this._widget_0.ScopeParent = this._widget;
			this._widget_0.ScopeMovements = GamepadNavigationTypes.Vertical;
			this._widget_1.TrackedWidget = this._widget_2;
			this._widget_2.DoNotPassEventsToChildren = true;
			this._widget_2.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_2.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_2.HorizontalAlignment = HorizontalAlignment.Left;
			this._widget_2.VerticalAlignment = VerticalAlignment.Top;
			this._widget_2.CollapseIndicator = this._widget_2_0_0;
			this._widget_2.ListPanel = this._widget_3;
			this._widget_2.RenderLate = true;
			this._widget_2.WidgetToClose = this._widget_3;
			this._widget_2.UpdateChildrenStates = true;
			this._widget_2.GamepadNavigationIndex = 0;
			this._widget_2_0.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_2_0.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_2_0.HorizontalAlignment = HorizontalAlignment.Left;
			this._widget_2_0.VerticalAlignment = VerticalAlignment.Center;
			this._widget_2_0.DoNotAcceptEvents = true;
			this._widget_2_0.UpdateChildrenStates = true;
			this._widget_2_0.StackLayout.LayoutMethod = LayoutMethod.HorizontalLeftToRight;
			this._widget_2_0_0.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_2_0_0.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_2_0_0.SuggestedHeight = 19f;
			this._widget_2_0_0.SuggestedWidth = 19f;
			this._widget_2_0_0.VerticalAlignment = VerticalAlignment.Center;
			this._widget_2_0_0.PositionXOffset = -10f;
			this._widget_2_0_0.PositionYOffset = -3f;
			this._widget_2_0_0.Brush = base.Context.GetBrush("SPOptions.GameKeysgroup.ExpandIndicator");
			this._widget_2_0_0.OverrideDefaultStateSwitchingEnabled = true;
			this._widget_2_0_1.WidthSizePolicy = SizePolicy.CoverChildren;
			this._widget_2_0_1.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_2_0_1.Brush = base.Context.GetBrush("SPOptions.GameKeysGroup.Title.Text");
			this._widget_2_0_1.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_2_0_2.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_2_0_2.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_2_0_2.SuggestedHeight = 2f;
			this._widget_2_0_2.VerticalAlignment = VerticalAlignment.Center;
			this._widget_2_0_2.MarginLeft = 5f;
			this._widget_2_0_2.Brush = base.Context.GetBrush("SPOptions.CollapserLine");
			this._widget_3.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_3.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_3.StackLayout.LayoutMethod = LayoutMethod.VerticalBottomToTop;
			this._widget_3.MarginTop = 40f;
			this._widget_3.DoNotAcceptEvents = true;
			this._widget_3.MarginLeft = 5f;
			this._widget_3.MaxIndex = 10000;
		}

		// Token: 0x06001905 RID: 6405 RVA: 0x000B6E44 File Offset: 0x000B5044
		public virtual void DestroyDataSource()
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget_2_0_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_2_0_1;
				this._widget_2_0_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_2_0_1;
				this._widget_2_0_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_2_0_1;
				this._widget_2_0_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_2_0_1;
				this._widget_2_0_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_2_0_1;
				this._widget_2_0_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_2_0_1;
				this._widget_2_0_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_2_0_1;
				this._widget_2_0_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_2_0_1;
				this._widget_2_0_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_2_0_1;
				if (this._datasource_Root_Filters != null)
				{
					this._datasource_Root_Filters.ListChanged -= this.OnList_datasource_Root_FiltersChanged;
					for (int i = this._widget_3.ChildCount - 1; i >= 0; i--)
					{
						Widget child = this._widget_3.GetChild(i);
						((EncyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaClanPageVM_Dependency_7_ItemTemplate)child).OnBeforeRemovedChild(child);
						((EncyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaClanPageVM_Dependency_7_ItemTemplate)this._widget_3.GetChild(i)).DestroyDataSource();
					}
					this._datasource_Root_Filters = null;
				}
				this._datasource_Root = null;
			}
		}

		// Token: 0x06001906 RID: 6406 RVA: 0x000B706E File Offset: 0x000B526E
		public virtual void SetDataSource(EncyclopediaFilterGroupVM dataSource)
		{
			this.RefreshDataSource_datasource_Root(dataSource);
		}

		// Token: 0x06001907 RID: 6407 RVA: 0x000B7077 File Offset: 0x000B5277
		private void PropertyChangedListenerOf_widget_2_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2_0_1(propertyName);
		}

		// Token: 0x06001908 RID: 6408 RVA: 0x000B7080 File Offset: 0x000B5280
		private void boolPropertyChangedListenerOf_widget_2_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2_0_1(propertyName);
		}

		// Token: 0x06001909 RID: 6409 RVA: 0x000B7089 File Offset: 0x000B5289
		private void floatPropertyChangedListenerOf_widget_2_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2_0_1(propertyName);
		}

		// Token: 0x0600190A RID: 6410 RVA: 0x000B7092 File Offset: 0x000B5292
		private void Vec2PropertyChangedListenerOf_widget_2_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2_0_1(propertyName);
		}

		// Token: 0x0600190B RID: 6411 RVA: 0x000B709B File Offset: 0x000B529B
		private void Vector2PropertyChangedListenerOf_widget_2_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2_0_1(propertyName);
		}

		// Token: 0x0600190C RID: 6412 RVA: 0x000B70A4 File Offset: 0x000B52A4
		private void doublePropertyChangedListenerOf_widget_2_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2_0_1(propertyName);
		}

		// Token: 0x0600190D RID: 6413 RVA: 0x000B70AD File Offset: 0x000B52AD
		private void intPropertyChangedListenerOf_widget_2_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2_0_1(propertyName);
		}

		// Token: 0x0600190E RID: 6414 RVA: 0x000B70B6 File Offset: 0x000B52B6
		private void uintPropertyChangedListenerOf_widget_2_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2_0_1(propertyName);
		}

		// Token: 0x0600190F RID: 6415 RVA: 0x000B70BF File Offset: 0x000B52BF
		private void ColorPropertyChangedListenerOf_widget_2_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2_0_1(propertyName);
		}

		// Token: 0x06001910 RID: 6416 RVA: 0x000B70C8 File Offset: 0x000B52C8
		private void HandleWidgetPropertyChangeOf_widget_2_0_1(string propertyName)
		{
			if (propertyName == "Text")
			{
				this._datasource_Root.FilterName = this._widget_2_0_1.Text;
				return;
			}
		}

		// Token: 0x06001911 RID: 6417 RVA: 0x000B70EE File Offset: 0x000B52EE
		private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001912 RID: 6418 RVA: 0x000B70FC File Offset: 0x000B52FC
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001913 RID: 6419 RVA: 0x000B710B File Offset: 0x000B530B
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001914 RID: 6420 RVA: 0x000B711A File Offset: 0x000B531A
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001915 RID: 6421 RVA: 0x000B7129 File Offset: 0x000B5329
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001916 RID: 6422 RVA: 0x000B7138 File Offset: 0x000B5338
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001917 RID: 6423 RVA: 0x000B7147 File Offset: 0x000B5347
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001918 RID: 6424 RVA: 0x000B7156 File Offset: 0x000B5356
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001919 RID: 6425 RVA: 0x000B7165 File Offset: 0x000B5365
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x0600191A RID: 6426 RVA: 0x000B7174 File Offset: 0x000B5374
		private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
		{
			if (propertyName == "Filters")
			{
				this.RefreshDataSource_datasource_Root_Filters(this._datasource_Root.Filters);
				return;
			}
			if (propertyName == "FilterName")
			{
				this._widget_2_0_1.Text = this._datasource_Root.FilterName;
				return;
			}
		}

		// Token: 0x0600191B RID: 6427 RVA: 0x000B71C4 File Offset: 0x000B53C4
		public void OnList_datasource_Root_FiltersChanged(object sender, ListChangedEventArgs e)
		{
			switch (e.ListChangedType)
			{
			case ListChangedType.Reset:
			{
				for (int i = this._widget_3.ChildCount - 1; i >= 0; i--)
				{
					Widget child = this._widget_3.GetChild(i);
					((EncyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaClanPageVM_Dependency_7_ItemTemplate)child).OnBeforeRemovedChild(child);
					Widget child2 = this._widget_3.GetChild(i);
					((EncyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaClanPageVM_Dependency_7_ItemTemplate)child2).SetDataSource(null);
					this._widget_3.RemoveChild(child2);
				}
				return;
			}
			case ListChangedType.Sorted:
			{
				for (int j = 0; j < this._datasource_Root_Filters.Count; j++)
				{
					EncyclopediaListFilterVM bindingObject = this._datasource_Root_Filters[j];
					this._widget_3.FindChild((Widget widget) => widget.GetComponent<GeneratedWidgetData>().Data == bindingObject).SetSiblingIndex(j, false);
				}
				return;
			}
			case ListChangedType.ItemAdded:
			{
				EncyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaClanPageVM_Dependency_7_ItemTemplate encyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaClanPageVM_Dependency_7_ItemTemplate = new EncyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaClanPageVM_Dependency_7_ItemTemplate(base.Context);
				GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(encyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaClanPageVM_Dependency_7_ItemTemplate);
				EncyclopediaListFilterVM encyclopediaListFilterVM = this._datasource_Root_Filters[e.NewIndex];
				generatedWidgetData.Data = encyclopediaListFilterVM;
				encyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaClanPageVM_Dependency_7_ItemTemplate.AddComponent(generatedWidgetData);
				this._widget_3.AddChildAtIndex(encyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaClanPageVM_Dependency_7_ItemTemplate, e.NewIndex);
				encyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaClanPageVM_Dependency_7_ItemTemplate.CreateWidgets();
				encyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaClanPageVM_Dependency_7_ItemTemplate.SetIds();
				encyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaClanPageVM_Dependency_7_ItemTemplate.SetAttributes();
				encyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaClanPageVM_Dependency_7_ItemTemplate.SetDataSource(encyclopediaListFilterVM);
				return;
			}
			case ListChangedType.ItemBeforeDeleted:
			{
				Widget child3 = this._widget_3.GetChild(e.NewIndex);
				((EncyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaClanPageVM_Dependency_7_ItemTemplate)child3).OnBeforeRemovedChild(child3);
				return;
			}
			case ListChangedType.ItemDeleted:
			{
				Widget child4 = this._widget_3.GetChild(e.NewIndex);
				((EncyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaClanPageVM_Dependency_7_ItemTemplate)child4).SetDataSource(null);
				this._widget_3.RemoveChild(child4);
				break;
			}
			case ListChangedType.ItemChanged:
				break;
			default:
				return;
			}
		}

		// Token: 0x0600191C RID: 6428 RVA: 0x000B7360 File Offset: 0x000B5560
		private void RefreshDataSource_datasource_Root(EncyclopediaFilterGroupVM newDataSource)
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget_2_0_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_2_0_1;
				this._widget_2_0_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_2_0_1;
				this._widget_2_0_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_2_0_1;
				this._widget_2_0_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_2_0_1;
				this._widget_2_0_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_2_0_1;
				this._widget_2_0_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_2_0_1;
				this._widget_2_0_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_2_0_1;
				this._widget_2_0_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_2_0_1;
				this._widget_2_0_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_2_0_1;
				if (this._datasource_Root_Filters != null)
				{
					this._datasource_Root_Filters.ListChanged -= this.OnList_datasource_Root_FiltersChanged;
					for (int i = this._widget_3.ChildCount - 1; i >= 0; i--)
					{
						Widget child = this._widget_3.GetChild(i);
						((EncyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaClanPageVM_Dependency_7_ItemTemplate)child).OnBeforeRemovedChild(child);
						Widget child2 = this._widget_3.GetChild(i);
						((EncyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaClanPageVM_Dependency_7_ItemTemplate)child2).SetDataSource(null);
						this._widget_3.RemoveChild(child2);
					}
					this._datasource_Root_Filters = null;
				}
				this._datasource_Root = null;
			}
			this._datasource_Root = newDataSource;
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget_2_0_1.Text = this._datasource_Root.FilterName;
				this._widget_2_0_1.PropertyChanged += this.PropertyChangedListenerOf_widget_2_0_1;
				this._widget_2_0_1.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_2_0_1;
				this._widget_2_0_1.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_2_0_1;
				this._widget_2_0_1.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_2_0_1;
				this._widget_2_0_1.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_2_0_1;
				this._widget_2_0_1.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_2_0_1;
				this._widget_2_0_1.intPropertyChanged += this.intPropertyChangedListenerOf_widget_2_0_1;
				this._widget_2_0_1.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_2_0_1;
				this._widget_2_0_1.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_2_0_1;
				this._datasource_Root_Filters = this._datasource_Root.Filters;
				if (this._datasource_Root_Filters != null)
				{
					this._datasource_Root_Filters.ListChanged += this.OnList_datasource_Root_FiltersChanged;
					for (int j = 0; j < this._datasource_Root_Filters.Count; j++)
					{
						EncyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaClanPageVM_Dependency_7_ItemTemplate encyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaClanPageVM_Dependency_7_ItemTemplate = new EncyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaClanPageVM_Dependency_7_ItemTemplate(base.Context);
						GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(encyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaClanPageVM_Dependency_7_ItemTemplate);
						EncyclopediaListFilterVM encyclopediaListFilterVM = this._datasource_Root_Filters[j];
						generatedWidgetData.Data = encyclopediaListFilterVM;
						encyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaClanPageVM_Dependency_7_ItemTemplate.AddComponent(generatedWidgetData);
						this._widget_3.AddChildAtIndex(encyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaClanPageVM_Dependency_7_ItemTemplate, j);
						encyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaClanPageVM_Dependency_7_ItemTemplate.CreateWidgets();
						encyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaClanPageVM_Dependency_7_ItemTemplate.SetIds();
						encyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaClanPageVM_Dependency_7_ItemTemplate.SetAttributes();
						encyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaClanPageVM_Dependency_7_ItemTemplate.SetDataSource(encyclopediaListFilterVM);
					}
				}
			}
		}

		// Token: 0x0600191D RID: 6429 RVA: 0x000B780C File Offset: 0x000B5A0C
		private void RefreshDataSource_datasource_Root_Filters(MBBindingList<EncyclopediaListFilterVM> newDataSource)
		{
			if (this._datasource_Root_Filters != null)
			{
				this._datasource_Root_Filters.ListChanged -= this.OnList_datasource_Root_FiltersChanged;
				for (int i = this._widget_3.ChildCount - 1; i >= 0; i--)
				{
					Widget child = this._widget_3.GetChild(i);
					((EncyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaClanPageVM_Dependency_7_ItemTemplate)child).OnBeforeRemovedChild(child);
					Widget child2 = this._widget_3.GetChild(i);
					((EncyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaClanPageVM_Dependency_7_ItemTemplate)child2).SetDataSource(null);
					this._widget_3.RemoveChild(child2);
				}
				this._datasource_Root_Filters = null;
			}
			this._datasource_Root_Filters = newDataSource;
			this._datasource_Root_Filters = this._datasource_Root.Filters;
			if (this._datasource_Root_Filters != null)
			{
				this._datasource_Root_Filters.ListChanged += this.OnList_datasource_Root_FiltersChanged;
				for (int j = 0; j < this._datasource_Root_Filters.Count; j++)
				{
					EncyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaClanPageVM_Dependency_7_ItemTemplate encyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaClanPageVM_Dependency_7_ItemTemplate = new EncyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaClanPageVM_Dependency_7_ItemTemplate(base.Context);
					GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(encyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaClanPageVM_Dependency_7_ItemTemplate);
					EncyclopediaListFilterVM encyclopediaListFilterVM = this._datasource_Root_Filters[j];
					generatedWidgetData.Data = encyclopediaListFilterVM;
					encyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaClanPageVM_Dependency_7_ItemTemplate.AddComponent(generatedWidgetData);
					this._widget_3.AddChildAtIndex(encyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaClanPageVM_Dependency_7_ItemTemplate, j);
					encyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaClanPageVM_Dependency_7_ItemTemplate.CreateWidgets();
					encyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaClanPageVM_Dependency_7_ItemTemplate.SetIds();
					encyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaClanPageVM_Dependency_7_ItemTemplate.SetAttributes();
					encyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaClanPageVM_Dependency_7_ItemTemplate.SetDataSource(encyclopediaListFilterVM);
				}
			}
		}

		// Token: 0x0400052B RID: 1323
		private Widget _widget;

		// Token: 0x0400052C RID: 1324
		private NavigationScopeTargeter _widget_0;

		// Token: 0x0400052D RID: 1325
		private NavigationAutoScrollWidget _widget_1;

		// Token: 0x0400052E RID: 1326
		private PartyHeaderToggleWidget _widget_2;

		// Token: 0x0400052F RID: 1327
		private ListPanel _widget_2_0;

		// Token: 0x04000530 RID: 1328
		private ImageWidget _widget_2_0_0;

		// Token: 0x04000531 RID: 1329
		private TextWidget _widget_2_0_1;

		// Token: 0x04000532 RID: 1330
		private ImageWidget _widget_2_0_2;

		// Token: 0x04000533 RID: 1331
		private NavigatableListPanel _widget_3;

		// Token: 0x04000534 RID: 1332
		private EncyclopediaFilterGroupVM _datasource_Root;

		// Token: 0x04000535 RID: 1333
		private MBBindingList<EncyclopediaListFilterVM> _datasource_Root_Filters;
	}
}
