using System;
using System.ComponentModel;
using TaleWorlds.CampaignSystem.ViewModelCollection.Encyclopedia;
using TaleWorlds.CampaignSystem.ViewModelCollection.Encyclopedia.List;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.GauntletUI.Data;
using TaleWorlds.GauntletUI.GamepadNavigation;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets;

namespace SandBox.GauntletUI.AutoGenerated1
{
	// Token: 0x0200005F RID: 95
	public class EncyclopediaHome__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaHomeVM : BrushWidget, IGeneratedGauntletMovieRoot
	{
		// Token: 0x0600167C RID: 5756 RVA: 0x000A2C7B File Offset: 0x000A0E7B
		public EncyclopediaHome__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaHomeVM(UIContext context)
			: base(context)
		{
		}

		// Token: 0x0600167D RID: 5757 RVA: 0x000A2C84 File Offset: 0x000A0E84
		public void CreateWidgets()
		{
			this._widget = this;
			this._widget_0 = new Widget(base.Context);
			this._widget.AddChild(this._widget_0);
			this._widget_0_0 = new NavigationScopeTargeter(base.Context);
			this._widget_0.AddChild(this._widget_0_0);
			this._widget_0_1 = new NavigatableListPanel(base.Context);
			this._widget_0.AddChild(this._widget_0_1);
		}

		// Token: 0x0600167E RID: 5758 RVA: 0x000A2CFE File Offset: 0x000A0EFE
		public void SetIds()
		{
			this._widget_0_1.Id = "EncyclopediaHomeList";
		}

		// Token: 0x0600167F RID: 5759 RVA: 0x000A2D10 File Offset: 0x000A0F10
		public void SetAttributes()
		{
			base.WidthSizePolicy = SizePolicy.StretchToParent;
			base.HeightSizePolicy = SizePolicy.StretchToParent;
			base.DoNotAcceptEvents = true;
			base.Brush = base.Context.GetBrush("Encyclopedia.Page.SoundBrush");
			this._widget_0.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_0.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_0.SuggestedHeight = 912f;
			this._widget_0.SuggestedWidth = 1465f;
			this._widget_0.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_0.VerticalAlignment = VerticalAlignment.Center;
			this._widget_0.DoNotAcceptEvents = true;
			this._widget_0_0.ScopeID = "EncyclopediaHomeScope";
			this._widget_0_0.ScopeParent = this._widget_0_1;
			this._widget_0_0.ScopeMovements = GamepadNavigationTypes.Horizontal;
			this._widget_0_0.IsDefaultNavigationScope = true;
			this._widget_0_0.HasCircularMovement = false;
			this._widget_0_1.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_0_1.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_0_1.MarginTop = 195f;
			this._widget_0_1.MarginBottom = 40f;
			this._widget_0_1.MarginLeft = 15f;
			this._widget_0_1.MarginRight = 15f;
			this._widget_0_1.HorizontalAlignment = HorizontalAlignment.Left;
		}

		// Token: 0x06001680 RID: 5760 RVA: 0x000A2E50 File Offset: 0x000A1050
		public void RefreshBindingWithChildren()
		{
			EncyclopediaHomeVM datasource_Root = this._datasource_Root;
			this.SetDataSource(null);
			this.SetDataSource(datasource_Root);
		}

		// Token: 0x06001681 RID: 5761 RVA: 0x000A2E74 File Offset: 0x000A1074
		public void DestroyDataSource()
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				if (this._datasource_Root_Lists != null)
				{
					this._datasource_Root_Lists.ListChanged -= this.OnList_datasource_Root_ListsChanged;
					for (int i = this._widget_0_1.ChildCount - 1; i >= 0; i--)
					{
						Widget child = this._widget_0_1.GetChild(i);
						((EncyclopediaHome__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaHomeVM_Dependency_1_ItemTemplate)child).OnBeforeRemovedChild(child);
						((EncyclopediaHome__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaHomeVM_Dependency_1_ItemTemplate)this._widget_0_1.GetChild(i)).DestroyDataSource();
					}
					this._datasource_Root_Lists = null;
				}
				this._datasource_Root = null;
			}
		}

		// Token: 0x06001682 RID: 5762 RVA: 0x000A2FCF File Offset: 0x000A11CF
		public void SetDataSource(EncyclopediaHomeVM dataSource)
		{
			this.RefreshDataSource_datasource_Root(dataSource);
		}

		// Token: 0x06001683 RID: 5763 RVA: 0x000A2FD8 File Offset: 0x000A11D8
		private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001684 RID: 5764 RVA: 0x000A2FE6 File Offset: 0x000A11E6
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001685 RID: 5765 RVA: 0x000A2FF5 File Offset: 0x000A11F5
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001686 RID: 5766 RVA: 0x000A3004 File Offset: 0x000A1204
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001687 RID: 5767 RVA: 0x000A3013 File Offset: 0x000A1213
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001688 RID: 5768 RVA: 0x000A3022 File Offset: 0x000A1222
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001689 RID: 5769 RVA: 0x000A3031 File Offset: 0x000A1231
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x0600168A RID: 5770 RVA: 0x000A3040 File Offset: 0x000A1240
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x0600168B RID: 5771 RVA: 0x000A304F File Offset: 0x000A124F
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x0600168C RID: 5772 RVA: 0x000A305E File Offset: 0x000A125E
		private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
		{
			if (propertyName == "Lists")
			{
				this.RefreshDataSource_datasource_Root_Lists(this._datasource_Root.Lists);
				return;
			}
		}

		// Token: 0x0600168D RID: 5773 RVA: 0x000A3080 File Offset: 0x000A1280
		public void OnList_datasource_Root_ListsChanged(object sender, ListChangedEventArgs e)
		{
			switch (e.ListChangedType)
			{
			case ListChangedType.Reset:
			{
				for (int i = this._widget_0_1.ChildCount - 1; i >= 0; i--)
				{
					Widget child = this._widget_0_1.GetChild(i);
					((EncyclopediaHome__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaHomeVM_Dependency_1_ItemTemplate)child).OnBeforeRemovedChild(child);
					Widget child2 = this._widget_0_1.GetChild(i);
					((EncyclopediaHome__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaHomeVM_Dependency_1_ItemTemplate)child2).SetDataSource(null);
					this._widget_0_1.RemoveChild(child2);
				}
				return;
			}
			case ListChangedType.Sorted:
			{
				for (int j = 0; j < this._datasource_Root_Lists.Count; j++)
				{
					ListTypeVM bindingObject = this._datasource_Root_Lists[j];
					this._widget_0_1.FindChild((Widget widget) => widget.GetComponent<GeneratedWidgetData>().Data == bindingObject).SetSiblingIndex(j, false);
				}
				return;
			}
			case ListChangedType.ItemAdded:
			{
				EncyclopediaHome__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaHomeVM_Dependency_1_ItemTemplate encyclopediaHome__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaHomeVM_Dependency_1_ItemTemplate = new EncyclopediaHome__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaHomeVM_Dependency_1_ItemTemplate(base.Context);
				GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(encyclopediaHome__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaHomeVM_Dependency_1_ItemTemplate);
				ListTypeVM listTypeVM = this._datasource_Root_Lists[e.NewIndex];
				generatedWidgetData.Data = listTypeVM;
				encyclopediaHome__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaHomeVM_Dependency_1_ItemTemplate.AddComponent(generatedWidgetData);
				this._widget_0_1.AddChildAtIndex(encyclopediaHome__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaHomeVM_Dependency_1_ItemTemplate, e.NewIndex);
				encyclopediaHome__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaHomeVM_Dependency_1_ItemTemplate.CreateWidgets();
				encyclopediaHome__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaHomeVM_Dependency_1_ItemTemplate.SetIds();
				encyclopediaHome__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaHomeVM_Dependency_1_ItemTemplate.SetAttributes();
				encyclopediaHome__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaHomeVM_Dependency_1_ItemTemplate.SetDataSource(listTypeVM);
				return;
			}
			case ListChangedType.ItemBeforeDeleted:
			{
				Widget child3 = this._widget_0_1.GetChild(e.NewIndex);
				((EncyclopediaHome__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaHomeVM_Dependency_1_ItemTemplate)child3).OnBeforeRemovedChild(child3);
				return;
			}
			case ListChangedType.ItemDeleted:
			{
				Widget child4 = this._widget_0_1.GetChild(e.NewIndex);
				((EncyclopediaHome__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaHomeVM_Dependency_1_ItemTemplate)child4).SetDataSource(null);
				this._widget_0_1.RemoveChild(child4);
				break;
			}
			case ListChangedType.ItemChanged:
				break;
			default:
				return;
			}
		}

		// Token: 0x0600168E RID: 5774 RVA: 0x000A321C File Offset: 0x000A141C
		private void RefreshDataSource_datasource_Root(EncyclopediaHomeVM newDataSource)
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				if (this._datasource_Root_Lists != null)
				{
					this._datasource_Root_Lists.ListChanged -= this.OnList_datasource_Root_ListsChanged;
					for (int i = this._widget_0_1.ChildCount - 1; i >= 0; i--)
					{
						Widget child = this._widget_0_1.GetChild(i);
						((EncyclopediaHome__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaHomeVM_Dependency_1_ItemTemplate)child).OnBeforeRemovedChild(child);
						Widget child2 = this._widget_0_1.GetChild(i);
						((EncyclopediaHome__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaHomeVM_Dependency_1_ItemTemplate)child2).SetDataSource(null);
						this._widget_0_1.RemoveChild(child2);
					}
					this._datasource_Root_Lists = null;
				}
				this._datasource_Root = null;
			}
			this._datasource_Root = newDataSource;
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._datasource_Root_Lists = this._datasource_Root.Lists;
				if (this._datasource_Root_Lists != null)
				{
					this._datasource_Root_Lists.ListChanged += this.OnList_datasource_Root_ListsChanged;
					for (int j = 0; j < this._datasource_Root_Lists.Count; j++)
					{
						EncyclopediaHome__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaHomeVM_Dependency_1_ItemTemplate encyclopediaHome__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaHomeVM_Dependency_1_ItemTemplate = new EncyclopediaHome__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaHomeVM_Dependency_1_ItemTemplate(base.Context);
						GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(encyclopediaHome__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaHomeVM_Dependency_1_ItemTemplate);
						ListTypeVM listTypeVM = this._datasource_Root_Lists[j];
						generatedWidgetData.Data = listTypeVM;
						encyclopediaHome__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaHomeVM_Dependency_1_ItemTemplate.AddComponent(generatedWidgetData);
						this._widget_0_1.AddChildAtIndex(encyclopediaHome__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaHomeVM_Dependency_1_ItemTemplate, j);
						encyclopediaHome__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaHomeVM_Dependency_1_ItemTemplate.CreateWidgets();
						encyclopediaHome__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaHomeVM_Dependency_1_ItemTemplate.SetIds();
						encyclopediaHome__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaHomeVM_Dependency_1_ItemTemplate.SetAttributes();
						encyclopediaHome__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaHomeVM_Dependency_1_ItemTemplate.SetDataSource(listTypeVM);
					}
				}
			}
		}

		// Token: 0x0600168F RID: 5775 RVA: 0x000A3514 File Offset: 0x000A1714
		private void RefreshDataSource_datasource_Root_Lists(MBBindingList<ListTypeVM> newDataSource)
		{
			if (this._datasource_Root_Lists != null)
			{
				this._datasource_Root_Lists.ListChanged -= this.OnList_datasource_Root_ListsChanged;
				for (int i = this._widget_0_1.ChildCount - 1; i >= 0; i--)
				{
					Widget child = this._widget_0_1.GetChild(i);
					((EncyclopediaHome__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaHomeVM_Dependency_1_ItemTemplate)child).OnBeforeRemovedChild(child);
					Widget child2 = this._widget_0_1.GetChild(i);
					((EncyclopediaHome__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaHomeVM_Dependency_1_ItemTemplate)child2).SetDataSource(null);
					this._widget_0_1.RemoveChild(child2);
				}
				this._datasource_Root_Lists = null;
			}
			this._datasource_Root_Lists = newDataSource;
			this._datasource_Root_Lists = this._datasource_Root.Lists;
			if (this._datasource_Root_Lists != null)
			{
				this._datasource_Root_Lists.ListChanged += this.OnList_datasource_Root_ListsChanged;
				for (int j = 0; j < this._datasource_Root_Lists.Count; j++)
				{
					EncyclopediaHome__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaHomeVM_Dependency_1_ItemTemplate encyclopediaHome__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaHomeVM_Dependency_1_ItemTemplate = new EncyclopediaHome__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaHomeVM_Dependency_1_ItemTemplate(base.Context);
					GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(encyclopediaHome__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaHomeVM_Dependency_1_ItemTemplate);
					ListTypeVM listTypeVM = this._datasource_Root_Lists[j];
					generatedWidgetData.Data = listTypeVM;
					encyclopediaHome__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaHomeVM_Dependency_1_ItemTemplate.AddComponent(generatedWidgetData);
					this._widget_0_1.AddChildAtIndex(encyclopediaHome__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaHomeVM_Dependency_1_ItemTemplate, j);
					encyclopediaHome__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaHomeVM_Dependency_1_ItemTemplate.CreateWidgets();
					encyclopediaHome__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaHomeVM_Dependency_1_ItemTemplate.SetIds();
					encyclopediaHome__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaHomeVM_Dependency_1_ItemTemplate.SetAttributes();
					encyclopediaHome__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaHomeVM_Dependency_1_ItemTemplate.SetDataSource(listTypeVM);
				}
			}
		}

		// Token: 0x0400047F RID: 1151
		private BrushWidget _widget;

		// Token: 0x04000480 RID: 1152
		private Widget _widget_0;

		// Token: 0x04000481 RID: 1153
		private NavigationScopeTargeter _widget_0_0;

		// Token: 0x04000482 RID: 1154
		private NavigatableListPanel _widget_0_1;

		// Token: 0x04000483 RID: 1155
		private EncyclopediaHomeVM _datasource_Root;

		// Token: 0x04000484 RID: 1156
		private MBBindingList<ListTypeVM> _datasource_Root_Lists;
	}
}
