using System;
using System.ComponentModel;
using System.Numerics;
using TaleWorlds.CampaignSystem.ViewModelCollection.GameMenu;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.GauntletUI.Data;
using TaleWorlds.GauntletUI.GamepadNavigation;
using TaleWorlds.GauntletUI.Layout;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets.GameMenu;
using TaleWorlds.TwoDimension;

namespace SandBox.GauntletUI.AutoGenerated1
{
	// Token: 0x0200008E RID: 142
	public class GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM : Widget, IGeneratedGauntletMovieRoot
	{
		// Token: 0x06001E68 RID: 7784 RVA: 0x000DDAB9 File Offset: 0x000DBCB9
		public GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM(UIContext context)
			: base(context)
		{
		}

		// Token: 0x06001E69 RID: 7785 RVA: 0x000DDAC4 File Offset: 0x000DBCC4
		private VisualDefinition CreateVisualDefinitionMenu()
		{
			VisualDefinition visualDefinition = new VisualDefinition("Menu", 0.65f, 0f, AnimationInterpolation.Type.EaseOut, AnimationInterpolation.Function.Quint);
			visualDefinition.AddVisualState(new VisualState("Default")
			{
				PositionXOffset = 0f
			});
			visualDefinition.AddVisualState(new VisualState("Disabled")
			{
				PositionXOffset = -530f
			});
			return visualDefinition;
		}

		// Token: 0x06001E6A RID: 7786 RVA: 0x000DDB24 File Offset: 0x000DBD24
		private VisualDefinition CreateVisualDefinitionInfoPanel()
		{
			VisualDefinition visualDefinition = new VisualDefinition("InfoPanel", 0.45f, 0f, AnimationInterpolation.Type.EaseOut, AnimationInterpolation.Function.Quint);
			visualDefinition.AddVisualState(new VisualState("Default")
			{
				SuggestedWidth = 900f,
				SuggestedHeight = 170f,
				PositionXOffset = 50f
			});
			visualDefinition.AddVisualState(new VisualState("Disabled")
			{
				SuggestedWidth = 900f,
				SuggestedHeight = 0f,
				PositionXOffset = 50f
			});
			return visualDefinition;
		}

		// Token: 0x06001E6B RID: 7787 RVA: 0x000DDBB0 File Offset: 0x000DBDB0
		public void CreateWidgets()
		{
			this._widget = this;
			this._widget_0 = new Widget(base.Context);
			this._widget.AddChild(this._widget_0);
			this._widget_0_0 = new ButtonWidget(base.Context);
			this._widget_0.AddChild(this._widget_0_0);
			this._widget_0_0_0 = new BrushWidget(base.Context);
			this._widget_0_0.AddChild(this._widget_0_0_0);
			this._widget_0_1 = new Widget(base.Context);
			this._widget_0.AddChild(this._widget_0_1);
			this._widget_0_2 = new NavigationScopeTargeter(base.Context);
			this._widget_0.AddChild(this._widget_0_2);
			this._widget_0_3 = new GameMenuWidget(base.Context);
			this._widget_0.AddChild(this._widget_0_3);
			this._widget_0_3_0 = new Widget(base.Context);
			this._widget_0_3.AddChild(this._widget_0_3_0);
			this._widget_0_3_0_0 = new TextWidget(base.Context);
			this._widget_0_3_0.AddChild(this._widget_0_3_0_0);
			this._widget_0_3_1 = new Widget(base.Context);
			this._widget_0_3.AddChild(this._widget_0_3_1);
			this._widget_0_3_1_0 = new ScrollablePanel(base.Context);
			this._widget_0_3_1.AddChild(this._widget_0_3_1_0);
			this._widget_0_3_1_0_0 = new Widget(base.Context);
			this._widget_0_3_1_0.AddChild(this._widget_0_3_1_0_0);
			this._widget_0_3_1_0_0_0 = new DimensionSyncWidget(base.Context);
			this._widget_0_3_1_0_0.AddChild(this._widget_0_3_1_0_0_0);
			this._widget_0_3_1_0_0_1 = new ListPanel(base.Context);
			this._widget_0_3_1_0_0.AddChild(this._widget_0_3_1_0_0_1);
			this._widget_0_3_1_0_0_1_0 = new AutoHideRichTextWidget(base.Context);
			this._widget_0_3_1_0_0_1.AddChild(this._widget_0_3_1_0_0_1_0);
			this._widget_0_3_1_0_0_1_1 = new ListPanel(base.Context);
			this._widget_0_3_1_0_0_1.AddChild(this._widget_0_3_1_0_0_1_1);
			this._widget_0_3_1_0_0_1_2 = new NavigatableListPanel(base.Context);
			this._widget_0_3_1_0_0_1.AddChild(this._widget_0_3_1_0_0_1_2);
			this._widget_0_3_1_0_0_1_3 = new GridWidget(base.Context);
			this._widget_0_3_1_0_0_1.AddChild(this._widget_0_3_1_0_0_1_3);
			this._widget_0_3_1_1 = new Widget(base.Context);
			this._widget_0_3_1.AddChild(this._widget_0_3_1_1);
			this._widget_0_3_1_1_0 = new ScrollbarWidget(base.Context);
			this._widget_0_3_1_1.AddChild(this._widget_0_3_1_1_0);
			this._widget_0_3_1_1_0_0 = new Widget(base.Context);
			this._widget_0_3_1_1_0.AddChild(this._widget_0_3_1_1_0_0);
			this._widget_0_3_2 = new BrushWidget(base.Context);
			this._widget_0_3.AddChild(this._widget_0_3_2);
		}

		// Token: 0x06001E6C RID: 7788 RVA: 0x000DDE90 File Offset: 0x000DC090
		public void SetIds()
		{
			this._widget_0.Id = "Overlay";
			this._widget_0_0.Id = "ExtendButton";
			this._widget_0_0_0.Id = "ExtendButtonArrow";
			this._widget_0_2.Id = "ScopeTargeter";
			this._widget_0_3.Id = "GameMenuParent";
			this._widget_0_3_0.Id = "TitleContainerWidget";
			this._widget_0_3_0_0.Id = "TitleTextWidget";
			this._widget_0_3_1.Id = "ContentContainerWidget";
			this._widget_0_3_1_0.Id = "ScrollablePanel";
			this._widget_0_3_1_0_0.Id = "ClipRect";
			this._widget_0_3_1_0_0_1.Id = "ItemListPanel";
			this._widget_0_3_1_0_0_1_2.Id = "OptionItemsList";
			this._widget_0_3_1_0_0_1_3.Id = "PlunderItemsGrid";
			this._widget_0_3_1_1.Id = "ScrollbarContainer";
			this._widget_0_3_1_1_0.Id = "Scrollbar";
			this._widget_0_3_1_1_0_0.Id = "ScrollbarHandle";
		}

		// Token: 0x06001E6D RID: 7789 RVA: 0x000DDFA0 File Offset: 0x000DC1A0
		public void SetAttributes()
		{
			base.DoNotAcceptEvents = true;
			base.WidthSizePolicy = SizePolicy.StretchToParent;
			base.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_0.VisualDefinition = this.CreateVisualDefinitionMenu();
			this._widget_0.WidthSizePolicy = SizePolicy.CoverChildren;
			this._widget_0.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_0.VerticalAlignment = VerticalAlignment.Center;
			this._widget_0.PositionYOffset = 20f;
			this._widget_0.PositionXOffset = -550f;
			this._widget_0_0.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_0_0.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_0_0.SuggestedHeight = 122f;
			this._widget_0_0.SuggestedWidth = 58f;
			this._widget_0_0.Brush = base.Context.GetBrush("GameMenu.Extend.Button");
			this._widget_0_0.VerticalAlignment = VerticalAlignment.Top;
			this._widget_0_0.MarginLeft = 522f;
			this._widget_0_0.DoNotPassEventsToChildren = true;
			this._widget_0_0.UpdateChildrenStates = true;
			this._widget_0_0.GamepadNavigationIndex = 0;
			this._widget_0_0_0.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_0_0_0.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_0_0_0.SuggestedWidth = 30f;
			this._widget_0_0_0.SuggestedHeight = 30f;
			this._widget_0_0_0.VerticalAlignment = VerticalAlignment.Center;
			this._widget_0_0_0.MarginBottom = 15f;
			this._widget_0_0_0.MarginLeft = 8f;
			this._widget_0_0_0.Brush = base.Context.GetBrush("GameMenu.Extend.Button.Arrow");
			this._widget_0_1.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_0_1.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_0_1.SuggestedWidth = 35f;
			this._widget_0_1.VerticalAlignment = VerticalAlignment.Center;
			this._widget_0_1.SuggestedHeight = 608f;
			this._widget_0_1.PositionXOffset = -10f;
			this._widget_0_1.Sprite = base.Context.SpriteData.GetSprite("StdAssets\\game_menu_hinges");
			this._widget_0_2.ScopeID = "GameMenuScope";
			this._widget_0_2.ScopeParent = this._widget_0_3;
			this._widget_0_2.ScopeMovements = GamepadNavigationTypes.Vertical;
			this._widget_0_2.IsDefaultNavigationScope = true;
			this._widget_0_2.NavigateFromScopeEdges = true;
			this._widget_0_3.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_0_3.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_0_3.HorizontalAlignment = HorizontalAlignment.Left;
			this._widget_0_3.MarginLeft = 27f;
			this._widget_0_3.ScopeTargeter = this._widget_0_2;
			this._widget_0_3.TitleContainerWidget = this._widget_0_3_0;
			this._widget_0_3.TitleTextWidget = this._widget_0_3_0_0;
			this._widget_0_3.Overlay = this._widget_0;
			this._widget_0_3.ExtendButtonWidget = this._widget_0_0;
			this._widget_0_3.ExtendButtonArrowWidget = this._widget_0_0_0;
			this._widget_0_3.OptionItemsList = this._widget_0_3_1_0_0_1_2;
			this._widget_0_3.EncounterModeMenuHeight = 825;
			this._widget_0_3.EncounterModeMenuWidth = 493;
			this._widget_0_3.NormalModeMenuWidth = 493;
			this._widget_0_3.NormalModeMenuHeight = 891;
			this._widget_0_3.NormalModeMenuMarginTop = 0;
			this._widget_0_3.EncounterModeMenuMarginTop = 66;
			this._widget_0_3.OverriddenSpriteMapBrush = base.Context.GetBrush("GameMenu.Background.MappingBrush");
			this._widget_0_3_0.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_0_3_0.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_0_3_0.SuggestedWidth = 343f;
			this._widget_0_3_0.SuggestedHeight = 60f;
			this._widget_0_3_0.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_0_3_0.VerticalAlignment = VerticalAlignment.Top;
			this._widget_0_3_0.PositionYOffset = -69f;
			this._widget_0_3_0_0.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_0_3_0_0.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_0_3_0_0.VerticalAlignment = VerticalAlignment.Center;
			this._widget_0_3_0_0.PositionYOffset = 13f;
			this._widget_0_3_0_0.Brush = base.Context.GetBrush("GameMenu.Text");
			this._widget_0_3_0_0.Brush.FontSize = 30;
			this._widget_0_3_1.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_0_3_1.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_0_3_1_0.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_0_3_1_0.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_0_3_1_0.HorizontalAlignment = HorizontalAlignment.Right;
			this._widget_0_3_1_0.VerticalAlignment = VerticalAlignment.Top;
			this._widget_0_3_1_0.AutoHideScrollBars = true;
			this._widget_0_3_1_0.ClipRect = this._widget_0_3_1_0_0;
			this._widget_0_3_1_0.InnerPanel = this._widget_0_3_1_0_0_1;
			this._widget_0_3_1_0.VerticalScrollbar = this._widget_0_3_1_1_0;
			this._widget_0_3_1_0_0.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_0_3_1_0_0.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_0_3_1_0_0.ClipContents = true;
			this._widget_0_3_1_0_0_0.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_0_3_1_0_0_0.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_0_3_1_0_0_0.Sprite = base.Context.SpriteData.GetSprite("SettlementLeftPanelFilter_9");
			this._widget_0_3_1_0_0_0.WidgetToCopyHeightFrom = this._widget_0_3_1_0_0_1;
			this._widget_0_3_1_0_0_0.AlphaFactor = 0.65f;
			this._widget_0_3_1_0_0_0.Color = new Color(0f, 0.1294118f, 0.2313726f, 1f);
			this._widget_0_3_1_0_0_0.DimensionToSync = DimensionSyncWidget.Dimensions.Vertical;
			this._widget_0_3_1_0_0_1.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_0_3_1_0_0_1.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_0_3_1_0_0_1.StackLayout.LayoutMethod = LayoutMethod.VerticalTopToBottom;
			this._widget_0_3_1_0_0_1_0.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_0_3_1_0_0_1_0.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_0_3_1_0_0_1_0.SuggestedWidth = 850f;
			this._widget_0_3_1_0_0_1_0.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_0_3_1_0_0_1_0.MarginTop = 15f;
			this._widget_0_3_1_0_0_1_0.MarginBottom = 10f;
			this._widget_0_3_1_0_0_1_0.MarginLeft = 15f;
			this._widget_0_3_1_0_0_1_0.MarginRight = 15f;
			this._widget_0_3_1_0_0_1_0.Brush = base.Context.GetBrush("GameMenu.InfoText");
			this._widget_0_3_1_0_0_1_0.Brush.FontSize = 24;
			this._widget_0_3_1_0_0_1_0.Brush.TextHorizontalAlignment = TextHorizontalAlignment.Left;
			this._widget_0_3_1_0_0_1_0.Brush.TextVerticalAlignment = TextVerticalAlignment.Center;
			this._widget_0_3_1_0_0_1_1.WidthSizePolicy = SizePolicy.CoverChildren;
			this._widget_0_3_1_0_0_1_1.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_0_3_1_0_0_1_1.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_0_3_1_0_0_1_1.MarginBottom = 12f;
			this._widget_0_3_1_0_0_1_1.StackLayout.LayoutMethod = LayoutMethod.VerticalTopToBottom;
			this._widget_0_3_1_0_0_1_2.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_0_3_1_0_0_1_2.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_0_3_1_0_0_1_2.MarginTop = 15f;
			this._widget_0_3_1_0_0_1_2.MarginBottom = 15f;
			this._widget_0_3_1_0_0_1_2.StackLayout.LayoutMethod = LayoutMethod.VerticalTopToBottom;
			this._widget_0_3_1_0_0_1_3.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_0_3_1_0_0_1_3.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_0_3_1_0_0_1_3.HorizontalAlignment = HorizontalAlignment.Left;
			this._widget_0_3_1_0_0_1_3.DefaultCellWidth = 55f;
			this._widget_0_3_1_0_0_1_3.DefaultCellHeight = 35f;
			this._widget_0_3_1_0_0_1_3.ColumnCount = 8;
			this._widget_0_3_1_0_0_1_3.MarginLeft = 20f;
			this._widget_0_3_1_0_0_1_3.MarginRight = 20f;
			this._widget_0_3_1_0_0_1_3.MarginBottom = 100f;
			this._widget_0_3_1_1.WidthSizePolicy = SizePolicy.CoverChildren;
			this._widget_0_3_1_1.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_0_3_1_1.IsVisible = false;
			this._widget_0_3_1_1.HorizontalAlignment = HorizontalAlignment.Right;
			this._widget_0_3_1_1_0.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_0_3_1_1_0.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_0_3_1_1_0.SuggestedWidth = 20f;
			this._widget_0_3_1_1_0.VerticalAlignment = VerticalAlignment.Top;
			this._widget_0_3_1_1_0.MarginTop = 20f;
			this._widget_0_3_1_1_0.MarginBottom = 10f;
			this._widget_0_3_1_1_0.Sprite = base.Context.SpriteData.GetSprite("scrollbar_9");
			this._widget_0_3_1_1_0.AlignmentAxis = AlignmentAxis.Vertical;
			this._widget_0_3_1_1_0.Handle = this._widget_0_3_1_1_0_0;
			this._widget_0_3_1_1_0.MaxValue = 100f;
			this._widget_0_3_1_1_0.MinValue = 0f;
			this._widget_0_3_1_1_0.ValueInt = 0;
			this._widget_0_3_1_1_0_0.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_0_3_1_1_0_0.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_0_3_1_1_0_0.SuggestedWidth = 20f;
			this._widget_0_3_1_1_0_0.HorizontalAlignment = HorizontalAlignment.Left;
			this._widget_0_3_1_1_0_0.VerticalAlignment = VerticalAlignment.Top;
			this._widget_0_3_1_1_0_0.Sprite = base.Context.SpriteData.GetSprite("scroll_button_9");
			this._widget_0_3_2.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_0_3_2.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_0_3_2.Brush = base.Context.GetBrush("Frame1.Border");
			this._widget_0_3_2.IsEnabled = false;
		}

		// Token: 0x06001E6E RID: 7790 RVA: 0x000DE87C File Offset: 0x000DCA7C
		public void RefreshBindingWithChildren()
		{
			GameMenuVM datasource_Root = this._datasource_Root;
			this.SetDataSource(null);
			this.SetDataSource(datasource_Root);
		}

		// Token: 0x06001E6F RID: 7791 RVA: 0x000DE8A0 File Offset: 0x000DCAA0
		public void DestroyDataSource()
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget_0_3.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3_1_0_0_1_0.EventFire -= this.EventListenerOf_widget_0_3_1_0_0_1_0;
				this._widget_0_3_1_0_0_1_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_3_1_0_0_1_0;
				this._widget_0_3_1_0_0_1_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_3_1_0_0_1_0;
				this._widget_0_3_1_0_0_1_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_3_1_0_0_1_0;
				this._widget_0_3_1_0_0_1_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_3_1_0_0_1_0;
				this._widget_0_3_1_0_0_1_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_3_1_0_0_1_0;
				this._widget_0_3_1_0_0_1_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_3_1_0_0_1_0;
				this._widget_0_3_1_0_0_1_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_3_1_0_0_1_0;
				this._widget_0_3_1_0_0_1_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_3_1_0_0_1_0;
				this._widget_0_3_1_0_0_1_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_3_1_0_0_1_0;
				if (this._datasource_Root_ProgressItemList != null)
				{
					this._datasource_Root_ProgressItemList.ListChanged -= this.OnList_datasource_Root_ProgressItemListChanged;
					for (int i = this._widget_0_3_1_0_0_1_1.ChildCount - 1; i >= 0; i--)
					{
						Widget child = this._widget_0_3_1_0_0_1_1.GetChild(i);
						((GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_1_ItemTemplate)child).OnBeforeRemovedChild(child);
						((GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_1_ItemTemplate)this._widget_0_3_1_0_0_1_1.GetChild(i)).DestroyDataSource();
					}
					this._datasource_Root_ProgressItemList = null;
				}
				if (this._datasource_Root_ItemList != null)
				{
					this._datasource_Root_ItemList.ListChanged -= this.OnList_datasource_Root_ItemListChanged;
					for (int j = this._widget_0_3_1_0_0_1_2.ChildCount - 1; j >= 0; j--)
					{
						Widget child2 = this._widget_0_3_1_0_0_1_2.GetChild(j);
						((GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_2_ItemTemplate)child2).OnBeforeRemovedChild(child2);
						((GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_2_ItemTemplate)this._widget_0_3_1_0_0_1_2.GetChild(j)).DestroyDataSource();
					}
					this._datasource_Root_ItemList = null;
				}
				if (this._datasource_Root_PlunderItems != null)
				{
					this._datasource_Root_PlunderItems.ListChanged -= this.OnList_datasource_Root_PlunderItemsChanged;
					for (int k = this._widget_0_3_1_0_0_1_3.ChildCount - 1; k >= 0; k--)
					{
						Widget child3 = this._widget_0_3_1_0_0_1_3.GetChild(k);
						((GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_3_ItemTemplate)child3).OnBeforeRemovedChild(child3);
						((GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_3_ItemTemplate)this._widget_0_3_1_0_0_1_3.GetChild(k)).DestroyDataSource();
					}
					this._datasource_Root_PlunderItems = null;
				}
				this._datasource_Root = null;
			}
		}

		// Token: 0x06001E70 RID: 7792 RVA: 0x000DEC93 File Offset: 0x000DCE93
		public void SetDataSource(GameMenuVM dataSource)
		{
			this.RefreshDataSource_datasource_Root(dataSource);
		}

		// Token: 0x06001E71 RID: 7793 RVA: 0x000DEC9C File Offset: 0x000DCE9C
		private void EventListenerOf_widget_0_3_1_0_0_1_0(Widget widget, string commandName, object[] args)
		{
			if (commandName == "LinkClick")
			{
				string text = (string)args[0];
				this._datasource_Root.ExecuteLink(text);
			}
		}

		// Token: 0x06001E72 RID: 7794 RVA: 0x000DECCB File Offset: 0x000DCECB
		private void PropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
		}

		// Token: 0x06001E73 RID: 7795 RVA: 0x000DECD4 File Offset: 0x000DCED4
		private void boolPropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
		}

		// Token: 0x06001E74 RID: 7796 RVA: 0x000DECDD File Offset: 0x000DCEDD
		private void floatPropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
		}

		// Token: 0x06001E75 RID: 7797 RVA: 0x000DECE6 File Offset: 0x000DCEE6
		private void Vec2PropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
		}

		// Token: 0x06001E76 RID: 7798 RVA: 0x000DECEF File Offset: 0x000DCEEF
		private void Vector2PropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
		}

		// Token: 0x06001E77 RID: 7799 RVA: 0x000DECF8 File Offset: 0x000DCEF8
		private void doublePropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
		}

		// Token: 0x06001E78 RID: 7800 RVA: 0x000DED01 File Offset: 0x000DCF01
		private void intPropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
		}

		// Token: 0x06001E79 RID: 7801 RVA: 0x000DED0A File Offset: 0x000DCF0A
		private void uintPropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
		}

		// Token: 0x06001E7A RID: 7802 RVA: 0x000DED13 File Offset: 0x000DCF13
		private void ColorPropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
		}

		// Token: 0x06001E7B RID: 7803 RVA: 0x000DED1C File Offset: 0x000DCF1C
		private void HandleWidgetPropertyChangeOf_widget_0_3(string propertyName)
		{
			if (propertyName == "SpriteName")
			{
				this._datasource_Root.BackgroundCopy = this._widget_0_3.SpriteName;
				return;
			}
			if (propertyName == "Sprite")
			{
				this._datasource_Root.Background = this._widget_0_3.Sprite.Name;
				return;
			}
			if (propertyName == "MenuId")
			{
				this._datasource_Root.MenuId = this._widget_0_3.MenuId;
				return;
			}
			if (propertyName == "IsNight")
			{
				this._datasource_Root.IsNight = this._widget_0_3.IsNight;
				return;
			}
			if (propertyName == "IsEncounterMenu")
			{
				this._datasource_Root.IsEncounterMenu = this._widget_0_3.IsEncounterMenu;
				return;
			}
		}

		// Token: 0x06001E7C RID: 7804 RVA: 0x000DEDE2 File Offset: 0x000DCFE2
		private void PropertyChangedListenerOf_widget_0_3_1_0_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3_1_0_0_1_0(propertyName);
		}

		// Token: 0x06001E7D RID: 7805 RVA: 0x000DEDEB File Offset: 0x000DCFEB
		private void boolPropertyChangedListenerOf_widget_0_3_1_0_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3_1_0_0_1_0(propertyName);
		}

		// Token: 0x06001E7E RID: 7806 RVA: 0x000DEDF4 File Offset: 0x000DCFF4
		private void floatPropertyChangedListenerOf_widget_0_3_1_0_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3_1_0_0_1_0(propertyName);
		}

		// Token: 0x06001E7F RID: 7807 RVA: 0x000DEDFD File Offset: 0x000DCFFD
		private void Vec2PropertyChangedListenerOf_widget_0_3_1_0_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3_1_0_0_1_0(propertyName);
		}

		// Token: 0x06001E80 RID: 7808 RVA: 0x000DEE06 File Offset: 0x000DD006
		private void Vector2PropertyChangedListenerOf_widget_0_3_1_0_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3_1_0_0_1_0(propertyName);
		}

		// Token: 0x06001E81 RID: 7809 RVA: 0x000DEE0F File Offset: 0x000DD00F
		private void doublePropertyChangedListenerOf_widget_0_3_1_0_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3_1_0_0_1_0(propertyName);
		}

		// Token: 0x06001E82 RID: 7810 RVA: 0x000DEE18 File Offset: 0x000DD018
		private void intPropertyChangedListenerOf_widget_0_3_1_0_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3_1_0_0_1_0(propertyName);
		}

		// Token: 0x06001E83 RID: 7811 RVA: 0x000DEE21 File Offset: 0x000DD021
		private void uintPropertyChangedListenerOf_widget_0_3_1_0_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3_1_0_0_1_0(propertyName);
		}

		// Token: 0x06001E84 RID: 7812 RVA: 0x000DEE2A File Offset: 0x000DD02A
		private void ColorPropertyChangedListenerOf_widget_0_3_1_0_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3_1_0_0_1_0(propertyName);
		}

		// Token: 0x06001E85 RID: 7813 RVA: 0x000DEE33 File Offset: 0x000DD033
		private void HandleWidgetPropertyChangeOf_widget_0_3_1_0_0_1_0(string propertyName)
		{
			if (propertyName == "Text")
			{
				this._datasource_Root.ContextText = this._widget_0_3_1_0_0_1_0.Text;
				return;
			}
		}

		// Token: 0x06001E86 RID: 7814 RVA: 0x000DEE59 File Offset: 0x000DD059
		private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001E87 RID: 7815 RVA: 0x000DEE67 File Offset: 0x000DD067
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001E88 RID: 7816 RVA: 0x000DEE76 File Offset: 0x000DD076
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001E89 RID: 7817 RVA: 0x000DEE85 File Offset: 0x000DD085
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001E8A RID: 7818 RVA: 0x000DEE94 File Offset: 0x000DD094
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001E8B RID: 7819 RVA: 0x000DEEA3 File Offset: 0x000DD0A3
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001E8C RID: 7820 RVA: 0x000DEEB2 File Offset: 0x000DD0B2
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001E8D RID: 7821 RVA: 0x000DEEC1 File Offset: 0x000DD0C1
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001E8E RID: 7822 RVA: 0x000DEED0 File Offset: 0x000DD0D0
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001E8F RID: 7823 RVA: 0x000DEEE0 File Offset: 0x000DD0E0
		private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
		{
			if (propertyName == "ProgressItemList")
			{
				this.RefreshDataSource_datasource_Root_ProgressItemList(this._datasource_Root.ProgressItemList);
				return;
			}
			if (propertyName == "ItemList")
			{
				this.RefreshDataSource_datasource_Root_ItemList(this._datasource_Root.ItemList);
				return;
			}
			if (propertyName == "PlunderItems")
			{
				this.RefreshDataSource_datasource_Root_PlunderItems(this._datasource_Root.PlunderItems);
				return;
			}
			if (propertyName == "BackgroundCopy")
			{
				this._widget_0_3.SpriteName = this._datasource_Root.BackgroundCopy;
				return;
			}
			if (propertyName == "Background")
			{
				if (this._datasource_Root.Background != null)
				{
					this._widget_0_3.Sprite = base.Context.SpriteData.GetSprite(this._datasource_Root.Background);
				}
				return;
			}
			if (propertyName == "MenuId")
			{
				this._widget_0_3.MenuId = this._datasource_Root.MenuId;
				return;
			}
			if (propertyName == "IsNight")
			{
				this._widget_0_3.IsNight = this._datasource_Root.IsNight;
				return;
			}
			if (propertyName == "IsEncounterMenu")
			{
				this._widget_0_3.IsEncounterMenu = this._datasource_Root.IsEncounterMenu;
				return;
			}
			if (propertyName == "ContextText")
			{
				this._widget_0_3_1_0_0_1_0.Text = this._datasource_Root.ContextText;
				return;
			}
		}

		// Token: 0x06001E90 RID: 7824 RVA: 0x000DF040 File Offset: 0x000DD240
		public void OnList_datasource_Root_ProgressItemListChanged(object sender, ListChangedEventArgs e)
		{
			switch (e.ListChangedType)
			{
			case ListChangedType.Reset:
			{
				for (int i = this._widget_0_3_1_0_0_1_1.ChildCount - 1; i >= 0; i--)
				{
					Widget child = this._widget_0_3_1_0_0_1_1.GetChild(i);
					((GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_1_ItemTemplate)child).OnBeforeRemovedChild(child);
					Widget child2 = this._widget_0_3_1_0_0_1_1.GetChild(i);
					((GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_1_ItemTemplate)child2).SetDataSource(null);
					this._widget_0_3_1_0_0_1_1.RemoveChild(child2);
				}
				return;
			}
			case ListChangedType.Sorted:
			{
				for (int j = 0; j < this._datasource_Root_ProgressItemList.Count; j++)
				{
					GameMenuItemProgressVM bindingObject = this._datasource_Root_ProgressItemList[j];
					this._widget_0_3_1_0_0_1_1.FindChild((Widget widget) => widget.GetComponent<GeneratedWidgetData>().Data == bindingObject).SetSiblingIndex(j, false);
				}
				return;
			}
			case ListChangedType.ItemAdded:
			{
				GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_1_ItemTemplate gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_1_ItemTemplate = new GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_1_ItemTemplate(base.Context);
				GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_1_ItemTemplate);
				GameMenuItemProgressVM gameMenuItemProgressVM = this._datasource_Root_ProgressItemList[e.NewIndex];
				generatedWidgetData.Data = gameMenuItemProgressVM;
				gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_1_ItemTemplate.AddComponent(generatedWidgetData);
				this._widget_0_3_1_0_0_1_1.AddChildAtIndex(gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_1_ItemTemplate, e.NewIndex);
				gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_1_ItemTemplate.CreateWidgets();
				gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_1_ItemTemplate.SetIds();
				gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_1_ItemTemplate.SetAttributes();
				gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_1_ItemTemplate.SetDataSource(gameMenuItemProgressVM);
				return;
			}
			case ListChangedType.ItemBeforeDeleted:
			{
				Widget child3 = this._widget_0_3_1_0_0_1_1.GetChild(e.NewIndex);
				((GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_1_ItemTemplate)child3).OnBeforeRemovedChild(child3);
				return;
			}
			case ListChangedType.ItemDeleted:
			{
				Widget child4 = this._widget_0_3_1_0_0_1_1.GetChild(e.NewIndex);
				((GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_1_ItemTemplate)child4).SetDataSource(null);
				this._widget_0_3_1_0_0_1_1.RemoveChild(child4);
				break;
			}
			case ListChangedType.ItemChanged:
				break;
			default:
				return;
			}
		}

		// Token: 0x06001E91 RID: 7825 RVA: 0x000DF1DC File Offset: 0x000DD3DC
		public void OnList_datasource_Root_ItemListChanged(object sender, ListChangedEventArgs e)
		{
			switch (e.ListChangedType)
			{
			case ListChangedType.Reset:
			{
				for (int i = this._widget_0_3_1_0_0_1_2.ChildCount - 1; i >= 0; i--)
				{
					Widget child = this._widget_0_3_1_0_0_1_2.GetChild(i);
					((GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_2_ItemTemplate)child).OnBeforeRemovedChild(child);
					Widget child2 = this._widget_0_3_1_0_0_1_2.GetChild(i);
					((GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_2_ItemTemplate)child2).SetDataSource(null);
					this._widget_0_3_1_0_0_1_2.RemoveChild(child2);
				}
				return;
			}
			case ListChangedType.Sorted:
			{
				for (int j = 0; j < this._datasource_Root_ItemList.Count; j++)
				{
					GameMenuItemVM bindingObject = this._datasource_Root_ItemList[j];
					this._widget_0_3_1_0_0_1_2.FindChild((Widget widget) => widget.GetComponent<GeneratedWidgetData>().Data == bindingObject).SetSiblingIndex(j, false);
				}
				return;
			}
			case ListChangedType.ItemAdded:
			{
				GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_2_ItemTemplate gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_2_ItemTemplate = new GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_2_ItemTemplate(base.Context);
				GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_2_ItemTemplate);
				GameMenuItemVM gameMenuItemVM = this._datasource_Root_ItemList[e.NewIndex];
				generatedWidgetData.Data = gameMenuItemVM;
				gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_2_ItemTemplate.AddComponent(generatedWidgetData);
				this._widget_0_3_1_0_0_1_2.AddChildAtIndex(gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_2_ItemTemplate, e.NewIndex);
				gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_2_ItemTemplate.CreateWidgets();
				gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_2_ItemTemplate.SetIds();
				gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_2_ItemTemplate.SetAttributes();
				gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_2_ItemTemplate.SetDataSource(gameMenuItemVM);
				return;
			}
			case ListChangedType.ItemBeforeDeleted:
			{
				Widget child3 = this._widget_0_3_1_0_0_1_2.GetChild(e.NewIndex);
				((GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_2_ItemTemplate)child3).OnBeforeRemovedChild(child3);
				return;
			}
			case ListChangedType.ItemDeleted:
			{
				Widget child4 = this._widget_0_3_1_0_0_1_2.GetChild(e.NewIndex);
				((GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_2_ItemTemplate)child4).SetDataSource(null);
				this._widget_0_3_1_0_0_1_2.RemoveChild(child4);
				break;
			}
			case ListChangedType.ItemChanged:
				break;
			default:
				return;
			}
		}

		// Token: 0x06001E92 RID: 7826 RVA: 0x000DF378 File Offset: 0x000DD578
		public void OnList_datasource_Root_PlunderItemsChanged(object sender, ListChangedEventArgs e)
		{
			switch (e.ListChangedType)
			{
			case ListChangedType.Reset:
			{
				for (int i = this._widget_0_3_1_0_0_1_3.ChildCount - 1; i >= 0; i--)
				{
					Widget child = this._widget_0_3_1_0_0_1_3.GetChild(i);
					((GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_3_ItemTemplate)child).OnBeforeRemovedChild(child);
					Widget child2 = this._widget_0_3_1_0_0_1_3.GetChild(i);
					((GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_3_ItemTemplate)child2).SetDataSource(null);
					this._widget_0_3_1_0_0_1_3.RemoveChild(child2);
				}
				return;
			}
			case ListChangedType.Sorted:
			{
				for (int j = 0; j < this._datasource_Root_PlunderItems.Count; j++)
				{
					GameMenuPlunderItemVM bindingObject = this._datasource_Root_PlunderItems[j];
					this._widget_0_3_1_0_0_1_3.FindChild((Widget widget) => widget.GetComponent<GeneratedWidgetData>().Data == bindingObject).SetSiblingIndex(j, false);
				}
				return;
			}
			case ListChangedType.ItemAdded:
			{
				GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_3_ItemTemplate gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_3_ItemTemplate = new GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_3_ItemTemplate(base.Context);
				GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_3_ItemTemplate);
				GameMenuPlunderItemVM gameMenuPlunderItemVM = this._datasource_Root_PlunderItems[e.NewIndex];
				generatedWidgetData.Data = gameMenuPlunderItemVM;
				gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_3_ItemTemplate.AddComponent(generatedWidgetData);
				this._widget_0_3_1_0_0_1_3.AddChildAtIndex(gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_3_ItemTemplate, e.NewIndex);
				gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_3_ItemTemplate.CreateWidgets();
				gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_3_ItemTemplate.SetIds();
				gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_3_ItemTemplate.SetAttributes();
				gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_3_ItemTemplate.SetDataSource(gameMenuPlunderItemVM);
				return;
			}
			case ListChangedType.ItemBeforeDeleted:
			{
				Widget child3 = this._widget_0_3_1_0_0_1_3.GetChild(e.NewIndex);
				((GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_3_ItemTemplate)child3).OnBeforeRemovedChild(child3);
				return;
			}
			case ListChangedType.ItemDeleted:
			{
				Widget child4 = this._widget_0_3_1_0_0_1_3.GetChild(e.NewIndex);
				((GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_3_ItemTemplate)child4).SetDataSource(null);
				this._widget_0_3_1_0_0_1_3.RemoveChild(child4);
				break;
			}
			case ListChangedType.ItemChanged:
				break;
			default:
				return;
			}
		}

		// Token: 0x06001E93 RID: 7827 RVA: 0x000DF514 File Offset: 0x000DD714
		private void RefreshDataSource_datasource_Root(GameMenuVM newDataSource)
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget_0_3.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3_1_0_0_1_0.EventFire -= this.EventListenerOf_widget_0_3_1_0_0_1_0;
				this._widget_0_3_1_0_0_1_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_3_1_0_0_1_0;
				this._widget_0_3_1_0_0_1_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_3_1_0_0_1_0;
				this._widget_0_3_1_0_0_1_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_3_1_0_0_1_0;
				this._widget_0_3_1_0_0_1_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_3_1_0_0_1_0;
				this._widget_0_3_1_0_0_1_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_3_1_0_0_1_0;
				this._widget_0_3_1_0_0_1_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_3_1_0_0_1_0;
				this._widget_0_3_1_0_0_1_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_3_1_0_0_1_0;
				this._widget_0_3_1_0_0_1_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_3_1_0_0_1_0;
				this._widget_0_3_1_0_0_1_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_3_1_0_0_1_0;
				if (this._datasource_Root_ProgressItemList != null)
				{
					this._datasource_Root_ProgressItemList.ListChanged -= this.OnList_datasource_Root_ProgressItemListChanged;
					for (int i = this._widget_0_3_1_0_0_1_1.ChildCount - 1; i >= 0; i--)
					{
						Widget child = this._widget_0_3_1_0_0_1_1.GetChild(i);
						((GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_1_ItemTemplate)child).OnBeforeRemovedChild(child);
						Widget child2 = this._widget_0_3_1_0_0_1_1.GetChild(i);
						((GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_1_ItemTemplate)child2).SetDataSource(null);
						this._widget_0_3_1_0_0_1_1.RemoveChild(child2);
					}
					this._datasource_Root_ProgressItemList = null;
				}
				if (this._datasource_Root_ItemList != null)
				{
					this._datasource_Root_ItemList.ListChanged -= this.OnList_datasource_Root_ItemListChanged;
					for (int j = this._widget_0_3_1_0_0_1_2.ChildCount - 1; j >= 0; j--)
					{
						Widget child3 = this._widget_0_3_1_0_0_1_2.GetChild(j);
						((GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_2_ItemTemplate)child3).OnBeforeRemovedChild(child3);
						Widget child4 = this._widget_0_3_1_0_0_1_2.GetChild(j);
						((GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_2_ItemTemplate)child4).SetDataSource(null);
						this._widget_0_3_1_0_0_1_2.RemoveChild(child4);
					}
					this._datasource_Root_ItemList = null;
				}
				if (this._datasource_Root_PlunderItems != null)
				{
					this._datasource_Root_PlunderItems.ListChanged -= this.OnList_datasource_Root_PlunderItemsChanged;
					for (int k = this._widget_0_3_1_0_0_1_3.ChildCount - 1; k >= 0; k--)
					{
						Widget child5 = this._widget_0_3_1_0_0_1_3.GetChild(k);
						((GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_3_ItemTemplate)child5).OnBeforeRemovedChild(child5);
						Widget child6 = this._widget_0_3_1_0_0_1_3.GetChild(k);
						((GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_3_ItemTemplate)child6).SetDataSource(null);
						this._widget_0_3_1_0_0_1_3.RemoveChild(child6);
					}
					this._datasource_Root_PlunderItems = null;
				}
				this._datasource_Root = null;
			}
			this._datasource_Root = newDataSource;
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget_0_3.SpriteName = this._datasource_Root.BackgroundCopy;
				if (this._datasource_Root.Background != null)
				{
					this._widget_0_3.Sprite = base.Context.SpriteData.GetSprite(this._datasource_Root.Background);
				}
				this._widget_0_3.MenuId = this._datasource_Root.MenuId;
				this._widget_0_3.IsNight = this._datasource_Root.IsNight;
				this._widget_0_3.IsEncounterMenu = this._datasource_Root.IsEncounterMenu;
				this._widget_0_3.PropertyChanged += this.PropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.intPropertyChanged += this.intPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3_1_0_0_1_0.Text = this._datasource_Root.ContextText;
				this._widget_0_3_1_0_0_1_0.EventFire += this.EventListenerOf_widget_0_3_1_0_0_1_0;
				this._widget_0_3_1_0_0_1_0.PropertyChanged += this.PropertyChangedListenerOf_widget_0_3_1_0_0_1_0;
				this._widget_0_3_1_0_0_1_0.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_0_3_1_0_0_1_0;
				this._widget_0_3_1_0_0_1_0.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_0_3_1_0_0_1_0;
				this._widget_0_3_1_0_0_1_0.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_0_3_1_0_0_1_0;
				this._widget_0_3_1_0_0_1_0.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_0_3_1_0_0_1_0;
				this._widget_0_3_1_0_0_1_0.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_0_3_1_0_0_1_0;
				this._widget_0_3_1_0_0_1_0.intPropertyChanged += this.intPropertyChangedListenerOf_widget_0_3_1_0_0_1_0;
				this._widget_0_3_1_0_0_1_0.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_0_3_1_0_0_1_0;
				this._widget_0_3_1_0_0_1_0.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_0_3_1_0_0_1_0;
				this._datasource_Root_ProgressItemList = this._datasource_Root.ProgressItemList;
				if (this._datasource_Root_ProgressItemList != null)
				{
					this._datasource_Root_ProgressItemList.ListChanged += this.OnList_datasource_Root_ProgressItemListChanged;
					for (int l = 0; l < this._datasource_Root_ProgressItemList.Count; l++)
					{
						GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_1_ItemTemplate gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_1_ItemTemplate = new GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_1_ItemTemplate(base.Context);
						GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_1_ItemTemplate);
						GameMenuItemProgressVM gameMenuItemProgressVM = this._datasource_Root_ProgressItemList[l];
						generatedWidgetData.Data = gameMenuItemProgressVM;
						gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_1_ItemTemplate.AddComponent(generatedWidgetData);
						this._widget_0_3_1_0_0_1_1.AddChildAtIndex(gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_1_ItemTemplate, l);
						gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_1_ItemTemplate.CreateWidgets();
						gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_1_ItemTemplate.SetIds();
						gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_1_ItemTemplate.SetAttributes();
						gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_1_ItemTemplate.SetDataSource(gameMenuItemProgressVM);
					}
				}
				this._datasource_Root_ItemList = this._datasource_Root.ItemList;
				if (this._datasource_Root_ItemList != null)
				{
					this._datasource_Root_ItemList.ListChanged += this.OnList_datasource_Root_ItemListChanged;
					for (int m = 0; m < this._datasource_Root_ItemList.Count; m++)
					{
						GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_2_ItemTemplate gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_2_ItemTemplate = new GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_2_ItemTemplate(base.Context);
						GeneratedWidgetData generatedWidgetData2 = new GeneratedWidgetData(gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_2_ItemTemplate);
						GameMenuItemVM gameMenuItemVM = this._datasource_Root_ItemList[m];
						generatedWidgetData2.Data = gameMenuItemVM;
						gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_2_ItemTemplate.AddComponent(generatedWidgetData2);
						this._widget_0_3_1_0_0_1_2.AddChildAtIndex(gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_2_ItemTemplate, m);
						gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_2_ItemTemplate.CreateWidgets();
						gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_2_ItemTemplate.SetIds();
						gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_2_ItemTemplate.SetAttributes();
						gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_2_ItemTemplate.SetDataSource(gameMenuItemVM);
					}
				}
				this._datasource_Root_PlunderItems = this._datasource_Root.PlunderItems;
				if (this._datasource_Root_PlunderItems != null)
				{
					this._datasource_Root_PlunderItems.ListChanged += this.OnList_datasource_Root_PlunderItemsChanged;
					for (int n = 0; n < this._datasource_Root_PlunderItems.Count; n++)
					{
						GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_3_ItemTemplate gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_3_ItemTemplate = new GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_3_ItemTemplate(base.Context);
						GeneratedWidgetData generatedWidgetData3 = new GeneratedWidgetData(gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_3_ItemTemplate);
						GameMenuPlunderItemVM gameMenuPlunderItemVM = this._datasource_Root_PlunderItems[n];
						generatedWidgetData3.Data = gameMenuPlunderItemVM;
						gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_3_ItemTemplate.AddComponent(generatedWidgetData3);
						this._widget_0_3_1_0_0_1_3.AddChildAtIndex(gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_3_ItemTemplate, n);
						gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_3_ItemTemplate.CreateWidgets();
						gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_3_ItemTemplate.SetIds();
						gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_3_ItemTemplate.SetAttributes();
						gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_3_ItemTemplate.SetDataSource(gameMenuPlunderItemVM);
					}
				}
			}
		}

		// Token: 0x06001E94 RID: 7828 RVA: 0x000DFE8C File Offset: 0x000DE08C
		private void RefreshDataSource_datasource_Root_ProgressItemList(MBBindingList<GameMenuItemProgressVM> newDataSource)
		{
			if (this._datasource_Root_ProgressItemList != null)
			{
				this._datasource_Root_ProgressItemList.ListChanged -= this.OnList_datasource_Root_ProgressItemListChanged;
				for (int i = this._widget_0_3_1_0_0_1_1.ChildCount - 1; i >= 0; i--)
				{
					Widget child = this._widget_0_3_1_0_0_1_1.GetChild(i);
					((GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_1_ItemTemplate)child).OnBeforeRemovedChild(child);
					Widget child2 = this._widget_0_3_1_0_0_1_1.GetChild(i);
					((GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_1_ItemTemplate)child2).SetDataSource(null);
					this._widget_0_3_1_0_0_1_1.RemoveChild(child2);
				}
				this._datasource_Root_ProgressItemList = null;
			}
			this._datasource_Root_ProgressItemList = newDataSource;
			this._datasource_Root_ProgressItemList = this._datasource_Root.ProgressItemList;
			if (this._datasource_Root_ProgressItemList != null)
			{
				this._datasource_Root_ProgressItemList.ListChanged += this.OnList_datasource_Root_ProgressItemListChanged;
				for (int j = 0; j < this._datasource_Root_ProgressItemList.Count; j++)
				{
					GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_1_ItemTemplate gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_1_ItemTemplate = new GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_1_ItemTemplate(base.Context);
					GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_1_ItemTemplate);
					GameMenuItemProgressVM gameMenuItemProgressVM = this._datasource_Root_ProgressItemList[j];
					generatedWidgetData.Data = gameMenuItemProgressVM;
					gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_1_ItemTemplate.AddComponent(generatedWidgetData);
					this._widget_0_3_1_0_0_1_1.AddChildAtIndex(gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_1_ItemTemplate, j);
					gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_1_ItemTemplate.CreateWidgets();
					gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_1_ItemTemplate.SetIds();
					gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_1_ItemTemplate.SetAttributes();
					gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_1_ItemTemplate.SetDataSource(gameMenuItemProgressVM);
				}
			}
		}

		// Token: 0x06001E95 RID: 7829 RVA: 0x000DFFC8 File Offset: 0x000DE1C8
		private void RefreshDataSource_datasource_Root_ItemList(MBBindingList<GameMenuItemVM> newDataSource)
		{
			if (this._datasource_Root_ItemList != null)
			{
				this._datasource_Root_ItemList.ListChanged -= this.OnList_datasource_Root_ItemListChanged;
				for (int i = this._widget_0_3_1_0_0_1_2.ChildCount - 1; i >= 0; i--)
				{
					Widget child = this._widget_0_3_1_0_0_1_2.GetChild(i);
					((GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_2_ItemTemplate)child).OnBeforeRemovedChild(child);
					Widget child2 = this._widget_0_3_1_0_0_1_2.GetChild(i);
					((GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_2_ItemTemplate)child2).SetDataSource(null);
					this._widget_0_3_1_0_0_1_2.RemoveChild(child2);
				}
				this._datasource_Root_ItemList = null;
			}
			this._datasource_Root_ItemList = newDataSource;
			this._datasource_Root_ItemList = this._datasource_Root.ItemList;
			if (this._datasource_Root_ItemList != null)
			{
				this._datasource_Root_ItemList.ListChanged += this.OnList_datasource_Root_ItemListChanged;
				for (int j = 0; j < this._datasource_Root_ItemList.Count; j++)
				{
					GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_2_ItemTemplate gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_2_ItemTemplate = new GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_2_ItemTemplate(base.Context);
					GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_2_ItemTemplate);
					GameMenuItemVM gameMenuItemVM = this._datasource_Root_ItemList[j];
					generatedWidgetData.Data = gameMenuItemVM;
					gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_2_ItemTemplate.AddComponent(generatedWidgetData);
					this._widget_0_3_1_0_0_1_2.AddChildAtIndex(gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_2_ItemTemplate, j);
					gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_2_ItemTemplate.CreateWidgets();
					gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_2_ItemTemplate.SetIds();
					gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_2_ItemTemplate.SetAttributes();
					gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_2_ItemTemplate.SetDataSource(gameMenuItemVM);
				}
			}
		}

		// Token: 0x06001E96 RID: 7830 RVA: 0x000E0104 File Offset: 0x000DE304
		private void RefreshDataSource_datasource_Root_PlunderItems(MBBindingList<GameMenuPlunderItemVM> newDataSource)
		{
			if (this._datasource_Root_PlunderItems != null)
			{
				this._datasource_Root_PlunderItems.ListChanged -= this.OnList_datasource_Root_PlunderItemsChanged;
				for (int i = this._widget_0_3_1_0_0_1_3.ChildCount - 1; i >= 0; i--)
				{
					Widget child = this._widget_0_3_1_0_0_1_3.GetChild(i);
					((GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_3_ItemTemplate)child).OnBeforeRemovedChild(child);
					Widget child2 = this._widget_0_3_1_0_0_1_3.GetChild(i);
					((GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_3_ItemTemplate)child2).SetDataSource(null);
					this._widget_0_3_1_0_0_1_3.RemoveChild(child2);
				}
				this._datasource_Root_PlunderItems = null;
			}
			this._datasource_Root_PlunderItems = newDataSource;
			this._datasource_Root_PlunderItems = this._datasource_Root.PlunderItems;
			if (this._datasource_Root_PlunderItems != null)
			{
				this._datasource_Root_PlunderItems.ListChanged += this.OnList_datasource_Root_PlunderItemsChanged;
				for (int j = 0; j < this._datasource_Root_PlunderItems.Count; j++)
				{
					GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_3_ItemTemplate gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_3_ItemTemplate = new GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_3_ItemTemplate(base.Context);
					GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_3_ItemTemplate);
					GameMenuPlunderItemVM gameMenuPlunderItemVM = this._datasource_Root_PlunderItems[j];
					generatedWidgetData.Data = gameMenuPlunderItemVM;
					gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_3_ItemTemplate.AddComponent(generatedWidgetData);
					this._widget_0_3_1_0_0_1_3.AddChildAtIndex(gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_3_ItemTemplate, j);
					gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_3_ItemTemplate.CreateWidgets();
					gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_3_ItemTemplate.SetIds();
					gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_3_ItemTemplate.SetAttributes();
					gameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_3_ItemTemplate.SetDataSource(gameMenuPlunderItemVM);
				}
			}
		}

		// Token: 0x0400066D RID: 1645
		private Widget _widget;

		// Token: 0x0400066E RID: 1646
		private Widget _widget_0;

		// Token: 0x0400066F RID: 1647
		private ButtonWidget _widget_0_0;

		// Token: 0x04000670 RID: 1648
		private BrushWidget _widget_0_0_0;

		// Token: 0x04000671 RID: 1649
		private Widget _widget_0_1;

		// Token: 0x04000672 RID: 1650
		private NavigationScopeTargeter _widget_0_2;

		// Token: 0x04000673 RID: 1651
		private GameMenuWidget _widget_0_3;

		// Token: 0x04000674 RID: 1652
		private Widget _widget_0_3_0;

		// Token: 0x04000675 RID: 1653
		private TextWidget _widget_0_3_0_0;

		// Token: 0x04000676 RID: 1654
		private Widget _widget_0_3_1;

		// Token: 0x04000677 RID: 1655
		private ScrollablePanel _widget_0_3_1_0;

		// Token: 0x04000678 RID: 1656
		private Widget _widget_0_3_1_0_0;

		// Token: 0x04000679 RID: 1657
		private DimensionSyncWidget _widget_0_3_1_0_0_0;

		// Token: 0x0400067A RID: 1658
		private ListPanel _widget_0_3_1_0_0_1;

		// Token: 0x0400067B RID: 1659
		private AutoHideRichTextWidget _widget_0_3_1_0_0_1_0;

		// Token: 0x0400067C RID: 1660
		private ListPanel _widget_0_3_1_0_0_1_1;

		// Token: 0x0400067D RID: 1661
		private NavigatableListPanel _widget_0_3_1_0_0_1_2;

		// Token: 0x0400067E RID: 1662
		private GridWidget _widget_0_3_1_0_0_1_3;

		// Token: 0x0400067F RID: 1663
		private Widget _widget_0_3_1_1;

		// Token: 0x04000680 RID: 1664
		private ScrollbarWidget _widget_0_3_1_1_0;

		// Token: 0x04000681 RID: 1665
		private Widget _widget_0_3_1_1_0_0;

		// Token: 0x04000682 RID: 1666
		private BrushWidget _widget_0_3_2;

		// Token: 0x04000683 RID: 1667
		private GameMenuVM _datasource_Root;

		// Token: 0x04000684 RID: 1668
		private MBBindingList<GameMenuItemProgressVM> _datasource_Root_ProgressItemList;

		// Token: 0x04000685 RID: 1669
		private MBBindingList<GameMenuItemVM> _datasource_Root_ItemList;

		// Token: 0x04000686 RID: 1670
		private MBBindingList<GameMenuPlunderItemVM> _datasource_Root_PlunderItems;
	}
}
