using System;
using System.ComponentModel;
using System.Numerics;
using SandBox.ViewModelCollection.Missions.NameMarker;
using TaleWorlds.CampaignSystem.ViewModelCollection.Quests;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.GauntletUI.Data;
using TaleWorlds.GauntletUI.Layout;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets.Mission.NameMarker;

namespace SandBox.GauntletUI.AutoGenerated1
{
	// Token: 0x020000AD RID: 173
	public class NameMarker__SandBox_ViewModelCollection_Missions_NameMarker_MissionNameMarkerVM_Dependency_1_ItemTemplate : NameMarkerListPanel
	{
		// Token: 0x060025F6 RID: 9718 RVA: 0x001177B7 File Offset: 0x001159B7
		public NameMarker__SandBox_ViewModelCollection_Missions_NameMarker_MissionNameMarkerVM_Dependency_1_ItemTemplate(UIContext context)
			: base(context)
		{
		}

		// Token: 0x060025F7 RID: 9719 RVA: 0x001177C0 File Offset: 0x001159C0
		public void CreateWidgets()
		{
			this._widget = this;
			this._widget_0 = new BrushWidget(base.Context);
			this._widget.AddChild(this._widget_0);
			this._widget_0_0 = new ListPanel(base.Context);
			this._widget_0.AddChild(this._widget_0_0);
			this._widget_0_1 = new ListPanel(base.Context);
			this._widget_0.AddChild(this._widget_0_1);
			this._widget_0_1_0 = new TextWidget(base.Context);
			this._widget_0_1.AddChild(this._widget_0_1_0);
			this._widget_0_1_1 = new ListPanel(base.Context);
			this._widget_0_1.AddChild(this._widget_0_1_1);
			this._widget_0_1_1_0 = new BrushWidget(base.Context);
			this._widget_0_1_1.AddChild(this._widget_0_1_1_0);
			this._widget_0_1_1_1 = new TextWidget(base.Context);
			this._widget_0_1_1.AddChild(this._widget_0_1_1_1);
		}

		// Token: 0x060025F8 RID: 9720 RVA: 0x001178C4 File Offset: 0x00115AC4
		public void SetIds()
		{
			this._widget_0.Id = "TypeWidget";
			this._widget_0_1.Id = "NameAndDistanceContainer";
			this._widget_0_1_0.Id = "NameTextWidget";
			this._widget_0_1_1.Id = "DistanceInfo";
			this._widget_0_1_1_0.Id = "DistanceIcon";
			this._widget_0_1_1_1.Id = "DistanceText";
		}

		// Token: 0x060025F9 RID: 9721 RVA: 0x00117934 File Offset: 0x00115B34
		public void SetAttributes()
		{
			base.WidthSizePolicy = SizePolicy.Fixed;
			base.HeightSizePolicy = SizePolicy.Fixed;
			base.SuggestedHeight = 40f;
			base.TypeVisualWidget = this._widget_0;
			base.NameTextWidget = this._widget_0_1_0;
			base.DistanceTextWidget = this._widget_0_1_1_1;
			base.DistanceIconWidget = this._widget_0_1_1_0;
			base.StackLayout.LayoutMethod = LayoutMethod.VerticalTopToBottom;
			base.FarAlphaTarget = 0.5f;
			base.FarDistanceCutoff = 250f;
			base.CloseDistanceCutoff = 25f;
			base.IssueNotificationColor = new Color(1f, 1f, 1f, 1f);
			base.MainQuestNotificationColor = new Color(1f, 1f, 1f, 1f);
			base.EnemyColor = new Color(0.9294118f, 0.1098039f, 0.1411765f, 1f);
			base.FriendlyColor = new Color(0.3058824f, 0.8784314f, 0.2980392f, 1f);
			this._widget_0.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_0.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_0.Brush = base.Context.GetBrush("NameMarker.VisualBrush");
			this._widget_0.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_0.VerticalAlignment = VerticalAlignment.Center;
			this._widget_0_0.WidthSizePolicy = SizePolicy.CoverChildren;
			this._widget_0_0.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_0_0.StackLayout.LayoutMethod = LayoutMethod.HorizontalLeftToRight;
			this._widget_0_0.PositionYOffset = -40f;
			this._widget_0_0.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_0_1.WidthSizePolicy = SizePolicy.CoverChildren;
			this._widget_0_1.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_0_1.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_0_1.MarginTop = 50f;
			this._widget_0_1.StackLayout.LayoutMethod = LayoutMethod.VerticalTopToBottom;
			this._widget_0_1_0.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_0_1_0.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_0_1_0.SuggestedWidth = 150f;
			this._widget_0_1_0.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_0_1_0.Brush = base.Context.GetBrush("NameMarker.TextBrush");
			this._widget_0_1_0.OverrideDefaultStateSwitchingEnabled = true;
			this._widget_0_1_0.ClipContents = false;
			this._widget_0_1_1.WidthSizePolicy = SizePolicy.CoverChildren;
			this._widget_0_1_1.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_0_1_1.PositionYOffset = 0f;
			this._widget_0_1_1.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_0_1_1.StackLayout.LayoutMethod = LayoutMethod.HorizontalLeftToRight;
			this._widget_0_1_1_0.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_0_1_1_0.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_0_1_1_0.SuggestedWidth = 20f;
			this._widget_0_1_1_0.SuggestedHeight = 28f;
			this._widget_0_1_1_0.Brush = base.Context.GetBrush("NameMarker.Distance.Icon");
			this._widget_0_1_1_0.VerticalAlignment = VerticalAlignment.Center;
			this._widget_0_1_1_0.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_0_1_1_1.WidthSizePolicy = SizePolicy.CoverChildren;
			this._widget_0_1_1_1.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_0_1_1_1.Brush = base.Context.GetBrush("NameMarker.Distance.Text");
			this._widget_0_1_1_1.MarginLeft = 4f;
			this._widget_0_1_1_1.MarginTop = 5f;
			this._widget_0_1_1_1.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_0_1_1_1.VerticalAlignment = VerticalAlignment.Center;
		}

		// Token: 0x060025FA RID: 9722 RVA: 0x00117C8C File Offset: 0x00115E8C
		public void DestroyDataSource()
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget.PropertyChanged -= this.PropertyChangedListenerOf_widget;
				this._widget.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget;
				this._widget.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget;
				this._widget.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget;
				this._widget.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget;
				this._widget.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget;
				this._widget.intPropertyChanged -= this.intPropertyChangedListenerOf_widget;
				this._widget.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget;
				this._widget.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget;
				this._widget_0_1_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_1_0;
				this._widget_0_1_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_1_0;
				this._widget_0_1_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_1_0;
				this._widget_0_1_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_1_0;
				this._widget_0_1_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_1_0;
				this._widget_0_1_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_1_0;
				this._widget_0_1_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_1_0;
				this._widget_0_1_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_1_0;
				this._widget_0_1_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_1_0;
				this._widget_0_1_1_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_1_1_1;
				this._widget_0_1_1_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_1_1_1;
				this._widget_0_1_1_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_1_1_1;
				this._widget_0_1_1_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_1_1_1;
				this._widget_0_1_1_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_1_1_1;
				this._widget_0_1_1_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_1_1_1;
				this._widget_0_1_1_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_1_1_1;
				this._widget_0_1_1_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_1_1_1;
				this._widget_0_1_1_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_1_1_1;
				if (this._datasource_Root_Quests != null)
				{
					this._datasource_Root_Quests.ListChanged -= this.OnList_datasource_Root_QuestsChanged;
					for (int i = this._widget_0_0.ChildCount - 1; i >= 0; i--)
					{
						Widget child = this._widget_0_0.GetChild(i);
						((NameMarker__SandBox_ViewModelCollection_Missions_NameMarker_MissionNameMarkerVM_Dependency_2_ItemTemplate)child).OnBeforeRemovedChild(child);
						((NameMarker__SandBox_ViewModelCollection_Missions_NameMarker_MissionNameMarkerVM_Dependency_2_ItemTemplate)this._widget_0_0.GetChild(i)).DestroyDataSource();
					}
					this._datasource_Root_Quests = null;
				}
				this._datasource_Root = null;
			}
		}

		// Token: 0x060025FB RID: 9723 RVA: 0x00118054 File Offset: 0x00116254
		public void SetDataSource(MissionNameMarkerTargetBaseVM dataSource)
		{
			this.RefreshDataSource_datasource_Root(dataSource);
		}

		// Token: 0x060025FC RID: 9724 RVA: 0x0011805D File Offset: 0x0011625D
		private void PropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x060025FD RID: 9725 RVA: 0x00118066 File Offset: 0x00116266
		private void boolPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x060025FE RID: 9726 RVA: 0x0011806F File Offset: 0x0011626F
		private void floatPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x060025FF RID: 9727 RVA: 0x00118078 File Offset: 0x00116278
		private void Vec2PropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x06002600 RID: 9728 RVA: 0x00118081 File Offset: 0x00116281
		private void Vector2PropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x06002601 RID: 9729 RVA: 0x0011808A File Offset: 0x0011628A
		private void doublePropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x06002602 RID: 9730 RVA: 0x00118093 File Offset: 0x00116293
		private void intPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x06002603 RID: 9731 RVA: 0x0011809C File Offset: 0x0011629C
		private void uintPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x06002604 RID: 9732 RVA: 0x001180A5 File Offset: 0x001162A5
		private void ColorPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x06002605 RID: 9733 RVA: 0x001180B0 File Offset: 0x001162B0
		private void HandleWidgetPropertyChangeOf_widget(string propertyName)
		{
			if (propertyName == "Position")
			{
				this._datasource_Root.ScreenPosition = this._widget.Position;
				return;
			}
			if (propertyName == "HasIssue")
			{
				this._datasource_Root.IsTracked = this._widget.HasIssue;
				return;
			}
			if (propertyName == "HasMainQuest")
			{
				this._datasource_Root.IsQuestMainStory = this._widget.HasMainQuest;
				return;
			}
			if (propertyName == "IsEnemy")
			{
				this._datasource_Root.IsEnemy = this._widget.IsEnemy;
				return;
			}
			if (propertyName == "IsFriendly")
			{
				this._datasource_Root.IsFriendly = this._widget.IsFriendly;
				return;
			}
			if (propertyName == "NameType")
			{
				this._datasource_Root.NameType = this._widget.NameType;
				return;
			}
			if (propertyName == "IconType")
			{
				this._datasource_Root.IconType = this._widget.IconType;
				return;
			}
			if (propertyName == "IsMarkerEnabled")
			{
				this._datasource_Root.IsEnabled = this._widget.IsMarkerEnabled;
				return;
			}
			if (propertyName == "IsMarkerPersistent")
			{
				this._datasource_Root.IsPersistent = this._widget.IsMarkerPersistent;
				return;
			}
			if (propertyName == "Distance")
			{
				this._datasource_Root.Distance = this._widget.Distance;
				return;
			}
		}

		// Token: 0x06002606 RID: 9734 RVA: 0x00118225 File Offset: 0x00116425
		private void PropertyChangedListenerOf_widget_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1_0(propertyName);
		}

		// Token: 0x06002607 RID: 9735 RVA: 0x0011822E File Offset: 0x0011642E
		private void boolPropertyChangedListenerOf_widget_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1_0(propertyName);
		}

		// Token: 0x06002608 RID: 9736 RVA: 0x00118237 File Offset: 0x00116437
		private void floatPropertyChangedListenerOf_widget_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1_0(propertyName);
		}

		// Token: 0x06002609 RID: 9737 RVA: 0x00118240 File Offset: 0x00116440
		private void Vec2PropertyChangedListenerOf_widget_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1_0(propertyName);
		}

		// Token: 0x0600260A RID: 9738 RVA: 0x00118249 File Offset: 0x00116449
		private void Vector2PropertyChangedListenerOf_widget_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1_0(propertyName);
		}

		// Token: 0x0600260B RID: 9739 RVA: 0x00118252 File Offset: 0x00116452
		private void doublePropertyChangedListenerOf_widget_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1_0(propertyName);
		}

		// Token: 0x0600260C RID: 9740 RVA: 0x0011825B File Offset: 0x0011645B
		private void intPropertyChangedListenerOf_widget_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1_0(propertyName);
		}

		// Token: 0x0600260D RID: 9741 RVA: 0x00118264 File Offset: 0x00116464
		private void uintPropertyChangedListenerOf_widget_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1_0(propertyName);
		}

		// Token: 0x0600260E RID: 9742 RVA: 0x0011826D File Offset: 0x0011646D
		private void ColorPropertyChangedListenerOf_widget_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1_0(propertyName);
		}

		// Token: 0x0600260F RID: 9743 RVA: 0x00118276 File Offset: 0x00116476
		private void HandleWidgetPropertyChangeOf_widget_0_1_0(string propertyName)
		{
			if (propertyName == "Text")
			{
				this._datasource_Root.Name = this._widget_0_1_0.Text;
				return;
			}
		}

		// Token: 0x06002610 RID: 9744 RVA: 0x0011829C File Offset: 0x0011649C
		private void PropertyChangedListenerOf_widget_0_1_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1_1_1(propertyName);
		}

		// Token: 0x06002611 RID: 9745 RVA: 0x001182A5 File Offset: 0x001164A5
		private void boolPropertyChangedListenerOf_widget_0_1_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1_1_1(propertyName);
		}

		// Token: 0x06002612 RID: 9746 RVA: 0x001182AE File Offset: 0x001164AE
		private void floatPropertyChangedListenerOf_widget_0_1_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1_1_1(propertyName);
		}

		// Token: 0x06002613 RID: 9747 RVA: 0x001182B7 File Offset: 0x001164B7
		private void Vec2PropertyChangedListenerOf_widget_0_1_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1_1_1(propertyName);
		}

		// Token: 0x06002614 RID: 9748 RVA: 0x001182C0 File Offset: 0x001164C0
		private void Vector2PropertyChangedListenerOf_widget_0_1_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1_1_1(propertyName);
		}

		// Token: 0x06002615 RID: 9749 RVA: 0x001182C9 File Offset: 0x001164C9
		private void doublePropertyChangedListenerOf_widget_0_1_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1_1_1(propertyName);
		}

		// Token: 0x06002616 RID: 9750 RVA: 0x001182D2 File Offset: 0x001164D2
		private void intPropertyChangedListenerOf_widget_0_1_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1_1_1(propertyName);
		}

		// Token: 0x06002617 RID: 9751 RVA: 0x001182DB File Offset: 0x001164DB
		private void uintPropertyChangedListenerOf_widget_0_1_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1_1_1(propertyName);
		}

		// Token: 0x06002618 RID: 9752 RVA: 0x001182E4 File Offset: 0x001164E4
		private void ColorPropertyChangedListenerOf_widget_0_1_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1_1_1(propertyName);
		}

		// Token: 0x06002619 RID: 9753 RVA: 0x001182ED File Offset: 0x001164ED
		private void HandleWidgetPropertyChangeOf_widget_0_1_1_1(string propertyName)
		{
			if (propertyName == "IntText")
			{
				this._datasource_Root.Distance = this._widget_0_1_1_1.IntText;
				return;
			}
		}

		// Token: 0x0600261A RID: 9754 RVA: 0x00118313 File Offset: 0x00116513
		private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x0600261B RID: 9755 RVA: 0x00118321 File Offset: 0x00116521
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x0600261C RID: 9756 RVA: 0x00118330 File Offset: 0x00116530
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x0600261D RID: 9757 RVA: 0x0011833F File Offset: 0x0011653F
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x0600261E RID: 9758 RVA: 0x0011834E File Offset: 0x0011654E
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x0600261F RID: 9759 RVA: 0x0011835D File Offset: 0x0011655D
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06002620 RID: 9760 RVA: 0x0011836C File Offset: 0x0011656C
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06002621 RID: 9761 RVA: 0x0011837B File Offset: 0x0011657B
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06002622 RID: 9762 RVA: 0x0011838A File Offset: 0x0011658A
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06002623 RID: 9763 RVA: 0x0011839C File Offset: 0x0011659C
		private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
		{
			if (propertyName == "Quests")
			{
				this.RefreshDataSource_datasource_Root_Quests(this._datasource_Root.Quests);
				return;
			}
			if (propertyName == "ScreenPosition")
			{
				this._widget.Position = this._datasource_Root.ScreenPosition;
				return;
			}
			if (propertyName == "IsTracked")
			{
				this._widget.HasIssue = this._datasource_Root.IsTracked;
				return;
			}
			if (propertyName == "IsQuestMainStory")
			{
				this._widget.HasMainQuest = this._datasource_Root.IsQuestMainStory;
				return;
			}
			if (propertyName == "IsEnemy")
			{
				this._widget.IsEnemy = this._datasource_Root.IsEnemy;
				return;
			}
			if (propertyName == "IsFriendly")
			{
				this._widget.IsFriendly = this._datasource_Root.IsFriendly;
				return;
			}
			if (propertyName == "NameType")
			{
				this._widget.NameType = this._datasource_Root.NameType;
				return;
			}
			if (propertyName == "IconType")
			{
				this._widget.IconType = this._datasource_Root.IconType;
				return;
			}
			if (propertyName == "IsEnabled")
			{
				this._widget.IsMarkerEnabled = this._datasource_Root.IsEnabled;
				return;
			}
			if (propertyName == "IsPersistent")
			{
				this._widget.IsMarkerPersistent = this._datasource_Root.IsPersistent;
				return;
			}
			if (propertyName == "Distance")
			{
				this._widget.Distance = this._datasource_Root.Distance;
				this._widget_0_1_1_1.IntText = this._datasource_Root.Distance;
				return;
			}
			if (propertyName == "Name")
			{
				this._widget_0_1_0.Text = this._datasource_Root.Name;
				return;
			}
		}

		// Token: 0x06002624 RID: 9764 RVA: 0x0011856C File Offset: 0x0011676C
		public void OnList_datasource_Root_QuestsChanged(object sender, ListChangedEventArgs e)
		{
			switch (e.ListChangedType)
			{
			case ListChangedType.Reset:
			{
				for (int i = this._widget_0_0.ChildCount - 1; i >= 0; i--)
				{
					Widget child = this._widget_0_0.GetChild(i);
					((NameMarker__SandBox_ViewModelCollection_Missions_NameMarker_MissionNameMarkerVM_Dependency_2_ItemTemplate)child).OnBeforeRemovedChild(child);
					Widget child2 = this._widget_0_0.GetChild(i);
					((NameMarker__SandBox_ViewModelCollection_Missions_NameMarker_MissionNameMarkerVM_Dependency_2_ItemTemplate)child2).SetDataSource(null);
					this._widget_0_0.RemoveChild(child2);
				}
				return;
			}
			case ListChangedType.Sorted:
			{
				for (int j = 0; j < this._datasource_Root_Quests.Count; j++)
				{
					QuestMarkerVM bindingObject = this._datasource_Root_Quests[j];
					this._widget_0_0.FindChild((Widget widget) => widget.GetComponent<GeneratedWidgetData>().Data == bindingObject).SetSiblingIndex(j, false);
				}
				return;
			}
			case ListChangedType.ItemAdded:
			{
				NameMarker__SandBox_ViewModelCollection_Missions_NameMarker_MissionNameMarkerVM_Dependency_2_ItemTemplate nameMarker__SandBox_ViewModelCollection_Missions_NameMarker_MissionNameMarkerVM_Dependency_2_ItemTemplate = new NameMarker__SandBox_ViewModelCollection_Missions_NameMarker_MissionNameMarkerVM_Dependency_2_ItemTemplate(base.Context);
				GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(nameMarker__SandBox_ViewModelCollection_Missions_NameMarker_MissionNameMarkerVM_Dependency_2_ItemTemplate);
				QuestMarkerVM questMarkerVM = this._datasource_Root_Quests[e.NewIndex];
				generatedWidgetData.Data = questMarkerVM;
				nameMarker__SandBox_ViewModelCollection_Missions_NameMarker_MissionNameMarkerVM_Dependency_2_ItemTemplate.AddComponent(generatedWidgetData);
				this._widget_0_0.AddChildAtIndex(nameMarker__SandBox_ViewModelCollection_Missions_NameMarker_MissionNameMarkerVM_Dependency_2_ItemTemplate, e.NewIndex);
				nameMarker__SandBox_ViewModelCollection_Missions_NameMarker_MissionNameMarkerVM_Dependency_2_ItemTemplate.CreateWidgets();
				nameMarker__SandBox_ViewModelCollection_Missions_NameMarker_MissionNameMarkerVM_Dependency_2_ItemTemplate.SetIds();
				nameMarker__SandBox_ViewModelCollection_Missions_NameMarker_MissionNameMarkerVM_Dependency_2_ItemTemplate.SetAttributes();
				nameMarker__SandBox_ViewModelCollection_Missions_NameMarker_MissionNameMarkerVM_Dependency_2_ItemTemplate.SetDataSource(questMarkerVM);
				return;
			}
			case ListChangedType.ItemBeforeDeleted:
			{
				Widget child3 = this._widget_0_0.GetChild(e.NewIndex);
				((NameMarker__SandBox_ViewModelCollection_Missions_NameMarker_MissionNameMarkerVM_Dependency_2_ItemTemplate)child3).OnBeforeRemovedChild(child3);
				return;
			}
			case ListChangedType.ItemDeleted:
			{
				Widget child4 = this._widget_0_0.GetChild(e.NewIndex);
				((NameMarker__SandBox_ViewModelCollection_Missions_NameMarker_MissionNameMarkerVM_Dependency_2_ItemTemplate)child4).SetDataSource(null);
				this._widget_0_0.RemoveChild(child4);
				break;
			}
			case ListChangedType.ItemChanged:
				break;
			default:
				return;
			}
		}

		// Token: 0x06002625 RID: 9765 RVA: 0x00118708 File Offset: 0x00116908
		private void RefreshDataSource_datasource_Root(MissionNameMarkerTargetBaseVM newDataSource)
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget.PropertyChanged -= this.PropertyChangedListenerOf_widget;
				this._widget.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget;
				this._widget.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget;
				this._widget.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget;
				this._widget.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget;
				this._widget.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget;
				this._widget.intPropertyChanged -= this.intPropertyChangedListenerOf_widget;
				this._widget.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget;
				this._widget.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget;
				this._widget_0_1_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_1_0;
				this._widget_0_1_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_1_0;
				this._widget_0_1_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_1_0;
				this._widget_0_1_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_1_0;
				this._widget_0_1_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_1_0;
				this._widget_0_1_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_1_0;
				this._widget_0_1_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_1_0;
				this._widget_0_1_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_1_0;
				this._widget_0_1_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_1_0;
				this._widget_0_1_1_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_1_1_1;
				this._widget_0_1_1_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_1_1_1;
				this._widget_0_1_1_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_1_1_1;
				this._widget_0_1_1_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_1_1_1;
				this._widget_0_1_1_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_1_1_1;
				this._widget_0_1_1_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_1_1_1;
				this._widget_0_1_1_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_1_1_1;
				this._widget_0_1_1_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_1_1_1;
				this._widget_0_1_1_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_1_1_1;
				if (this._datasource_Root_Quests != null)
				{
					this._datasource_Root_Quests.ListChanged -= this.OnList_datasource_Root_QuestsChanged;
					for (int i = this._widget_0_0.ChildCount - 1; i >= 0; i--)
					{
						Widget child = this._widget_0_0.GetChild(i);
						((NameMarker__SandBox_ViewModelCollection_Missions_NameMarker_MissionNameMarkerVM_Dependency_2_ItemTemplate)child).OnBeforeRemovedChild(child);
						Widget child2 = this._widget_0_0.GetChild(i);
						((NameMarker__SandBox_ViewModelCollection_Missions_NameMarker_MissionNameMarkerVM_Dependency_2_ItemTemplate)child2).SetDataSource(null);
						this._widget_0_0.RemoveChild(child2);
					}
					this._datasource_Root_Quests = null;
				}
				this._datasource_Root = null;
			}
			this._datasource_Root = newDataSource;
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget.Position = this._datasource_Root.ScreenPosition;
				this._widget.HasIssue = this._datasource_Root.IsTracked;
				this._widget.HasMainQuest = this._datasource_Root.IsQuestMainStory;
				this._widget.IsEnemy = this._datasource_Root.IsEnemy;
				this._widget.IsFriendly = this._datasource_Root.IsFriendly;
				this._widget.NameType = this._datasource_Root.NameType;
				this._widget.IconType = this._datasource_Root.IconType;
				this._widget.IsMarkerEnabled = this._datasource_Root.IsEnabled;
				this._widget.IsMarkerPersistent = this._datasource_Root.IsPersistent;
				this._widget.Distance = this._datasource_Root.Distance;
				this._widget.PropertyChanged += this.PropertyChangedListenerOf_widget;
				this._widget.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget;
				this._widget.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget;
				this._widget.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget;
				this._widget.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget;
				this._widget.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget;
				this._widget.intPropertyChanged += this.intPropertyChangedListenerOf_widget;
				this._widget.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget;
				this._widget.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget;
				this._widget_0_1_0.Text = this._datasource_Root.Name;
				this._widget_0_1_0.PropertyChanged += this.PropertyChangedListenerOf_widget_0_1_0;
				this._widget_0_1_0.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_0_1_0;
				this._widget_0_1_0.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_0_1_0;
				this._widget_0_1_0.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_0_1_0;
				this._widget_0_1_0.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_0_1_0;
				this._widget_0_1_0.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_0_1_0;
				this._widget_0_1_0.intPropertyChanged += this.intPropertyChangedListenerOf_widget_0_1_0;
				this._widget_0_1_0.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_0_1_0;
				this._widget_0_1_0.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_0_1_0;
				this._widget_0_1_1_1.IntText = this._datasource_Root.Distance;
				this._widget_0_1_1_1.PropertyChanged += this.PropertyChangedListenerOf_widget_0_1_1_1;
				this._widget_0_1_1_1.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_0_1_1_1;
				this._widget_0_1_1_1.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_0_1_1_1;
				this._widget_0_1_1_1.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_0_1_1_1;
				this._widget_0_1_1_1.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_0_1_1_1;
				this._widget_0_1_1_1.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_0_1_1_1;
				this._widget_0_1_1_1.intPropertyChanged += this.intPropertyChangedListenerOf_widget_0_1_1_1;
				this._widget_0_1_1_1.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_0_1_1_1;
				this._widget_0_1_1_1.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_0_1_1_1;
				this._datasource_Root_Quests = this._datasource_Root.Quests;
				if (this._datasource_Root_Quests != null)
				{
					this._datasource_Root_Quests.ListChanged += this.OnList_datasource_Root_QuestsChanged;
					for (int j = 0; j < this._datasource_Root_Quests.Count; j++)
					{
						NameMarker__SandBox_ViewModelCollection_Missions_NameMarker_MissionNameMarkerVM_Dependency_2_ItemTemplate nameMarker__SandBox_ViewModelCollection_Missions_NameMarker_MissionNameMarkerVM_Dependency_2_ItemTemplate = new NameMarker__SandBox_ViewModelCollection_Missions_NameMarker_MissionNameMarkerVM_Dependency_2_ItemTemplate(base.Context);
						GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(nameMarker__SandBox_ViewModelCollection_Missions_NameMarker_MissionNameMarkerVM_Dependency_2_ItemTemplate);
						QuestMarkerVM questMarkerVM = this._datasource_Root_Quests[j];
						generatedWidgetData.Data = questMarkerVM;
						nameMarker__SandBox_ViewModelCollection_Missions_NameMarker_MissionNameMarkerVM_Dependency_2_ItemTemplate.AddComponent(generatedWidgetData);
						this._widget_0_0.AddChildAtIndex(nameMarker__SandBox_ViewModelCollection_Missions_NameMarker_MissionNameMarkerVM_Dependency_2_ItemTemplate, j);
						nameMarker__SandBox_ViewModelCollection_Missions_NameMarker_MissionNameMarkerVM_Dependency_2_ItemTemplate.CreateWidgets();
						nameMarker__SandBox_ViewModelCollection_Missions_NameMarker_MissionNameMarkerVM_Dependency_2_ItemTemplate.SetIds();
						nameMarker__SandBox_ViewModelCollection_Missions_NameMarker_MissionNameMarkerVM_Dependency_2_ItemTemplate.SetAttributes();
						nameMarker__SandBox_ViewModelCollection_Missions_NameMarker_MissionNameMarkerVM_Dependency_2_ItemTemplate.SetDataSource(questMarkerVM);
					}
				}
			}
		}

		// Token: 0x06002626 RID: 9766 RVA: 0x00118FE0 File Offset: 0x001171E0
		private void RefreshDataSource_datasource_Root_Quests(MBBindingList<QuestMarkerVM> newDataSource)
		{
			if (this._datasource_Root_Quests != null)
			{
				this._datasource_Root_Quests.ListChanged -= this.OnList_datasource_Root_QuestsChanged;
				for (int i = this._widget_0_0.ChildCount - 1; i >= 0; i--)
				{
					Widget child = this._widget_0_0.GetChild(i);
					((NameMarker__SandBox_ViewModelCollection_Missions_NameMarker_MissionNameMarkerVM_Dependency_2_ItemTemplate)child).OnBeforeRemovedChild(child);
					Widget child2 = this._widget_0_0.GetChild(i);
					((NameMarker__SandBox_ViewModelCollection_Missions_NameMarker_MissionNameMarkerVM_Dependency_2_ItemTemplate)child2).SetDataSource(null);
					this._widget_0_0.RemoveChild(child2);
				}
				this._datasource_Root_Quests = null;
			}
			this._datasource_Root_Quests = newDataSource;
			this._datasource_Root_Quests = this._datasource_Root.Quests;
			if (this._datasource_Root_Quests != null)
			{
				this._datasource_Root_Quests.ListChanged += this.OnList_datasource_Root_QuestsChanged;
				for (int j = 0; j < this._datasource_Root_Quests.Count; j++)
				{
					NameMarker__SandBox_ViewModelCollection_Missions_NameMarker_MissionNameMarkerVM_Dependency_2_ItemTemplate nameMarker__SandBox_ViewModelCollection_Missions_NameMarker_MissionNameMarkerVM_Dependency_2_ItemTemplate = new NameMarker__SandBox_ViewModelCollection_Missions_NameMarker_MissionNameMarkerVM_Dependency_2_ItemTemplate(base.Context);
					GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(nameMarker__SandBox_ViewModelCollection_Missions_NameMarker_MissionNameMarkerVM_Dependency_2_ItemTemplate);
					QuestMarkerVM questMarkerVM = this._datasource_Root_Quests[j];
					generatedWidgetData.Data = questMarkerVM;
					nameMarker__SandBox_ViewModelCollection_Missions_NameMarker_MissionNameMarkerVM_Dependency_2_ItemTemplate.AddComponent(generatedWidgetData);
					this._widget_0_0.AddChildAtIndex(nameMarker__SandBox_ViewModelCollection_Missions_NameMarker_MissionNameMarkerVM_Dependency_2_ItemTemplate, j);
					nameMarker__SandBox_ViewModelCollection_Missions_NameMarker_MissionNameMarkerVM_Dependency_2_ItemTemplate.CreateWidgets();
					nameMarker__SandBox_ViewModelCollection_Missions_NameMarker_MissionNameMarkerVM_Dependency_2_ItemTemplate.SetIds();
					nameMarker__SandBox_ViewModelCollection_Missions_NameMarker_MissionNameMarkerVM_Dependency_2_ItemTemplate.SetAttributes();
					nameMarker__SandBox_ViewModelCollection_Missions_NameMarker_MissionNameMarkerVM_Dependency_2_ItemTemplate.SetDataSource(questMarkerVM);
				}
			}
		}

		// Token: 0x040007E5 RID: 2021
		private NameMarkerListPanel _widget;

		// Token: 0x040007E6 RID: 2022
		private BrushWidget _widget_0;

		// Token: 0x040007E7 RID: 2023
		private ListPanel _widget_0_0;

		// Token: 0x040007E8 RID: 2024
		private ListPanel _widget_0_1;

		// Token: 0x040007E9 RID: 2025
		private TextWidget _widget_0_1_0;

		// Token: 0x040007EA RID: 2026
		private ListPanel _widget_0_1_1;

		// Token: 0x040007EB RID: 2027
		private BrushWidget _widget_0_1_1_0;

		// Token: 0x040007EC RID: 2028
		private TextWidget _widget_0_1_1_1;

		// Token: 0x040007ED RID: 2029
		private MissionNameMarkerTargetBaseVM _datasource_Root;

		// Token: 0x040007EE RID: 2030
		private MBBindingList<QuestMarkerVM> _datasource_Root_Quests;
	}
}
