using System;
using System.Collections.Generic;
using Helpers;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.Conversation;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.ObjectSystem;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.Issues
{
	// Token: 0x02000372 RID: 882
	public class ArmyNeedsSuppliesIssueBehavior : CampaignBehaviorBase
	{
		// Token: 0x060034EE RID: 13550 RVA: 0x000D8B41 File Offset: 0x000D6D41
		public override void RegisterEvents()
		{
			CampaignEvents.OnCheckForIssueEvent.AddNonSerializedListener(this, new Action<Hero>(this.OnCheckForIssue));
			CampaignEvents.ArmyDispersed.AddNonSerializedListener(this, new Action<Army, Army.ArmyDispersionReason, bool>(this.OnArmyDispersed));
		}

		// Token: 0x060034EF RID: 13551 RVA: 0x000D8B71 File Offset: 0x000D6D71
		private void OnArmyDispersed(Army army, Army.ArmyDispersionReason reason, bool arg3)
		{
			Hero armyOwner = army.ArmyOwner;
			if (((armyOwner != null) ? armyOwner.Issue : null) is ArmyNeedsSuppliesIssueBehavior.ArmyNeedsSuppliesIssue)
			{
				army.ArmyOwner.Issue.CompleteIssueWithStayAliveConditionsFailed();
			}
		}

		// Token: 0x060034F0 RID: 13552 RVA: 0x000D8B9C File Offset: 0x000D6D9C
		public void OnCheckForIssue(Hero hero)
		{
			if (this.ConditionsHold(hero))
			{
				Campaign.Current.IssueManager.AddPotentialIssueData(hero, new PotentialIssueData(new PotentialIssueData.StartIssueDelegate(this.OnStartIssue), typeof(ArmyNeedsSuppliesIssueBehavior.ArmyNeedsSuppliesIssue), IssueBase.IssueFrequency.VeryCommon, null));
				return;
			}
			Campaign.Current.IssueManager.AddPotentialIssueData(hero, new PotentialIssueData(typeof(ArmyNeedsSuppliesIssueBehavior.ArmyNeedsSuppliesIssue), IssueBase.IssueFrequency.VeryCommon));
		}

		// Token: 0x060034F1 RID: 13553 RVA: 0x000D8C00 File Offset: 0x000D6E00
		private bool ConditionsHold(Hero issueGiver)
		{
			return issueGiver.IsLord && issueGiver.MapFaction.IsKingdomFaction && issueGiver.PartyBelongedTo != null && issueGiver.PartyBelongedTo.Army != null && issueGiver.PartyBelongedTo.Army.ArmyOwner == issueGiver && issueGiver.PartyBelongedTo.Army.Cohesion > 80f;
		}

		// Token: 0x060034F2 RID: 13554 RVA: 0x000D8C63 File Offset: 0x000D6E63
		private IssueBase OnStartIssue(in PotentialIssueData pid, Hero issueOwner)
		{
			return new ArmyNeedsSuppliesIssueBehavior.ArmyNeedsSuppliesIssue(issueOwner);
		}

		// Token: 0x060034F3 RID: 13555 RVA: 0x000D8C6B File Offset: 0x000D6E6B
		public override void SyncData(IDataStore dataStore)
		{
		}

		// Token: 0x04000EEB RID: 3819
		private const IssueBase.IssueFrequency ArmyNeedsSuppliesIssueFrequency = IssueBase.IssueFrequency.VeryCommon;

		// Token: 0x04000EEC RID: 3820
		private const float QuestDurationInDays = 15f;

		// Token: 0x02000716 RID: 1814
		public class ArmyNeedsSuppliesIssue : IssueBase
		{
			// Token: 0x06005742 RID: 22338 RVA: 0x0019DC6F File Offset: 0x0019BE6F
			internal static void AutoGeneratedStaticCollectObjectsArmyNeedsSuppliesIssue(object o, List<object> collectedObjects)
			{
				((ArmyNeedsSuppliesIssueBehavior.ArmyNeedsSuppliesIssue)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x06005743 RID: 22339 RVA: 0x0019DC7D File Offset: 0x0019BE7D
			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x06005744 RID: 22340 RVA: 0x0019DC86 File Offset: 0x0019BE86
			internal static object AutoGeneratedGetMemberValueNumberOfManInArmy(object o)
			{
				return ((ArmyNeedsSuppliesIssueBehavior.ArmyNeedsSuppliesIssue)o).NumberOfManInArmy;
			}

			// Token: 0x17000FF9 RID: 4089
			// (get) Token: 0x06005745 RID: 22341 RVA: 0x0019DC98 File Offset: 0x0019BE98
			private int GrainAmount
			{
				get
				{
					return MathF.Ceiling((float)(this.NumberOfManInArmy / 20) * 5f);
				}
			}

			// Token: 0x17000FFA RID: 4090
			// (get) Token: 0x06005746 RID: 22342 RVA: 0x0019DCAF File Offset: 0x0019BEAF
			private int LiveStockAmount
			{
				get
				{
					return MathF.Ceiling((float)(this.NumberOfManInArmy / 20) * 0.5f);
				}
			}

			// Token: 0x17000FFB RID: 4091
			// (get) Token: 0x06005747 RID: 22343 RVA: 0x0019DCC6 File Offset: 0x0019BEC6
			private int WineAmount
			{
				get
				{
					return MathF.Ceiling((float)(this.NumberOfManInArmy / 20) * 0.5f);
				}
			}

			// Token: 0x17000FFC RID: 4092
			// (get) Token: 0x06005748 RID: 22344 RVA: 0x0019DCDD File Offset: 0x0019BEDD
			public override bool IsThereAlternativeSolution
			{
				get
				{
					return false;
				}
			}

			// Token: 0x17000FFD RID: 4093
			// (get) Token: 0x06005749 RID: 22345 RVA: 0x0019DCE0 File Offset: 0x0019BEE0
			public override bool IsThereLordSolution
			{
				get
				{
					return false;
				}
			}

			// Token: 0x17000FFE RID: 4094
			// (get) Token: 0x0600574A RID: 22346 RVA: 0x0019DCE3 File Offset: 0x0019BEE3
			public override TextObject IssueBriefByIssueGiver
			{
				get
				{
					return new TextObject("{=BW7v0g6q}We are about to go on campaign but my quartermaster reports that our food supplies will not be enough to keep us in the field for very long. I can't spare any of my lords, so I need someone else to bring us a large amount of supplies as soon as possible. Can you do this?[if:convo_grave][ib:closed]", null);
				}
			}

			// Token: 0x17000FFF RID: 4095
			// (get) Token: 0x0600574B RID: 22347 RVA: 0x0019DCF0 File Offset: 0x0019BEF0
			public override TextObject IssueAcceptByPlayer
			{
				get
				{
					TextObject textObject = new TextObject("{=YaZc08oa}I can bring supplies, your {?QUEST_GIVER.GENDER}ladyship{?}lordship{\\?}. Just tell me what you need.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.IssueOwner.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17001000 RID: 4096
			// (get) Token: 0x0600574C RID: 22348 RVA: 0x0019DD24 File Offset: 0x0019BF24
			public override TextObject IssueQuestSolutionExplanationByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=444rcko0}We need {GRAIN_AMOUNT} sacks of grain to meet our basic needs. And if you can find {LIVESTOCK_AMOUNT} live stocks and {WINE_AMOUNT} barrels of wine that would be a great favor. Men fight better after a good meal.", null);
					textObject.SetTextVariable("GRAIN_AMOUNT", this.GrainAmount);
					textObject.SetTextVariable("LIVESTOCK_AMOUNT", this.LiveStockAmount);
					textObject.SetTextVariable("WINE_AMOUNT", this.WineAmount);
					return textObject;
				}
			}

			// Token: 0x17001001 RID: 4097
			// (get) Token: 0x0600574D RID: 22349 RVA: 0x0019DD74 File Offset: 0x0019BF74
			public override TextObject IssueQuestSolutionAcceptByPlayer
			{
				get
				{
					TextObject textObject = new TextObject("{=ppO0hoT6}I'll deliver {GRAIN_AMOUNT} sacks of grain as soon as possible {?QUEST_GIVER.GENDER}lady{?}sir{\\?}, and try to find some livestock and wine as you requested.", null);
					textObject.SetTextVariable("GRAIN_AMOUNT", this.GrainAmount);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.IssueOwner.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17001002 RID: 4098
			// (get) Token: 0x0600574E RID: 22350 RVA: 0x0019DDB8 File Offset: 0x0019BFB8
			public override TextObject Title
			{
				get
				{
					return new TextObject("{=wVyqTlpS}Army Needs Supply", null);
				}
			}

			// Token: 0x17001003 RID: 4099
			// (get) Token: 0x0600574F RID: 22351 RVA: 0x0019DDC5 File Offset: 0x0019BFC5
			public override TextObject Description
			{
				get
				{
					TextObject textObject = new TextObject("{=iMq7M0bo}{QUEST_GIVER.LINK} asks you to provide them supplies for their military campaign.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.IssueOwner.CharacterObject, null, false);
					return textObject;
				}
			}

			// Token: 0x06005750 RID: 22352 RVA: 0x0019DDEA File Offset: 0x0019BFEA
			public ArmyNeedsSuppliesIssue(Hero issueOwner)
				: base(issueOwner, CampaignTime.DaysFromNow(15f))
			{
				this.NumberOfManInArmy = base.IssueOwner.PartyBelongedTo.Army.TotalRegularCount;
			}

			// Token: 0x06005751 RID: 22353 RVA: 0x0019DE18 File Offset: 0x0019C018
			protected override void OnGameLoad()
			{
			}

			// Token: 0x06005752 RID: 22354 RVA: 0x0019DE1A File Offset: 0x0019C01A
			protected override void HourlyTick()
			{
			}

			// Token: 0x06005753 RID: 22355 RVA: 0x0019DE1C File Offset: 0x0019C01C
			protected override QuestBase GenerateIssueQuest(string questId)
			{
				return new ArmyNeedsSuppliesIssueBehavior.ArmyNeedsSuppliesIssueQuest(questId, base.IssueOwner, CampaignTime.DaysFromNow(15f), this.RewardGold, this.GrainAmount, this.LiveStockAmount, this.WineAmount);
			}

			// Token: 0x06005754 RID: 22356 RVA: 0x0019DE4C File Offset: 0x0019C04C
			public override IssueBase.IssueFrequency GetFrequency()
			{
				return IssueBase.IssueFrequency.VeryCommon;
			}

			// Token: 0x06005755 RID: 22357 RVA: 0x0019DE50 File Offset: 0x0019C050
			protected override bool CanPlayerTakeQuestConditions(Hero issueGiver, out IssueBase.PreconditionFlags flags, out Hero relationHero, out SkillObject skill, out int requiredGold)
			{
				relationHero = null;
				skill = null;
				requiredGold = 0;
				flags = IssueBase.PreconditionFlags.None;
				if (issueGiver.GetRelationWithPlayer() < -10f)
				{
					flags |= IssueBase.PreconditionFlags.Relation;
					relationHero = issueGiver;
				}
				if (Hero.MainHero.IsKingdomLeader)
				{
					flags |= IssueBase.PreconditionFlags.MainHeroIsKingdomLeader;
				}
				if (issueGiver.MapFaction.IsAtWarWith(Hero.MainHero.MapFaction))
				{
					flags |= IssueBase.PreconditionFlags.AtWar;
				}
				if (Clan.PlayerClan.Tier < 1)
				{
					flags |= IssueBase.PreconditionFlags.ClanTier;
				}
				if (Clan.PlayerClan.Kingdom != issueGiver.MapFaction)
				{
					flags |= IssueBase.PreconditionFlags.NotInSameFaction;
				}
				return flags == IssueBase.PreconditionFlags.None;
			}

			// Token: 0x06005756 RID: 22358 RVA: 0x0019DEED File Offset: 0x0019C0ED
			protected override float GetIssueEffectAmountInternal(IssueEffect issueEffect)
			{
				if (issueEffect == DefaultIssueEffects.ClanInfluence)
				{
					return -0.1f;
				}
				return 0f;
			}

			// Token: 0x06005757 RID: 22359 RVA: 0x0019DF04 File Offset: 0x0019C104
			public override bool IssueStayAliveConditions()
			{
				if (base.IssueOwner.PartyBelongedTo != null && base.IssueOwner.PartyBelongedTo.Army != null && base.IssueOwner.PartyBelongedTo.Army.ArmyOwner == base.IssueOwner && base.IssueOwner.PartyBelongedTo.Army.Cohesion > 40f && base.IssueOwner.Clan != Clan.PlayerClan && base.IssueOwner.MapFaction.IsKingdomFaction)
				{
					this.NumberOfManInArmy = base.IssueOwner.PartyBelongedTo.Army.TotalRegularCount;
					return true;
				}
				return false;
			}

			// Token: 0x06005758 RID: 22360 RVA: 0x0019DFAE File Offset: 0x0019C1AE
			protected override void CompleteIssueWithTimedOutConsequences()
			{
			}

			// Token: 0x04001D12 RID: 7442
			[SaveableField(70)]
			private int NumberOfManInArmy;
		}

		// Token: 0x02000717 RID: 1815
		public class ArmyNeedsSuppliesIssueQuest : QuestBase
		{
			// Token: 0x06005759 RID: 22361 RVA: 0x0019DFB0 File Offset: 0x0019C1B0
			internal static void AutoGeneratedStaticCollectObjectsArmyNeedsSuppliesIssueQuest(object o, List<object> collectedObjects)
			{
				((ArmyNeedsSuppliesIssueBehavior.ArmyNeedsSuppliesIssueQuest)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x0600575A RID: 22362 RVA: 0x0019DFBE File Offset: 0x0019C1BE
			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
				collectedObjects.Add(this._grainLog);
				collectedObjects.Add(this._liveStockLog);
				collectedObjects.Add(this._wineLog);
			}

			// Token: 0x0600575B RID: 22363 RVA: 0x0019DFEB File Offset: 0x0019C1EB
			internal static object AutoGeneratedGetMemberValue_requestedGrainAmount(object o)
			{
				return ((ArmyNeedsSuppliesIssueBehavior.ArmyNeedsSuppliesIssueQuest)o)._requestedGrainAmount;
			}

			// Token: 0x0600575C RID: 22364 RVA: 0x0019DFFD File Offset: 0x0019C1FD
			internal static object AutoGeneratedGetMemberValue_requestedLiveStockAmount(object o)
			{
				return ((ArmyNeedsSuppliesIssueBehavior.ArmyNeedsSuppliesIssueQuest)o)._requestedLiveStockAmount;
			}

			// Token: 0x0600575D RID: 22365 RVA: 0x0019E00F File Offset: 0x0019C20F
			internal static object AutoGeneratedGetMemberValue_requestedWineAmount(object o)
			{
				return ((ArmyNeedsSuppliesIssueBehavior.ArmyNeedsSuppliesIssueQuest)o)._requestedWineAmount;
			}

			// Token: 0x0600575E RID: 22366 RVA: 0x0019E021 File Offset: 0x0019C221
			internal static object AutoGeneratedGetMemberValue_currentGrainAmount(object o)
			{
				return ((ArmyNeedsSuppliesIssueBehavior.ArmyNeedsSuppliesIssueQuest)o)._currentGrainAmount;
			}

			// Token: 0x0600575F RID: 22367 RVA: 0x0019E033 File Offset: 0x0019C233
			internal static object AutoGeneratedGetMemberValue_currentLiveStockAmount(object o)
			{
				return ((ArmyNeedsSuppliesIssueBehavior.ArmyNeedsSuppliesIssueQuest)o)._currentLiveStockAmount;
			}

			// Token: 0x06005760 RID: 22368 RVA: 0x0019E045 File Offset: 0x0019C245
			internal static object AutoGeneratedGetMemberValue_currentWineAmount(object o)
			{
				return ((ArmyNeedsSuppliesIssueBehavior.ArmyNeedsSuppliesIssueQuest)o)._currentWineAmount;
			}

			// Token: 0x06005761 RID: 22369 RVA: 0x0019E057 File Offset: 0x0019C257
			internal static object AutoGeneratedGetMemberValue_grainLog(object o)
			{
				return ((ArmyNeedsSuppliesIssueBehavior.ArmyNeedsSuppliesIssueQuest)o)._grainLog;
			}

			// Token: 0x06005762 RID: 22370 RVA: 0x0019E064 File Offset: 0x0019C264
			internal static object AutoGeneratedGetMemberValue_liveStockLog(object o)
			{
				return ((ArmyNeedsSuppliesIssueBehavior.ArmyNeedsSuppliesIssueQuest)o)._liveStockLog;
			}

			// Token: 0x06005763 RID: 22371 RVA: 0x0019E071 File Offset: 0x0019C271
			internal static object AutoGeneratedGetMemberValue_wineLog(object o)
			{
				return ((ArmyNeedsSuppliesIssueBehavior.ArmyNeedsSuppliesIssueQuest)o)._wineLog;
			}

			// Token: 0x17001004 RID: 4100
			// (get) Token: 0x06005764 RID: 22372 RVA: 0x0019E07E File Offset: 0x0019C27E
			public override bool IsRemainingTimeHidden
			{
				get
				{
					return false;
				}
			}

			// Token: 0x17001005 RID: 4101
			// (get) Token: 0x06005765 RID: 22373 RVA: 0x0019E081 File Offset: 0x0019C281
			public override TextObject Title
			{
				get
				{
					return new TextObject("{=wVyqTlpS}Army Needs Supply", null);
				}
			}

			// Token: 0x17001006 RID: 4102
			// (get) Token: 0x06005766 RID: 22374 RVA: 0x0019E090 File Offset: 0x0019C290
			private TextObject PlayerStartsQuestLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=GiaTh92Q}{QUEST_GIVER.LINK}, commanding an army of the {QUEST_GIVER_FACTION}, has told you that they need food supplies for their upcoming military campaign. {?QUEST_GIVER.GENDER}She{?}He{\\?} wanted you to deliver {GRAIN_AMOUNT} sacks of grain and although it's not necessary, to provide {LIVESTOCK_AMOUNT} live stocks and {WINE_AMOUNT} barrels of wine {?QUEST_GIVER.GENDER}she{?}he{\\?} would appreciate it.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("QUEST_GIVER_FACTION", base.QuestGiver.MapFaction.EncyclopediaLinkWithName);
					textObject.SetTextVariable("GRAIN_AMOUNT", this._requestedGrainAmount);
					textObject.SetTextVariable("LIVESTOCK_AMOUNT", this._requestedLiveStockAmount);
					textObject.SetTextVariable("WINE_AMOUNT", this._requestedWineAmount);
					return textObject;
				}
			}

			// Token: 0x17001007 RID: 4103
			// (get) Token: 0x06005767 RID: 22375 RVA: 0x0019E114 File Offset: 0x0019C314
			private TextObject SuccessQuestLogText
			{
				get
				{
					return new TextObject("{=z9pbB0K5}You have successfully delivered the supplies as requested.", null);
				}
			}

			// Token: 0x17001008 RID: 4104
			// (get) Token: 0x06005768 RID: 22376 RVA: 0x0019E121 File Offset: 0x0019C321
			private TextObject FailQuestLogText
			{
				get
				{
					return new TextObject("{=k5HJ3Ld6}You have failed to deliver the supplies in time.", null);
				}
			}

			// Token: 0x17001009 RID: 4105
			// (get) Token: 0x06005769 RID: 22377 RVA: 0x0019E130 File Offset: 0x0019C330
			private TextObject QuestCanceledWarDeclaredLog
			{
				get
				{
					TextObject textObject = new TextObject("{=vW6kBki9}Your clan is now at war with {QUEST_GIVER.LINK}'s realm. Your agreement with {QUEST_GIVER.LINK} is canceled.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x1700100A RID: 4106
			// (get) Token: 0x0600576A RID: 22378 RVA: 0x0019E164 File Offset: 0x0019C364
			private TextObject PlayerDeclaredWarQuestLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=bqeWVVEE}Your actions have started a war with {QUEST_GIVER.LINK}'s faction. {?QUEST_GIVER.GENDER}She{?}He{\\?} cancels your agreement and the quest is a failure.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x0600576B RID: 22379 RVA: 0x0019E196 File Offset: 0x0019C396
			public ArmyNeedsSuppliesIssueQuest(string questId, Hero questGiver, CampaignTime duration, int rewardGold, int grainAmount, int liveStockAmount, int wineAmount)
				: base(questId, questGiver, duration, rewardGold)
			{
				this._requestedGrainAmount = grainAmount;
				this._requestedLiveStockAmount = liveStockAmount;
				this._requestedWineAmount = wineAmount;
				this.SetDialogs();
				base.InitializeQuestOnCreation();
			}

			// Token: 0x0600576C RID: 22380 RVA: 0x0019E1C7 File Offset: 0x0019C3C7
			protected override void InitializeQuestOnGameLoad()
			{
				this.SetDialogs();
			}

			// Token: 0x0600576D RID: 22381 RVA: 0x0019E1CF File Offset: 0x0019C3CF
			protected override void HourlyTick()
			{
			}

			// Token: 0x0600576E RID: 22382 RVA: 0x0019E1D4 File Offset: 0x0019C3D4
			protected override void SetDialogs()
			{
				this.OfferDialogFlow = DialogFlow.CreateDialogFlow("issue_classic_quest_start", 100).NpcLine(new TextObject("{=64RFlBFr}Very well. Don't worry, all your expenses will be covered.[if:convo_approving][ib:hip] ", null), null, null, null, null).Condition(() => Hero.OneToOneConversationHero == base.QuestGiver)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.QuestAcceptedConsequences))
					.CloseDialog();
				this.DiscussDialogFlow = DialogFlow.CreateDialogFlow("quest_discuss", 100).NpcLine(new TextObject("{=bGbSbqTG}Have you brought our supplies?", null), null, null, null, null).Condition(() => Hero.OneToOneConversationHero == base.QuestGiver)
					.Consequence(delegate
					{
						this.CalculateAndUpdateRequestedItemsCountInPlayer(false);
					})
					.BeginPlayerOptions(null, false)
					.PlayerOption(new TextObject("{=FmjZfigu}Yes. I have brought your grain, livestock and wine as you requested.", null), null, null, null)
					.Condition(new ConversationSentence.OnConditionDelegate(this.CheckIfPlayerCollectedEverything))
					.NpcLine(new TextObject("{=UjS8JnH5}Splendid. I will never forget your service, my friend.", null), null, null, null, null)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.CollectedEverythingConsequence))
					.CloseDialog()
					.PlayerOption(new TextObject("{=ISOHhXxW}Yes. I have brought your grain and wine as you requested.", null), null, null, null)
					.Condition(new ConversationSentence.OnConditionDelegate(this.CheckIfPlayerCollectedGrainWine))
					.NpcLine(new TextObject("{=1atg831t}Thank you. Your service will be remembered.", null), null, null, null, null)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.CollectedGrainAndWineConsequence))
					.CloseDialog()
					.PlayerOption(new TextObject("{=YbsVaZkb}Yes. I have brought your grain and livestock as you requested.", null), null, null, null)
					.Condition(new ConversationSentence.OnConditionDelegate(this.CheckIfPlayerCollectedGrainLiveStock))
					.NpcLine(new TextObject("{=1atg831t}Thank you. Your service will be remembered.", null), null, null, null, null)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.CollectedGrainAndLiveStockConsequence))
					.CloseDialog()
					.PlayerOption(new TextObject("{=m9a3ZalO}Yes. I have brought your grain as you requested.", null), null, null, null)
					.Condition(new ConversationSentence.OnConditionDelegate(this.CheckIfPlayerCollectedGrain))
					.NpcLine(new TextObject("{=1atg831t}Thank you. Your service will be remembered.", null), null, null, null, null)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.CollectedGrainConsequence))
					.CloseDialog()
					.PlayerOption(new TextObject("{=PAbVhuKi}Not yet. I'm still working on it.", null), null, null, null)
					.NpcLine(new TextObject("{=AV5xVGM5}Good. We need them as soon as possible.[if:convo_undecided_open][ib:closed2]", null), null, null, null, null)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(MapEventHelper.OnConversationEnd))
					.CloseDialog()
					.EndPlayerOptions()
					.CloseDialog();
			}

			// Token: 0x0600576F RID: 22383 RVA: 0x0019E3FC File Offset: 0x0019C5FC
			private void CollectedGrainConsequence()
			{
				GainRenownAction.Apply(Hero.MainHero, 2f, false);
				GainKingdomInfluenceAction.ApplyForGivingFood(Hero.MainHero, base.QuestGiver, 5f);
				this.RelationshipChangeWithQuestGiver = 2;
				int num = DefaultItems.Grain.Value * this._requestedGrainAmount;
				GiveGoldAction.ApplyBetweenCharacters(null, Hero.MainHero, num, false);
				MobileParty.MainParty.ItemRoster.AddToCounts(DefaultItems.Grain, -this._requestedGrainAmount);
				base.QuestGiver.PartyBelongedTo.ItemRoster.AddToCounts(DefaultItems.Grain, this._requestedGrainAmount);
				base.CompleteQuestWithSuccess();
				MapEventHelper.OnConversationEnd();
			}

			// Token: 0x06005770 RID: 22384 RVA: 0x0019E49C File Offset: 0x0019C69C
			private void CollectedGrainAndLiveStockConsequence()
			{
				GainRenownAction.Apply(Hero.MainHero, 2f, false);
				GainKingdomInfluenceAction.ApplyForGivingFood(Hero.MainHero, base.QuestGiver, 5f);
				this.RelationshipChangeWithQuestGiver = 3;
				int num = DefaultItems.Grain.Value * this._requestedGrainAmount;
				num += MBObjectManager.Instance.GetObject<ItemObject>("sheep").Value * this._requestedLiveStockAmount;
				GiveGoldAction.ApplyBetweenCharacters(null, Hero.MainHero, num, false);
				MobileParty.MainParty.ItemRoster.AddToCounts(DefaultItems.Grain, -this._requestedGrainAmount);
				base.QuestGiver.PartyBelongedTo.ItemRoster.AddToCounts(DefaultItems.Grain, this._requestedGrainAmount);
				this.RemoveLiveStocksFromPlayer();
				base.CompleteQuestWithSuccess();
				MapEventHelper.OnConversationEnd();
			}

			// Token: 0x06005771 RID: 22385 RVA: 0x0019E560 File Offset: 0x0019C760
			private void CollectedGrainAndWineConsequence()
			{
				GainRenownAction.Apply(Hero.MainHero, 2f, false);
				GainKingdomInfluenceAction.ApplyForGivingFood(Hero.MainHero, base.QuestGiver, 5f);
				this.RelationshipChangeWithQuestGiver = 4;
				int num = DefaultItems.Grain.Value * this._requestedGrainAmount;
				num += MBObjectManager.Instance.GetObject<ItemObject>("wine").Value * this._requestedLiveStockAmount;
				GiveGoldAction.ApplyBetweenCharacters(null, Hero.MainHero, num, false);
				MobileParty.MainParty.ItemRoster.AddToCounts(DefaultItems.Grain, -this._requestedGrainAmount);
				base.QuestGiver.PartyBelongedTo.ItemRoster.AddToCounts(DefaultItems.Grain, this._requestedGrainAmount);
				ItemObject @object = MBObjectManager.Instance.GetObject<ItemObject>("wine");
				MobileParty.MainParty.ItemRoster.AddToCounts(@object, -this._requestedWineAmount);
				base.QuestGiver.PartyBelongedTo.ItemRoster.AddToCounts(@object, this._requestedWineAmount);
				base.CompleteQuestWithSuccess();
				MapEventHelper.OnConversationEnd();
			}

			// Token: 0x06005772 RID: 22386 RVA: 0x0019E664 File Offset: 0x0019C864
			private void CollectedEverythingConsequence()
			{
				GainRenownAction.Apply(Hero.MainHero, 2f, false);
				GainKingdomInfluenceAction.ApplyForGivingFood(Hero.MainHero, base.QuestGiver, 8f);
				this.RelationshipChangeWithQuestGiver = 6;
				int num = DefaultItems.Grain.Value * this._requestedGrainAmount;
				num += MBObjectManager.Instance.GetObject<ItemObject>("wine").Value * this._requestedLiveStockAmount;
				num += MBObjectManager.Instance.GetObject<ItemObject>("sheep").Value * this._requestedLiveStockAmount;
				GiveGoldAction.ApplyBetweenCharacters(null, Hero.MainHero, num, false);
				MobileParty.MainParty.ItemRoster.AddToCounts(DefaultItems.Grain, -this._requestedGrainAmount);
				base.QuestGiver.PartyBelongedTo.ItemRoster.AddToCounts(DefaultItems.Grain, this._requestedGrainAmount);
				ItemObject @object = MBObjectManager.Instance.GetObject<ItemObject>("wine");
				MobileParty.MainParty.ItemRoster.AddToCounts(@object, -this._requestedWineAmount);
				base.QuestGiver.PartyBelongedTo.ItemRoster.AddToCounts(@object, this._requestedWineAmount);
				this.RemoveLiveStocksFromPlayer();
				base.CompleteQuestWithSuccess();
				MapEventHelper.OnConversationEnd();
			}

			// Token: 0x06005773 RID: 22387 RVA: 0x0019E78C File Offset: 0x0019C98C
			private void RemoveLiveStocksFromPlayer()
			{
				int i = this._requestedLiveStockAmount;
				while (i > 0)
				{
					for (int j = 0; j < MobileParty.MainParty.ItemRoster.Count; j++)
					{
						ItemRosterElement itemRosterElement = MobileParty.MainParty.ItemRoster[j];
						if (!itemRosterElement.IsEmpty)
						{
							ItemObject item = itemRosterElement.EquipmentElement.Item;
							if (item.HasHorseComponent && item.HorseComponent.IsLiveStock)
							{
								if (i < itemRosterElement.Amount)
								{
									MobileParty.MainParty.ItemRoster.AddToCounts(item, -i);
									i = 0;
									break;
								}
								MobileParty.MainParty.ItemRoster.AddToCounts(item, -itemRosterElement.Amount);
								i -= itemRosterElement.Amount;
							}
						}
					}
				}
				base.QuestGiver.PartyBelongedTo.ItemRoster.AddToCounts(MBObjectManager.Instance.GetObject<ItemObject>("meat"), this._requestedLiveStockAmount * 2);
			}

			// Token: 0x06005774 RID: 22388 RVA: 0x0019E87F File Offset: 0x0019CA7F
			private bool CheckIfPlayerCollectedGrain()
			{
				return this._currentGrainAmount >= this._requestedGrainAmount;
			}

			// Token: 0x06005775 RID: 22389 RVA: 0x0019E892 File Offset: 0x0019CA92
			private bool CheckIfPlayerCollectedGrainLiveStock()
			{
				return this._currentGrainAmount >= this._requestedGrainAmount && this._currentLiveStockAmount >= this._requestedLiveStockAmount;
			}

			// Token: 0x06005776 RID: 22390 RVA: 0x0019E8B5 File Offset: 0x0019CAB5
			private bool CheckIfPlayerCollectedGrainWine()
			{
				return this._currentGrainAmount >= this._requestedGrainAmount && this._currentWineAmount >= this._requestedWineAmount;
			}

			// Token: 0x06005777 RID: 22391 RVA: 0x0019E8D8 File Offset: 0x0019CAD8
			private bool CheckIfPlayerCollectedEverything()
			{
				return this._currentGrainAmount >= this._requestedGrainAmount && this._currentWineAmount >= this._requestedWineAmount && this._currentLiveStockAmount >= this._requestedLiveStockAmount;
			}

			// Token: 0x06005778 RID: 22392 RVA: 0x0019E90C File Offset: 0x0019CB0C
			private void QuestAcceptedConsequences()
			{
				base.StartQuest();
				base.AddLog(this.PlayerStartsQuestLogText, false);
				this.CalculateAndUpdateRequestedItemsCountInPlayer(true);
				this._grainLog = base.AddDiscreteLog(TextObject.GetEmpty(), new TextObject("{=yGxjOnYb}Collected Grain Amount", null), this._currentGrainAmount, this._requestedGrainAmount, null, false);
				this._liveStockLog = base.AddDiscreteLog(TextObject.GetEmpty(), new TextObject("{=aIxX2s8n}Collected Livestock Amount (Optional)", null), this._currentLiveStockAmount, this._requestedLiveStockAmount, null, false);
				this._wineLog = base.AddDiscreteLog(TextObject.GetEmpty(), new TextObject("{=ENS8Ig1o}Collected Wine Amount (Optional)", null), this._currentWineAmount, this._requestedWineAmount, null, false);
			}

			// Token: 0x06005779 RID: 22393 RVA: 0x0019E9B4 File Offset: 0x0019CBB4
			protected override void RegisterEvents()
			{
				CampaignEvents.WarDeclared.AddNonSerializedListener(this, new Action<IFaction, IFaction, DeclareWarAction.DeclareWarDetail>(this.OnWarDeclared));
				CampaignEvents.PlayerInventoryExchangeEvent.AddNonSerializedListener(this, new Action<List<ValueTuple<ItemRosterElement, int>>, List<ValueTuple<ItemRosterElement, int>>, bool>(this.OnInventoryExchange));
				CampaignEvents.ArmyDispersed.AddNonSerializedListener(this, new Action<Army, Army.ArmyDispersionReason, bool>(this.OnArmyDispersed));
				CampaignEvents.OnClanChangedKingdomEvent.AddNonSerializedListener(this, new Action<Clan, Kingdom, Kingdom, ChangeKingdomAction.ChangeKingdomActionDetail, bool>(this.OnClanChangedKingdom));
			}

			// Token: 0x0600577A RID: 22394 RVA: 0x0019EA20 File Offset: 0x0019CC20
			private void OnClanChangedKingdom(Clan clan, Kingdom oldKingdom, Kingdom newKingdom, ChangeKingdomAction.ChangeKingdomActionDetail detail, bool showNotification = true)
			{
				if (clan == Clan.PlayerClan && oldKingdom == base.QuestGiver.MapFaction)
				{
					TextObject textObject = new TextObject("{=aQVdW6aC}You have left {QUEST_GIVER_FACTION}. Your agreement with {QUEST_GIVER.LINK} is terminated.", null);
					textObject.SetTextVariable("QUEST_GIVER_FACTION", base.QuestGiver.MapFaction.EncyclopediaLinkWithName);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					base.CompleteQuestWithCancel(textObject);
					return;
				}
				if (base.QuestGiver.MapFaction.IsAtWarWith(Hero.MainHero.MapFaction))
				{
					base.CompleteQuestWithCancel(this.QuestCanceledWarDeclaredLog);
				}
			}

			// Token: 0x0600577B RID: 22395 RVA: 0x0019EAB3 File Offset: 0x0019CCB3
			private void OnArmyDispersed(Army army, Army.ArmyDispersionReason reason, bool isPlayersArmy)
			{
				if (army.ArmyOwner == base.QuestGiver)
				{
					base.AddLog(new TextObject("{=K2gsZOMb}Army is disbanded and your mission was canceled.", null), false);
					base.CompleteQuestWithCancel(null);
				}
			}

			// Token: 0x0600577C RID: 22396 RVA: 0x0019EADD File Offset: 0x0019CCDD
			private void OnInventoryExchange(List<ValueTuple<ItemRosterElement, int>> purchasedItems, List<ValueTuple<ItemRosterElement, int>> soldItems, bool isTrading)
			{
				this.CalculateAndUpdateRequestedItemsCountInPlayer(true);
			}

			// Token: 0x0600577D RID: 22397 RVA: 0x0019EAE8 File Offset: 0x0019CCE8
			private void CalculateAndUpdateRequestedItemsCountInPlayer(bool notifyPlayer = true)
			{
				ItemObject grain = DefaultItems.Grain;
				ItemObject @object = MBObjectManager.Instance.GetObject<ItemObject>("wine");
				this._currentGrainAmount = MobileParty.MainParty.ItemRoster.GetItemNumber(grain);
				this._currentLiveStockAmount = MobileParty.MainParty.ItemRoster.NumberOfLivestockAnimals;
				this._currentWineAmount = MobileParty.MainParty.ItemRoster.GetItemNumber(@object);
				if (notifyPlayer)
				{
					if (this._currentGrainAmount >= this._requestedGrainAmount && this._currentLiveStockAmount >= this._requestedLiveStockAmount && this._currentWineAmount >= this._requestedWineAmount)
					{
						MBInformationManager.AddQuickInformation(new TextObject("{=uEV6kKdU}You have collected all the supplies that the army commander requested. Return to army and deliver the supplies", null), 0, null, null, "");
					}
					else if (this._currentGrainAmount >= this._requestedGrainAmount)
					{
						MBInformationManager.AddQuickInformation(new TextObject("{=8XpTvx1i}You have collected enough grains that the army commander requested. Return to army and deliver the supplies", null), 0, null, null, "");
					}
				}
				this._currentGrainAmount = (int)MathF.Clamp((float)this._currentGrainAmount, 0f, (float)this._requestedGrainAmount);
				this._currentLiveStockAmount = (int)MathF.Clamp((float)this._currentLiveStockAmount, 0f, (float)this._requestedLiveStockAmount);
				this._currentWineAmount = (int)MathF.Clamp((float)this._currentWineAmount, 0f, (float)this._requestedWineAmount);
				JournalLog grainLog = this._grainLog;
				if (grainLog != null)
				{
					grainLog.UpdateCurrentProgress(this._currentGrainAmount);
				}
				JournalLog liveStockLog = this._liveStockLog;
				if (liveStockLog != null)
				{
					liveStockLog.UpdateCurrentProgress(this._currentLiveStockAmount);
				}
				JournalLog wineLog = this._wineLog;
				if (wineLog == null)
				{
					return;
				}
				wineLog.UpdateCurrentProgress(this._currentWineAmount);
			}

			// Token: 0x0600577E RID: 22398 RVA: 0x0019EC5A File Offset: 0x0019CE5A
			private void OnWarDeclared(IFaction faction1, IFaction faction2, DeclareWarAction.DeclareWarDetail detail)
			{
				QuestHelper.CheckWarDeclarationAndFailOrCancelTheQuest(this, faction1, faction2, detail, this.PlayerDeclaredWarQuestLogText, this.QuestCanceledWarDeclaredLog, false);
			}

			// Token: 0x0600577F RID: 22399 RVA: 0x0019EC72 File Offset: 0x0019CE72
			public override void OnFailed()
			{
				this.RelationshipChangeWithQuestGiver = -2;
			}

			// Token: 0x06005780 RID: 22400 RVA: 0x0019EC7C File Offset: 0x0019CE7C
			protected override void OnCompleteWithSuccess()
			{
				base.AddLog(this.SuccessQuestLogText, false);
			}

			// Token: 0x06005781 RID: 22401 RVA: 0x0019EC8C File Offset: 0x0019CE8C
			protected override void OnTimedOut()
			{
				this.OnFailed();
				base.AddLog(this.FailQuestLogText, false);
			}

			// Token: 0x06005782 RID: 22402 RVA: 0x0019ECA2 File Offset: 0x0019CEA2
			public override void OnCanceled()
			{
			}

			// Token: 0x04001D13 RID: 7443
			[SaveableField(10)]
			private int _requestedGrainAmount;

			// Token: 0x04001D14 RID: 7444
			[SaveableField(20)]
			private int _requestedLiveStockAmount;

			// Token: 0x04001D15 RID: 7445
			[SaveableField(30)]
			private int _requestedWineAmount;

			// Token: 0x04001D16 RID: 7446
			[SaveableField(40)]
			private int _currentGrainAmount;

			// Token: 0x04001D17 RID: 7447
			[SaveableField(50)]
			private int _currentLiveStockAmount;

			// Token: 0x04001D18 RID: 7448
			[SaveableField(60)]
			private int _currentWineAmount;

			// Token: 0x04001D19 RID: 7449
			[SaveableField(70)]
			private JournalLog _grainLog;

			// Token: 0x04001D1A RID: 7450
			[SaveableField(80)]
			private JournalLog _liveStockLog;

			// Token: 0x04001D1B RID: 7451
			[SaveableField(90)]
			private JournalLog _wineLog;
		}

		// Token: 0x02000718 RID: 1816
		public class ArmyNeedsSuppliesIssueTypeDefiner : SaveableTypeDefiner
		{
			// Token: 0x06005786 RID: 22406 RVA: 0x0019ECCB File Offset: 0x0019CECB
			public ArmyNeedsSuppliesIssueTypeDefiner()
				: base(585800)
			{
			}

			// Token: 0x06005787 RID: 22407 RVA: 0x0019ECD8 File Offset: 0x0019CED8
			protected override void DefineClassTypes()
			{
				base.AddClassDefinition(typeof(ArmyNeedsSuppliesIssueBehavior.ArmyNeedsSuppliesIssue), 1, null);
				base.AddClassDefinition(typeof(ArmyNeedsSuppliesIssueBehavior.ArmyNeedsSuppliesIssueQuest), 2, null);
			}
		}
	}
}
