using System;
using System.Collections.Generic;
using System.Linq;
using Helpers;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.CharacterDevelopment;
using TaleWorlds.CampaignSystem.Conversation;
using TaleWorlds.CampaignSystem.Extensions;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Roster;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.ObjectSystem;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.Issues
{
	// Token: 0x02000374 RID: 884
	public class ArtisanOverpricedGoodsIssueBehavior : CampaignBehaviorBase
	{
		// Token: 0x17000C89 RID: 3209
		// (get) Token: 0x060034FD RID: 13565 RVA: 0x000D8DD5 File Offset: 0x000D6FD5
		private static IEnumerable<ItemObject> PossibleRequestedItems
		{
			get
			{
				yield return MBObjectManager.Instance.GetObject<ItemObject>("cow");
				yield return MBObjectManager.Instance.GetObject<ItemObject>("sheep");
				yield return MBObjectManager.Instance.GetObject<ItemObject>("wool");
				yield return MBObjectManager.Instance.GetObject<ItemObject>("iron");
				yield return MBObjectManager.Instance.GetObject<ItemObject>("leather");
				yield return MBObjectManager.Instance.GetObject<ItemObject>("hardwood");
				yield break;
			}
		}

		// Token: 0x060034FE RID: 13566 RVA: 0x000D8DDE File Offset: 0x000D6FDE
		public override void RegisterEvents()
		{
			CampaignEvents.OnCheckForIssueEvent.AddNonSerializedListener(this, new Action<Hero>(this.OnCheckForIssue));
		}

		// Token: 0x060034FF RID: 13567 RVA: 0x000D8DF7 File Offset: 0x000D6FF7
		public override void SyncData(IDataStore dataStore)
		{
		}

		// Token: 0x06003500 RID: 13568 RVA: 0x000D8DFC File Offset: 0x000D6FFC
		public void OnCheckForIssue(Hero hero)
		{
			Hero hero2;
			ItemObject itemObject;
			if (this.ConditionsHold(hero, out hero2, out itemObject))
			{
				KeyValuePair<Hero, ItemObject> keyValuePair = new KeyValuePair<Hero, ItemObject>(hero2, itemObject);
				Campaign.Current.IssueManager.AddPotentialIssueData(hero, new PotentialIssueData(new PotentialIssueData.StartIssueDelegate(this.OnStartIssue), typeof(ArtisanOverpricedGoodsIssueBehavior.ArtisanOverpricedGoodsIssue), IssueBase.IssueFrequency.Common, keyValuePair));
				return;
			}
			Campaign.Current.IssueManager.AddPotentialIssueData(hero, new PotentialIssueData(typeof(ArtisanOverpricedGoodsIssueBehavior.ArtisanOverpricedGoodsIssue), IssueBase.IssueFrequency.Common));
		}

		// Token: 0x06003501 RID: 13569 RVA: 0x000D8E74 File Offset: 0x000D7074
		private Hero GetAntagonistMerchant(Hero issueOwner)
		{
			return issueOwner.CurrentSettlement.Notables.GetRandomElementWithPredicate<Hero>((Hero x) => x != issueOwner && x.IsMerchant && x.GetTraitLevel(DefaultTraits.Mercy) <= 0 && x.CanHaveCampaignIssues());
		}

		// Token: 0x06003502 RID: 13570 RVA: 0x000D8EB0 File Offset: 0x000D70B0
		private bool ConditionsHold(Hero IssueOwner, out Hero antagonistMerchant, out ItemObject requestedItem)
		{
			antagonistMerchant = null;
			requestedItem = null;
			if (IssueOwner.CurrentSettlement != null && IssueOwner.CurrentSettlement.IsTown && IssueOwner.IsArtisan)
			{
				antagonistMerchant = this.GetAntagonistMerchant(IssueOwner);
				if (antagonistMerchant != null)
				{
					foreach (ItemObject itemObject in ArtisanOverpricedGoodsIssueBehavior.PossibleRequestedItems)
					{
						if (IssueOwner.CurrentSettlement.Town.GetItemCategoryPriceIndex(itemObject.ItemCategory) > 2f)
						{
							requestedItem = itemObject;
							return true;
						}
					}
					return false;
				}
				return false;
			}
			return false;
		}

		// Token: 0x06003503 RID: 13571 RVA: 0x000D8F50 File Offset: 0x000D7150
		private IssueBase OnStartIssue(in PotentialIssueData pid, Hero issueOwner)
		{
			PotentialIssueData potentialIssueData = pid;
			KeyValuePair<Hero, ItemObject> keyValuePair = (KeyValuePair<Hero, ItemObject>)potentialIssueData.RelatedObject;
			return new ArtisanOverpricedGoodsIssueBehavior.ArtisanOverpricedGoodsIssue(issueOwner, keyValuePair.Key, keyValuePair.Value);
		}

		// Token: 0x04000EEE RID: 3822
		private const IssueBase.IssueFrequency ArtisanOverpricedGoodsIssueFrequency = IssueBase.IssueFrequency.Common;

		// Token: 0x04000EEF RID: 3823
		private const float HighestPriceIndexAtTown = 2f;

		// Token: 0x0200071F RID: 1823
		public class ArtisanOverpricedGoodsIssue : IssueBase
		{
			// Token: 0x06005801 RID: 22529 RVA: 0x001A0A97 File Offset: 0x0019EC97
			internal static void AutoGeneratedStaticCollectObjectsArtisanOverpricedGoodsIssue(object o, List<object> collectedObjects)
			{
				((ArtisanOverpricedGoodsIssueBehavior.ArtisanOverpricedGoodsIssue)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x06005802 RID: 22530 RVA: 0x001A0AA5 File Offset: 0x0019ECA5
			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
				collectedObjects.Add(this._requestedTradeGood);
				collectedObjects.Add(this.CounterOfferHero);
			}

			// Token: 0x06005803 RID: 22531 RVA: 0x001A0AC6 File Offset: 0x0019ECC6
			internal static object AutoGeneratedGetMemberValueRequestedTradeGoodAmount(object o)
			{
				return ((ArtisanOverpricedGoodsIssueBehavior.ArtisanOverpricedGoodsIssue)o).RequestedTradeGoodAmount;
			}

			// Token: 0x06005804 RID: 22532 RVA: 0x001A0AD8 File Offset: 0x0019ECD8
			internal static object AutoGeneratedGetMemberValueCounterOfferHero(object o)
			{
				return ((ArtisanOverpricedGoodsIssueBehavior.ArtisanOverpricedGoodsIssue)o).CounterOfferHero;
			}

			// Token: 0x06005805 RID: 22533 RVA: 0x001A0AE5 File Offset: 0x0019ECE5
			internal static object AutoGeneratedGetMemberValue_goldReward(object o)
			{
				return ((ArtisanOverpricedGoodsIssueBehavior.ArtisanOverpricedGoodsIssue)o)._goldReward;
			}

			// Token: 0x06005806 RID: 22534 RVA: 0x001A0AF7 File Offset: 0x0019ECF7
			internal static object AutoGeneratedGetMemberValue_requestedTradeGood(object o)
			{
				return ((ArtisanOverpricedGoodsIssueBehavior.ArtisanOverpricedGoodsIssue)o)._requestedTradeGood;
			}

			// Token: 0x17001034 RID: 4148
			// (get) Token: 0x06005807 RID: 22535 RVA: 0x001A0B04 File Offset: 0x0019ED04
			public override int AlternativeSolutionBaseNeededMenCount
			{
				get
				{
					return 4 + MathF.Ceiling(6f * base.IssueDifficultyMultiplier);
				}
			}

			// Token: 0x17001035 RID: 4149
			// (get) Token: 0x06005808 RID: 22536 RVA: 0x001A0B19 File Offset: 0x0019ED19
			protected override int AlternativeSolutionBaseDurationInDaysInternal
			{
				get
				{
					return 3 + MathF.Ceiling(5f * base.IssueDifficultyMultiplier);
				}
			}

			// Token: 0x17001036 RID: 4150
			// (get) Token: 0x06005809 RID: 22537 RVA: 0x001A0B2E File Offset: 0x0019ED2E
			public override IssueBase.AlternativeSolutionScaleFlag AlternativeSolutionScaleFlags
			{
				get
				{
					return IssueBase.AlternativeSolutionScaleFlag.Duration;
				}
			}

			// Token: 0x17001037 RID: 4151
			// (get) Token: 0x0600580A RID: 22538 RVA: 0x001A0B31 File Offset: 0x0019ED31
			protected override int RewardGold
			{
				get
				{
					return this._goldReward;
				}
			}

			// Token: 0x17001038 RID: 4152
			// (get) Token: 0x0600580B RID: 22539 RVA: 0x001A0B39 File Offset: 0x0019ED39
			// (set) Token: 0x0600580C RID: 22540 RVA: 0x001A0B41 File Offset: 0x0019ED41
			[SaveableProperty(12)]
			private int RequestedTradeGoodAmount { get; set; }

			// Token: 0x17001039 RID: 4153
			// (get) Token: 0x0600580D RID: 22541 RVA: 0x001A0B4A File Offset: 0x0019ED4A
			private int RequiredGoldForAlternativeSolution
			{
				get
				{
					return MathF.Floor((float)(this._requestedTradeGood.Value * this.RequestedTradeGoodAmount) * 0.75f);
				}
			}

			// Token: 0x1700103A RID: 4154
			// (get) Token: 0x0600580E RID: 22542 RVA: 0x001A0B6A File Offset: 0x0019ED6A
			// (set) Token: 0x0600580F RID: 22543 RVA: 0x001A0B72 File Offset: 0x0019ED72
			[SaveableProperty(11)]
			public override Hero CounterOfferHero { get; protected set; }

			// Token: 0x1700103B RID: 4155
			// (get) Token: 0x06005810 RID: 22544 RVA: 0x001A0B7B File Offset: 0x0019ED7B
			public override int NeededInfluenceForLordSolution
			{
				get
				{
					return 15 + MathF.Ceiling(35f * base.IssueDifficultyMultiplier);
				}
			}

			// Token: 0x1700103C RID: 4156
			// (get) Token: 0x06005811 RID: 22545 RVA: 0x001A0B91 File Offset: 0x0019ED91
			public override TextObject IssueBriefByIssueGiver
			{
				get
				{
					return new TextObject("{=FKtkmwtb}I don't know if you know much about the law here... Craftsmen like me are required to buy our raw materials from local merchants. The other side of the bargain is that they offer us reasonable prices. But they're not doing that! They've come together and agreed on a price that's just too high. They don't care if it ruins us - they can always sell the goods elsewhere.[ib:hip][if:convo_thinking]", null);
				}
			}

			// Token: 0x1700103D RID: 4157
			// (get) Token: 0x06005812 RID: 22546 RVA: 0x001A0B9E File Offset: 0x0019ED9E
			public override TextObject IssueAcceptByPlayer
			{
				get
				{
					return new TextObject("{=j4V4fVBd}I see... How can I help?", null);
				}
			}

			// Token: 0x1700103E RID: 4158
			// (get) Token: 0x06005813 RID: 22547 RVA: 0x001A0BAB File Offset: 0x0019EDAB
			protected override TextObject LordSolutionStartLog
			{
				get
				{
					return new TextObject("{=p5OHK0Lh}You decided to issue a decree banning the merchants' price-fixing arrangement.", null);
				}
			}

			// Token: 0x1700103F RID: 4159
			// (get) Token: 0x06005814 RID: 22548 RVA: 0x001A0BB8 File Offset: 0x0019EDB8
			protected override TextObject LordSolutionCounterOfferRefuseLog
			{
				get
				{
					return new TextObject("{=wrliXWLc}You approved the law which prevents price fixing in the markets and rejected the merchants' counter-offer.", null);
				}
			}

			// Token: 0x17001040 RID: 4160
			// (get) Token: 0x06005815 RID: 22549 RVA: 0x001A0BC5 File Offset: 0x0019EDC5
			protected override TextObject LordSolutionCounterOfferAcceptLog
			{
				get
				{
					return new TextObject("{=bSguu34C}After listening to the town merchants, you decided to let the merchants continue price-fixing.", null);
				}
			}

			// Token: 0x17001041 RID: 4161
			// (get) Token: 0x06005816 RID: 22550 RVA: 0x001A0BD4 File Offset: 0x0019EDD4
			public override TextObject IssueQuestSolutionExplanationByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=epcc2knY}Well, you get around, right? It wouldn't be hard for you to collect the {.%}{SELECTED_GOOD}{.%} we need. If you could bring, say {SELECTED_AMOUNT} {.%}{?SELECTED_AMOUNT > 1}{PLURAL(SELECTED_GOOD)}{?}{SELECTED_GOOD}{\\?}{.%} directly to me instead of selling to the merchants, I would gladly pay {REWARD_AMOUNT}{GOLD_ICON} for them. With this, the merchants would have to lower their prices.[if:convo_calm_friendly][ib:confident3]", null);
					textObject.SetTextVariable("SELECTED_GOOD", this._requestedTradeGood.Name);
					textObject.SetTextVariable("SELECTED_AMOUNT", this.RequestedTradeGoodAmount);
					textObject.SetTextVariable("REWARD_AMOUNT", this.RewardGold);
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"6\">");
					return textObject;
				}
			}

			// Token: 0x17001042 RID: 4162
			// (get) Token: 0x06005817 RID: 22551 RVA: 0x001A0C38 File Offset: 0x0019EE38
			public override TextObject IssueAlternativeSolutionExplanationByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=XvC1eLR1}Or, if you will not be able to acquire the goods yourself, you can perhaps assign one of your trusted companions to the task. Somewhat with a good understanding of trade and and around {TROOP_NUMBER} {?TROOP_NUMBER}troops{?}troop{\\?} could do it easily enough, along with {GOLD_COST}{GOLD_ICON} denars to make the purchases.[ib:normal2][if:convo_undecided_open]", null);
					textObject.SetTextVariable("TROOP_NUMBER", base.GetTotalAlternativeSolutionNeededMenCount());
					textObject.SetTextVariable("GOLD_COST", this.RequiredGoldForAlternativeSolution);
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"6\">");
					return textObject;
				}
			}

			// Token: 0x17001043 RID: 4163
			// (get) Token: 0x06005818 RID: 22552 RVA: 0x001A0C88 File Offset: 0x0019EE88
			public override TextObject IssueLordSolutionExplanationByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=JeL0aUOa}You could stop them with a decree, my {?PLAYER.GENDER}lady{?}lord{\\?}. All the craftsmen here would be very grateful.", null);
					StringHelpers.SetCharacterProperties("PLAYER", CharacterObject.PlayerCharacter, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17001044 RID: 4164
			// (get) Token: 0x06005819 RID: 22553 RVA: 0x001A0CB4 File Offset: 0x0019EEB4
			public override TextObject IssueQuestSolutionAcceptByPlayer
			{
				get
				{
					TextObject textObject = new TextObject("{=mTuIMcLA}All right. I will bring {SELECTED_AMOUNT} {.%}{?SELECTED_AMOUNT > 1}{PLURAL(SELECTED_GOOD)}{?}{SELECTED_GOOD}{\\?}{.%} to you.", null);
					textObject.SetTextVariable("SELECTED_GOOD", this._requestedTradeGood.Name);
					textObject.SetTextVariable("SELECTED_AMOUNT", this.RequestedTradeGoodAmount);
					return textObject;
				}
			}

			// Token: 0x17001045 RID: 4165
			// (get) Token: 0x0600581A RID: 22554 RVA: 0x001A0CEA File Offset: 0x0019EEEA
			public override TextObject IssueAlternativeSolutionAcceptByPlayer
			{
				get
				{
					return new TextObject("{=79h7xNeL}I will have one of my companions take care of this.", null);
				}
			}

			// Token: 0x17001046 RID: 4166
			// (get) Token: 0x0600581B RID: 22555 RVA: 0x001A0CF7 File Offset: 0x0019EEF7
			public override TextObject IssueDiscussAlternativeSolution
			{
				get
				{
					return new TextObject("{=E9GhODyh}I am very grateful to you for sparing your men to help us get what we need for a fair price.[if:convo_approving][ib:normal2]", null);
				}
			}

			// Token: 0x17001047 RID: 4167
			// (get) Token: 0x0600581C RID: 22556 RVA: 0x001A0D04 File Offset: 0x0019EF04
			public override TextObject IssueAlternativeSolutionResponseByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=2YiPE05P}Thank you, my {?PLAYER.GENDER}lady{?}lord{\\?}. Your companion will no doubt be very helpful.", null);
					StringHelpers.SetCharacterProperties("PLAYER", CharacterObject.PlayerCharacter, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17001048 RID: 4168
			// (get) Token: 0x0600581D RID: 22557 RVA: 0x001A0D30 File Offset: 0x0019EF30
			public override TextObject IssueLordSolutionAcceptByPlayer
			{
				get
				{
					return new TextObject("{=xTKHO53L}This is outrageous. I declare that from now on that there shall be no price fixing.", null);
				}
			}

			// Token: 0x17001049 RID: 4169
			// (get) Token: 0x0600581E RID: 22558 RVA: 0x001A0D40 File Offset: 0x0019EF40
			public override TextObject IssueLordSolutionResponseByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=6vPCEaSR}Thank you, my {?PLAYER.GENDER}lady{?}lord{\\?} that would be very good. Merchants will not like this but the hard-working artisans like me will be grateful to you for this.", null);
					StringHelpers.SetCharacterProperties("PLAYER", CharacterObject.PlayerCharacter, textObject, false);
					return textObject;
				}
			}

			// Token: 0x1700104A RID: 4170
			// (get) Token: 0x0600581F RID: 22559 RVA: 0x001A0D6C File Offset: 0x0019EF6C
			public override TextObject IssueLordSolutionCounterOfferBriefByOtherNpc
			{
				get
				{
					return new TextObject("{=KSeIOHDh}(One of the merchants in the town comes to talk as you are preparing to depart.)", null);
				}
			}

			// Token: 0x1700104B RID: 4171
			// (get) Token: 0x06005820 RID: 22560 RVA: 0x001A0D79 File Offset: 0x0019EF79
			public override TextObject IssueLordSolutionCounterOfferExplanationByOtherNpc
			{
				get
				{
					return new TextObject("{=8Tqv9ezH}We heard you wish to issue a decree changing our longstanding rules on pricing. Of course this is your right, but I'd like to remind you that we merchants pay significantly more taxes than the artisans. I would ask you to think of the finances of the town, and reconsider this.", null);
				}
			}

			// Token: 0x1700104C RID: 4172
			// (get) Token: 0x06005821 RID: 22561 RVA: 0x001A0D86 File Offset: 0x0019EF86
			public override TextObject IssueLordSolutionCounterOfferAcceptByPlayer
			{
				get
				{
					return new TextObject("{=FyTGbvLS}On second thought, I have decided not to interfere with the merchant's business.", null);
				}
			}

			// Token: 0x1700104D RID: 4173
			// (get) Token: 0x06005822 RID: 22562 RVA: 0x001A0D94 File Offset: 0x0019EF94
			public override TextObject IssueLordSolutionCounterOfferAcceptResponseByOtherNpc
			{
				get
				{
					TextObject textObject = new TextObject("{=wynCFpsT}This is a wise decision, my {?PLAYER.GENDER}lady{?}lord{\\?}. Thank you.", null);
					StringHelpers.SetCharacterProperties("PLAYER", CharacterObject.PlayerCharacter, textObject, false);
					return textObject;
				}
			}

			// Token: 0x1700104E RID: 4174
			// (get) Token: 0x06005823 RID: 22563 RVA: 0x001A0DC0 File Offset: 0x0019EFC0
			public override TextObject IssueLordSolutionCounterOfferDeclineByPlayer
			{
				get
				{
					return new TextObject("{=IXuaflOe}I stand by my decision.", null);
				}
			}

			// Token: 0x1700104F RID: 4175
			// (get) Token: 0x06005824 RID: 22564 RVA: 0x001A0DCD File Offset: 0x0019EFCD
			public override TextObject IssueLordSolutionCounterOfferDeclineResponseByOtherNpc
			{
				get
				{
					return new TextObject("{=A8dyXgLz}That's a pity.", null);
				}
			}

			// Token: 0x06005825 RID: 22565 RVA: 0x001A0DDA File Offset: 0x0019EFDA
			protected override void LordSolutionConsequenceWithRefuseCounterOffer()
			{
				this.ApplySuccessRewards(base.IssueOwner);
			}

			// Token: 0x06005826 RID: 22566 RVA: 0x001A0DE8 File Offset: 0x0019EFE8
			protected override void LordSolutionConsequenceWithAcceptCounterOffer()
			{
				ChangeRelationAction.ApplyPlayerRelation(this.CounterOfferHero, 5, true, true);
				this.RelationshipChangeWithIssueOwner = -5;
				base.IssueSettlement.Town.Prosperity -= 30f;
				TraitLevelingHelper.OnIssueSolvedThroughBetrayal(base.IssueOwner, new Tuple<TraitObject, int>[]
				{
					new Tuple<TraitObject, int>(DefaultTraits.Honor, -50)
				});
				base.IssueOwner.AddPower(-5f);
			}

			// Token: 0x17001050 RID: 4176
			// (get) Token: 0x06005827 RID: 22567 RVA: 0x001A0E58 File Offset: 0x0019F058
			protected override TextObject AlternativeSolutionStartLog
			{
				get
				{
					TextObject textObject = new TextObject("{=aeKdXKnO}{ISSUE_GIVER.LINK}, an artisan from {SETTLEMENT}, has told you that a local merchant {COUNTER_OFFER.LINK} is asking ridiculous amounts of money for raw materials which {?ISSUE_GIVER.GENDER}she{?}he{\\?} needs to continue {?ISSUE_GIVER.GENDER}her{?}his{\\?} work. {?ISSUE_GIVER.GENDER}She{?}He{\\?} is willing to pay {REWARD_AMOUNT}{GOLD_ICON} for help obtaining the needed goods.{newline}You asked {COMPANION.LINK} to stay with {?ISSUE_GIVER.GENDER}her{?}him{\\?} and try to solve {?ISSUE_GIVER.GENDER}her{?}his{\\?} problems. You expect {COMPANION.LINK} to report back to you in {RETURN_DAYS} days.", null);
					StringHelpers.SetCharacterProperties("ISSUE_GIVER", base.IssueOwner.CharacterObject, textObject, false);
					StringHelpers.SetCharacterProperties("COUNTER_OFFER", this.CounterOfferHero.CharacterObject, textObject, false);
					textObject.SetCharacterProperties("COMPANION", base.AlternativeSolutionHero.CharacterObject, false);
					textObject.SetTextVariable("SETTLEMENT", base.IssueOwner.CurrentSettlement.EncyclopediaLinkWithName);
					textObject.SetTextVariable("REWARD_AMOUNT", this.RewardGold);
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"6\">");
					textObject.SetTextVariable("RETURN_DAYS", base.GetTotalAlternativeSolutionDurationInDays());
					return textObject;
				}
			}

			// Token: 0x17001051 RID: 4177
			// (get) Token: 0x06005828 RID: 22568 RVA: 0x001A0F0A File Offset: 0x0019F10A
			public override bool IsThereAlternativeSolution
			{
				get
				{
					return true;
				}
			}

			// Token: 0x17001052 RID: 4178
			// (get) Token: 0x06005829 RID: 22569 RVA: 0x001A0F0D File Offset: 0x0019F10D
			public override bool IsThereLordSolution
			{
				get
				{
					return true;
				}
			}

			// Token: 0x17001053 RID: 4179
			// (get) Token: 0x0600582A RID: 22570 RVA: 0x001A0F10 File Offset: 0x0019F110
			public override TextObject Title
			{
				get
				{
					TextObject textObject = new TextObject("{=dt6kKXSL}Overpriced Raw Materials at {SETTLEMENT}", null);
					textObject.SetTextVariable("SETTLEMENT", base.IssueSettlement.Name);
					return textObject;
				}
			}

			// Token: 0x17001054 RID: 4180
			// (get) Token: 0x0600582B RID: 22571 RVA: 0x001A0F34 File Offset: 0x0019F134
			public override TextObject Description
			{
				get
				{
					TextObject textObject = new TextObject("{=U90asNb9}Artisans in {SETTLEMENT} cannot continue their work because of the overpriced raw materials.", null);
					textObject.SetTextVariable("SETTLEMENT", base.IssueOwner.CurrentSettlement.Name);
					return textObject;
				}
			}

			// Token: 0x17001055 RID: 4181
			// (get) Token: 0x0600582C RID: 22572 RVA: 0x001A0F60 File Offset: 0x0019F160
			public override TextObject IssueAsRumorInSettlement
			{
				get
				{
					TextObject textObject = new TextObject("{=FPbmUpy7}{QUEST_GIVER.NAME} is in quite a stew over the merchants' monopoly, so I hear.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.IssueOwner.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17001056 RID: 4182
			// (get) Token: 0x0600582D RID: 22573 RVA: 0x001A0F92 File Offset: 0x0019F192
			public override TextObject IssueAlternativeSolutionSuccessLog
			{
				get
				{
					TextObject textObject = new TextObject("{=3r2HLPQ1}Your {COMPANION.LINK} has delivered {ISSUE_GIVER.LINK}'s goods as you promised.", null);
					textObject.SetCharacterProperties("COMPANION", base.AlternativeSolutionHero.CharacterObject, false);
					textObject.SetCharacterProperties("ISSUE_GIVER", base.IssueOwner.CharacterObject, false);
					return textObject;
				}
			}

			// Token: 0x0600582E RID: 22574 RVA: 0x001A0FCD File Offset: 0x0019F1CD
			public ArtisanOverpricedGoodsIssue(Hero issueOwner, Hero counterOfferHero, ItemObject requestedTradeGood)
				: base(issueOwner, CampaignTime.DaysFromNow(30f))
			{
				this.CounterOfferHero = counterOfferHero;
				this._requestedTradeGood = requestedTradeGood;
				this.CalculateTradeGoodsAmountAndReward();
			}

			// Token: 0x0600582F RID: 22575 RVA: 0x001A0FF4 File Offset: 0x0019F1F4
			protected override float GetIssueEffectAmountInternal(IssueEffect issueEffect)
			{
				if (issueEffect == DefaultIssueEffects.SettlementProsperity)
				{
					return -0.4f;
				}
				return 0f;
			}

			// Token: 0x06005830 RID: 22576 RVA: 0x001A100C File Offset: 0x0019F20C
			public override bool IssueStayAliveConditions()
			{
				return base.IssueOwner.CurrentSettlement.Town.GetItemCategoryPriceIndex(this._requestedTradeGood.ItemCategory) > 1.8f && this.CounterOfferHero.IsActive && this.CounterOfferHero.CurrentSettlement == base.IssueSettlement;
			}

			// Token: 0x06005831 RID: 22577 RVA: 0x001A1062 File Offset: 0x0019F262
			protected override void CompleteIssueWithTimedOutConsequences()
			{
			}

			// Token: 0x06005832 RID: 22578 RVA: 0x001A1064 File Offset: 0x0019F264
			public override ValueTuple<SkillObject, int> GetAlternativeSolutionSkill(Hero hero)
			{
				return new ValueTuple<SkillObject, int>((hero.GetSkillValue(DefaultSkills.Roguery) >= hero.GetSkillValue(DefaultSkills.Trade)) ? DefaultSkills.Roguery : DefaultSkills.Trade, 120);
			}

			// Token: 0x06005833 RID: 22579 RVA: 0x001A1091 File Offset: 0x0019F291
			public override bool AlternativeSolutionCondition(out TextObject explanation)
			{
				return QuestHelper.CheckRosterForAlternativeSolution(MobileParty.MainParty.MemberRoster, base.GetTotalAlternativeSolutionNeededMenCount(), out explanation, 2, false) && QuestHelper.CheckGoldForAlternativeSolution(this.RequiredGoldForAlternativeSolution, out explanation);
			}

			// Token: 0x06005834 RID: 22580 RVA: 0x001A10BB File Offset: 0x0019F2BB
			public override bool DoTroopsSatisfyAlternativeSolution(TroopRoster troopRoster, out TextObject explanation)
			{
				return QuestHelper.CheckRosterForAlternativeSolution(troopRoster, base.GetTotalAlternativeSolutionNeededMenCount(), out explanation, 2, false);
			}

			// Token: 0x06005835 RID: 22581 RVA: 0x001A10CC File Offset: 0x0019F2CC
			public override bool IsTroopTypeNeededByAlternativeSolution(CharacterObject character)
			{
				return character.Tier >= 2;
			}

			// Token: 0x06005836 RID: 22582 RVA: 0x001A10DA File Offset: 0x0019F2DA
			public override void AlternativeSolutionStartConsequence()
			{
				GiveGoldAction.ApplyBetweenCharacters(Hero.MainHero, null, this.RequiredGoldForAlternativeSolution, false);
			}

			// Token: 0x06005837 RID: 22583 RVA: 0x001A10EE File Offset: 0x0019F2EE
			protected override void AlternativeSolutionEndWithSuccessConsequence()
			{
				this.ApplySuccessRewards(base.IssueOwner);
			}

			// Token: 0x06005838 RID: 22584 RVA: 0x001A10FC File Offset: 0x0019F2FC
			public override bool LordSolutionCondition(out TextObject explanation)
			{
				if (Clan.PlayerClan == Settlement.CurrentSettlement.OwnerClan)
				{
					explanation = null;
					return true;
				}
				explanation = new TextObject("{=bItEf0WN}You need to be the {?PLAYER.GENDER}lady{?}lord{\\?} of this settlement.", null);
				StringHelpers.SetCharacterProperties("PLAYER", Hero.MainHero.CharacterObject, explanation, false);
				return false;
			}

			// Token: 0x17001057 RID: 4183
			// (get) Token: 0x06005839 RID: 22585 RVA: 0x001A113A File Offset: 0x0019F33A
			protected override int CompanionSkillRewardXP
			{
				get
				{
					return (int)(400f + 1700f * base.IssueDifficultyMultiplier);
				}
			}

			// Token: 0x0600583A RID: 22586 RVA: 0x001A1150 File Offset: 0x0019F350
			private void ApplySuccessRewards(Hero issueGiver)
			{
				issueGiver.AddPower(10f);
				ChangeRelationAction.ApplyPlayerRelation(issueGiver, 5, true, true);
				ChangeRelationAction.ApplyPlayerRelation(this.CounterOfferHero, -10, true, true);
				this.CounterOfferHero.AddPower(-10f);
				issueGiver.CurrentSettlement.Town.Prosperity += 30f;
			}

			// Token: 0x0600583B RID: 22587 RVA: 0x001A11AC File Offset: 0x0019F3AC
			public override IssueBase.IssueFrequency GetFrequency()
			{
				return IssueBase.IssueFrequency.Common;
			}

			// Token: 0x0600583C RID: 22588 RVA: 0x001A11AF File Offset: 0x0019F3AF
			protected override bool CanPlayerTakeQuestConditions(Hero issueGiver, out IssueBase.PreconditionFlags flag, out Hero relationHero, out SkillObject skill, out int requiredGold)
			{
				flag = IssueBase.PreconditionFlags.None;
				relationHero = null;
				requiredGold = 0;
				skill = null;
				if (issueGiver.GetRelationWithPlayer() < -10f)
				{
					flag |= IssueBase.PreconditionFlags.Relation;
					relationHero = issueGiver;
				}
				return flag == IssueBase.PreconditionFlags.None;
			}

			// Token: 0x0600583D RID: 22589 RVA: 0x001A11DC File Offset: 0x0019F3DC
			private void CalculateTradeGoodsAmountAndReward()
			{
				this.RequestedTradeGoodAmount = MathF.Max((int)(10000f / (float)this._requestedTradeGood.Value * base.IssueDifficultyMultiplier), 1);
				this._goldReward = (int)((float)QuestHelper.GetAveragePriceOfItemInTheWorld(this._requestedTradeGood) * 1.5f * (float)this.RequestedTradeGoodAmount);
			}

			// Token: 0x0600583E RID: 22590 RVA: 0x001A1230 File Offset: 0x0019F430
			protected override void OnGameLoad()
			{
				if (this.RequestedTradeGoodAmount == 0 || this._goldReward == 0)
				{
					this.CalculateTradeGoodsAmountAndReward();
				}
			}

			// Token: 0x0600583F RID: 22591 RVA: 0x001A1248 File Offset: 0x0019F448
			protected override void HourlyTick()
			{
			}

			// Token: 0x06005840 RID: 22592 RVA: 0x001A124A File Offset: 0x0019F44A
			protected override QuestBase GenerateIssueQuest(string questId)
			{
				return new ArtisanOverpricedGoodsIssueBehavior.ArtisanOverpricedGoodsIssueQuest(questId, base.IssueOwner, CampaignTime.DaysFromNow(30f), this._requestedTradeGood, this.RewardGold, this.RequestedTradeGoodAmount, this.CounterOfferHero);
			}

			// Token: 0x04001D35 RID: 7477
			private const int RequiredTradeSkillLevelForSendingComp = 120;

			// Token: 0x04001D36 RID: 7478
			private const int BaseRewardGold = 300;

			// Token: 0x04001D37 RID: 7479
			private const int IssueDuration = 30;

			// Token: 0x04001D38 RID: 7480
			private const int QuestTimeLimit = 30;

			// Token: 0x04001D39 RID: 7481
			private const int MinimumAlternativeTroopTier = 2;

			// Token: 0x04001D3A RID: 7482
			[SaveableField(13)]
			private int _goldReward;

			// Token: 0x04001D3C RID: 7484
			[SaveableField(10)]
			private ItemObject _requestedTradeGood;
		}

		// Token: 0x02000720 RID: 1824
		public class ArtisanOverpricedGoodsIssueQuest : QuestBase
		{
			// Token: 0x06005841 RID: 22593 RVA: 0x001A127A File Offset: 0x0019F47A
			internal static void AutoGeneratedStaticCollectObjectsArtisanOverpricedGoodsIssueQuest(object o, List<object> collectedObjects)
			{
				((ArtisanOverpricedGoodsIssueBehavior.ArtisanOverpricedGoodsIssueQuest)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x06005842 RID: 22594 RVA: 0x001A1288 File Offset: 0x0019F488
			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
				collectedObjects.Add(this._requestedTradeGood);
				collectedObjects.Add(this._playerStartsQuestLog);
			}

			// Token: 0x06005843 RID: 22595 RVA: 0x001A12A9 File Offset: 0x0019F4A9
			internal static object AutoGeneratedGetMemberValue_rewardGold(object o)
			{
				return ((ArtisanOverpricedGoodsIssueBehavior.ArtisanOverpricedGoodsIssueQuest)o)._rewardGold;
			}

			// Token: 0x06005844 RID: 22596 RVA: 0x001A12BB File Offset: 0x0019F4BB
			internal static object AutoGeneratedGetMemberValue_requestedTradeGood(object o)
			{
				return ((ArtisanOverpricedGoodsIssueBehavior.ArtisanOverpricedGoodsIssueQuest)o)._requestedTradeGood;
			}

			// Token: 0x06005845 RID: 22597 RVA: 0x001A12C8 File Offset: 0x0019F4C8
			internal static object AutoGeneratedGetMemberValue_requestedTradeGoodAmount(object o)
			{
				return ((ArtisanOverpricedGoodsIssueBehavior.ArtisanOverpricedGoodsIssueQuest)o)._requestedTradeGoodAmount;
			}

			// Token: 0x06005846 RID: 22598 RVA: 0x001A12DA File Offset: 0x0019F4DA
			internal static object AutoGeneratedGetMemberValue_givenTradeGoods(object o)
			{
				return ((ArtisanOverpricedGoodsIssueBehavior.ArtisanOverpricedGoodsIssueQuest)o)._givenTradeGoods;
			}

			// Token: 0x06005847 RID: 22599 RVA: 0x001A12EC File Offset: 0x0019F4EC
			internal static object AutoGeneratedGetMemberValue_playerStartsQuestLog(object o)
			{
				return ((ArtisanOverpricedGoodsIssueBehavior.ArtisanOverpricedGoodsIssueQuest)o)._playerStartsQuestLog;
			}

			// Token: 0x17001058 RID: 4184
			// (get) Token: 0x06005848 RID: 22600 RVA: 0x001A12F9 File Offset: 0x0019F4F9
			public override TextObject Title
			{
				get
				{
					TextObject textObject = new TextObject("{=dt6kKXSL}Overpriced Raw Materials at {SETTLEMENT}", null);
					textObject.SetTextVariable("SETTLEMENT", base.QuestGiver.CurrentSettlement.Name);
					return textObject;
				}
			}

			// Token: 0x17001059 RID: 4185
			// (get) Token: 0x06005849 RID: 22601 RVA: 0x001A1322 File Offset: 0x0019F522
			private Hero AntagonistHero
			{
				get
				{
					return base.QuestGiver.CurrentSettlement.Notables.FirstOrDefault<Hero>((Hero x) => x != base.QuestGiver && x.IsMerchant && x.GetTraitLevel(DefaultTraits.Mercy) <= 0);
				}
			}

			// Token: 0x1700105A RID: 4186
			// (get) Token: 0x0600584A RID: 22602 RVA: 0x001A1345 File Offset: 0x0019F545
			public override bool IsRemainingTimeHidden
			{
				get
				{
					return false;
				}
			}

			// Token: 0x1700105B RID: 4187
			// (get) Token: 0x0600584B RID: 22603 RVA: 0x001A1348 File Offset: 0x0019F548
			private TextObject PlayerStartsQuestLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=IL3QWZ93}{QUEST_GIVER.LINK}, an artisan from {SETTLEMENT}, has told you about local merchant asking ridiculous amounts of money for the raw materials that {?QUEST_GIVER.GENDER}she{?}he{\\?} needs to continue {?QUEST_GIVER.GENDER}her{?}his{\\?} work. You said that you can bring {?QUEST_GIVER.GENDER}her{?}him{\\?} {REQUESTED_AMOUNT} {.%}{?REQUESTED_AMOUNT > 1}{PLURAL(REQUESTED_GOOD)}{?}{REQUESTED_GOOD}{\\?}{.%}. {?QUEST_GIVER.GENDER}She{?}He{\\?} is willing to pay {REWARD_AMOUNT}{GOLD_ICON} for these items.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("SETTLEMENT", base.QuestGiver.CurrentSettlement.EncyclopediaLinkWithName);
					textObject.SetTextVariable("REQUESTED_AMOUNT", this._requestedTradeGoodAmount);
					textObject.SetTextVariable("REQUESTED_GOOD", this._requestedTradeGood.Name);
					textObject.SetTextVariable("REWARD_AMOUNT", this._rewardGold);
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"6\">");
					return textObject;
				}
			}

			// Token: 0x1700105C RID: 4188
			// (get) Token: 0x0600584C RID: 22604 RVA: 0x001A13E4 File Offset: 0x0019F5E4
			private TextObject SuccessQuestLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=6XvszYj2}You brought {REQUESTED_AMOUNT} {.%}{?REQUESTED_AMOUNT > 1}{PLURAL(REQUESTED_GOOD)}{?}{REQUESTED_GOOD}{\\?}{.%} to {?QUEST_GIVER.GENDER}her{?}him{\\?} as promised.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("REQUESTED_AMOUNT", this._requestedTradeGoodAmount);
					textObject.SetTextVariable("REQUESTED_GOOD", this._requestedTradeGood.Name);
					return textObject;
				}
			}

			// Token: 0x1700105D RID: 4189
			// (get) Token: 0x0600584D RID: 22605 RVA: 0x001A1440 File Offset: 0x0019F640
			private TextObject TimeoutQuestLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=Ts5dZih4}You couldn't fully bring {.%}{REQUESTED_GOOD}{.%} to {?QUEST_GIVER.GENDER}her{?}him{\\?} in time.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("REQUESTED_GOOD", this._requestedTradeGood.Name);
					return textObject;
				}
			}

			// Token: 0x0600584E RID: 22606 RVA: 0x001A1489 File Offset: 0x0019F689
			protected override void InitializeQuestOnGameLoad()
			{
				this.SetDialogs();
				Campaign.Current.ConversationManager.AddDialogFlow(this.GetMerchantDialogFlow(), this);
			}

			// Token: 0x0600584F RID: 22607 RVA: 0x001A14A7 File Offset: 0x0019F6A7
			protected override void HourlyTick()
			{
			}

			// Token: 0x06005850 RID: 22608 RVA: 0x001A14A9 File Offset: 0x0019F6A9
			public ArtisanOverpricedGoodsIssueQuest(string questId, Hero questGiver, CampaignTime dueTime, ItemObject requestedTradeGood, int rewardGold, int requestedTradeGoodAmount, Hero counterOfferHero)
				: base(questId, questGiver, dueTime, rewardGold)
			{
				this._requestedTradeGood = requestedTradeGood;
				this._requestedTradeGoodAmount = requestedTradeGoodAmount;
				this._rewardGold = rewardGold;
				this.SetDialogs();
				base.InitializeQuestOnCreation();
			}

			// Token: 0x06005851 RID: 22609 RVA: 0x001A14DC File Offset: 0x0019F6DC
			protected override void SetDialogs()
			{
				this.OfferDialogFlow = DialogFlow.CreateDialogFlow("issue_classic_quest_start", 100).NpcLine(new TextObject("{=e1sSXEOh}This is excellent news. If you could bring the goods, it would be an immense help, and the merchants would have to lower their prices. Thank you.[if:convo_excited][ib:hip2]", null), null, null, null, null).Condition(() => Hero.OneToOneConversationHero == base.QuestGiver)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.QuestAcceptedConsequences))
					.CloseDialog();
				TextObject textObject = new TextObject("{=fKnkkWH1}Have you brought any {.%}{REQUESTED_GOOD}{.%}? My stocks are running out and I need some very soon.", null);
				textObject.SetTextVariable("REQUESTED_GOOD", this._requestedTradeGood.Name);
				TextObject textObject2 = new TextObject("{=bPbzwMat}I could only deliver {AMOUNT_TO_DELIVER} {.%}{?AMOUNT_TO_DELIVER > 1}{PLURAL(REQUESTED_GOOD)}{?}{REQUESTED_GOOD}{\\?}{.%}.", null);
				textObject2.SetTextVariable("REQUESTED_GOOD", this._requestedTradeGood.Name);
				textObject2.SetTextVariable("AMOUNT_TO_DELIVER", this.GetAvailableRequestedItemCountOnPlayer());
				TextObject textObject3 = new TextObject("{=IfF3OHNT}Thank you. These will be very useful. If you can get your hands on more, please bring them directly to me.", null);
				TextObject textObject4 = new TextObject("{=1LzohiMf}I brought {AMOUNT_TO_DELIVER} {.%}{?AMOUNT_TO_DELIVER > 1}{PLURAL(REQUESTED_GOOD)}{?}{REQUESTED_GOOD}{\\?}{.%} as we agreed.", null);
				textObject4.SetTextVariable("AMOUNT_TO_DELIVER", this._requestedTradeGoodAmount - this._givenTradeGoods);
				textObject4.SetTextVariable("REQUESTED_GOOD", this._requestedTradeGood.Name);
				TextObject textObject5 = new TextObject("{=cxQGUbUD}I'm so grateful! You've kept my workshop running and my family fed. Please take this money and some extra to cover your costs.[if:convo_grateful][ib:normal2]", null);
				TextObject textObject6 = new TextObject("{=4uKTfTg9}Sorry. I don't have anything for you this time.", null);
				TextObject textObject7 = new TextObject("{=YWorGaI1}Ah... We'll get by. I won't lie. It will be hard. I just hope you can deliver some soon.[if:convo_normal][ib:closed]", null);
				this.DiscussDialogFlow = DialogFlow.CreateDialogFlow("quest_discuss", 100).NpcLine(textObject, null, null, null, null).Condition(() => Hero.OneToOneConversationHero == base.QuestGiver)
					.BeginPlayerOptions(null, false)
					.PlayerOption(textObject2, null, null, null)
					.Condition(delegate
					{
						int availableRequestedItemCountOnPlayer = this.GetAvailableRequestedItemCountOnPlayer();
						Campaign.Current.ConversationManager.GetCurrentDialogLine().SetTextVariable("REQUESTED_GOOD", this._requestedTradeGood.Name);
						Campaign.Current.ConversationManager.GetCurrentDialogLine().SetTextVariable("AMOUNT_TO_DELIVER", availableRequestedItemCountOnPlayer);
						return availableRequestedItemCountOnPlayer > 0 && availableRequestedItemCountOnPlayer < this._requestedTradeGoodAmount - this._givenTradeGoods;
					})
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.DeliverItemsPartiallyOnConsequence))
					.NpcLine(textObject3, null, null, null, null)
					.CloseDialog()
					.PlayerOption(textObject4, null, null, null)
					.Condition(delegate
					{
						int availableRequestedItemCountOnPlayer2 = this.GetAvailableRequestedItemCountOnPlayer();
						Campaign.Current.ConversationManager.GetCurrentDialogLine().SetTextVariable("AMOUNT_TO_DELIVER", this._requestedTradeGoodAmount - this._givenTradeGoods);
						Campaign.Current.ConversationManager.GetCurrentDialogLine().SetTextVariable("REQUESTED_GOOD", this._requestedTradeGood.Name);
						return availableRequestedItemCountOnPlayer2 >= this._requestedTradeGoodAmount - this._givenTradeGoods;
					})
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.DeliverItemsFullyOnConsequence))
					.NpcLine(textObject5, null, null, null, null)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(base.CompleteQuestWithSuccess))
					.CloseDialog()
					.PlayerOption(textObject6, null, null, null)
					.NpcLine(textObject7, null, null, null, null)
					.CloseDialog()
					.EndPlayerOptions()
					.CloseDialog();
			}

			// Token: 0x06005852 RID: 22610 RVA: 0x001A16DB File Offset: 0x0019F8DB
			private int GetAvailableRequestedItemCountOnPlayer()
			{
				return PartyBase.MainParty.ItemRoster.GetItemNumber(this._requestedTradeGood);
			}

			// Token: 0x06005853 RID: 22611 RVA: 0x001A16F4 File Offset: 0x0019F8F4
			private void DeliverItemsPartiallyOnConsequence()
			{
				int num = this.GetAvailableRequestedItemCountOnPlayer();
				if (PartyBase.MainParty.ItemRoster.ElementAt<ItemRosterElement>(PartyBase.MainParty.ItemRoster.FindIndex((ItemObject x) => x == this._requestedTradeGood)).Amount <= 0)
				{
					num = 0;
				}
				PartyBase.MainParty.ItemRoster.AddToCounts(this._requestedTradeGood, -num);
				this._givenTradeGoods += num;
				base.UpdateQuestTaskStage(this._playerStartsQuestLog, this._givenTradeGoods);
			}

			// Token: 0x06005854 RID: 22612 RVA: 0x001A1778 File Offset: 0x0019F978
			private void DeliverItemsFullyOnConsequence()
			{
				TraitLevelingHelper.OnIssueSolvedThroughQuest(base.QuestGiver, new Tuple<TraitObject, int>[]
				{
					new Tuple<TraitObject, int>(DefaultTraits.Honor, 50)
				});
				ChangeCrimeRatingAction.Apply(base.QuestGiver.MapFaction, 5f, true);
				PartyBase.MainParty.ItemRoster.AddToCounts(this._requestedTradeGood, -(this._requestedTradeGoodAmount - this._givenTradeGoods));
				this._givenTradeGoods = this._requestedTradeGoodAmount;
				base.UpdateQuestTaskStage(this._playerStartsQuestLog, this._givenTradeGoods);
			}

			// Token: 0x06005855 RID: 22613 RVA: 0x001A1800 File Offset: 0x0019FA00
			private void QuestAcceptedConsequences()
			{
				base.StartQuest();
				this._playerStartsQuestLog = base.AddDiscreteLog(this.PlayerStartsQuestLogText, new TextObject("{=yw62BLhy}Delivered Goods", null), this._givenTradeGoods, this._requestedTradeGoodAmount, null, true);
				Campaign.Current.ConversationManager.AddDialogFlow(this.GetMerchantDialogFlow(), this);
			}

			// Token: 0x06005856 RID: 22614 RVA: 0x001A1854 File Offset: 0x0019FA54
			private DialogFlow GetMerchantDialogFlow()
			{
				TextObject textObject = new TextObject("{=YNxGcaJI}I want to talk to you about the outlandish prices you're asking for the goods you sell the artisans.", null);
				TextObject textObject2 = new TextObject("{=UwEbBanm}These are the laws of our town. The artisans don't complain when the laws require us to buy tools from them.[if:convo_bored][ib:closed2]", null);
				TextObject textObject3 = new TextObject("{=sPEZq0Yk}What's sauce for the goose is sauce for the gander. We've done business for years like this and we're not just going to change things because one party complains.[if:convo_mocking_teasing][ib:hip]", null);
				TextObject textObject4 = new TextObject("{=VzzQX4EZ}Maybe you're right. I won't get involved in this.", null);
				TextObject textObject5 = new TextObject("{=KbFJJfl6}I am sorry. I will do what I must.", null);
				TextObject textObject6 = new TextObject("{=yccVH4KD}Thank you for listening to the voice of reason.", null);
				TextObject textObject7 = new TextObject("{=A8dyXgLz}That's a pity.", null);
				return DialogFlow.CreateDialogFlow("hero_main_options", 125).PlayerLine(textObject, null, null, null).Condition(new ConversationSentence.OnConditionDelegate(this.IsSuitableToTalk))
					.NpcLine(textObject2, null, null, null, null)
					.NpcLine(textObject3, null, null, null, null)
					.BeginPlayerOptions(null, false)
					.PlayerOption(textObject4, null, null, null)
					.NpcLine(textObject6, null, null, null, null)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.AcceptCounterOffer))
					.CloseDialog()
					.PlayerOption(textObject5, null, null, null)
					.NpcLine(textObject7, null, null, null, null)
					.CloseDialog();
			}

			// Token: 0x06005857 RID: 22615 RVA: 0x001A193D File Offset: 0x0019FB3D
			private bool IsSuitableToTalk()
			{
				return Settlement.CurrentSettlement == base.QuestGiver.CurrentSettlement && CharacterObject.OneToOneConversationCharacter.IsHero && CharacterObject.OneToOneConversationCharacter.HeroObject == this.AntagonistHero;
			}

			// Token: 0x06005858 RID: 22616 RVA: 0x001A1974 File Offset: 0x0019FB74
			private void AcceptCounterOffer()
			{
				Hero antagonistHero = this.AntagonistHero;
				TextObject textObject = new TextObject("{=q4wWEbsa}You decided not to deliver the items after listening to {COUNTER_OFFER_HERO.LINK}.", null);
				StringHelpers.SetCharacterProperties("COUNTER_OFFER_HERO", antagonistHero.CharacterObject, textObject, false);
				ChangeRelationAction.ApplyPlayerRelation(antagonistHero, 5, true, true);
				antagonistHero.AddPower(5f);
				TraitLevelingHelper.OnIssueSolvedThroughBetrayal(base.QuestGiver, new Tuple<TraitObject, int>[]
				{
					new Tuple<TraitObject, int>(DefaultTraits.Honor, -50)
				});
				base.QuestGiver.CurrentSettlement.Town.Prosperity -= 30f;
				base.CompleteQuestWithFail(textObject);
			}

			// Token: 0x06005859 RID: 22617 RVA: 0x001A1A04 File Offset: 0x0019FC04
			protected override void OnCompleteWithSuccess()
			{
				base.QuestGiver.AddPower(10f);
				TraitLevelingHelper.OnIssueSolvedThroughQuest(base.QuestGiver, new Tuple<TraitObject, int>[]
				{
					new Tuple<TraitObject, int>(DefaultTraits.Honor, 50)
				});
				base.QuestGiver.CurrentSettlement.Town.Prosperity += 30f;
				this.RelationshipChangeWithQuestGiver = 5;
				if (this.AntagonistHero != null)
				{
					this.AntagonistHero.AddPower(-10f);
					ChangeRelationAction.ApplyPlayerRelation(this.AntagonistHero, -10, true, true);
				}
				GiveGoldAction.ApplyBetweenCharacters(null, Hero.MainHero, this._rewardGold, false);
				base.AddLog(this.SuccessQuestLogText, false);
			}

			// Token: 0x0600585A RID: 22618 RVA: 0x001A1AB0 File Offset: 0x0019FCB0
			public override void OnFailed()
			{
				base.QuestGiver.AddPower(-10f);
				this.RelationshipChangeWithQuestGiver = -5;
				base.QuestGiver.CurrentSettlement.Town.Prosperity -= 20f;
			}

			// Token: 0x0600585B RID: 22619 RVA: 0x001A1AEC File Offset: 0x0019FCEC
			protected override void OnTimedOut()
			{
				base.AddLog(this.TimeoutQuestLogText, false);
				base.QuestGiver.AddPower(-20f);
				this.RelationshipChangeWithQuestGiver = -5;
				base.QuestGiver.CurrentSettlement.Town.Prosperity -= 50f;
			}

			// Token: 0x04001D3E RID: 7486
			[SaveableField(20)]
			private int _rewardGold;

			// Token: 0x04001D3F RID: 7487
			[SaveableField(30)]
			private readonly ItemObject _requestedTradeGood;

			// Token: 0x04001D40 RID: 7488
			[SaveableField(60)]
			private readonly int _requestedTradeGoodAmount;

			// Token: 0x04001D41 RID: 7489
			[SaveableField(40)]
			private int _givenTradeGoods;

			// Token: 0x04001D42 RID: 7490
			[SaveableField(50)]
			private JournalLog _playerStartsQuestLog;
		}

		// Token: 0x02000721 RID: 1825
		public class ArtisanOverpricedGoodsIssueTypeDefiner : SaveableTypeDefiner
		{
			// Token: 0x06005862 RID: 22626 RVA: 0x001A1C6C File Offset: 0x0019FE6C
			public ArtisanOverpricedGoodsIssueTypeDefiner()
				: base(470000)
			{
			}

			// Token: 0x06005863 RID: 22627 RVA: 0x001A1C79 File Offset: 0x0019FE79
			protected override void DefineClassTypes()
			{
				base.AddClassDefinition(typeof(ArtisanOverpricedGoodsIssueBehavior.ArtisanOverpricedGoodsIssue), 1, null);
				base.AddClassDefinition(typeof(ArtisanOverpricedGoodsIssueBehavior.ArtisanOverpricedGoodsIssueQuest), 2, null);
			}
		}
	}
}
