using System;
using System.ComponentModel;
using System.Numerics;
using TaleWorlds.CampaignSystem.ViewModelCollection.Encyclopedia.List;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.GauntletUI.Data;
using TaleWorlds.GauntletUI.GamepadNavigation;
using TaleWorlds.GauntletUI.Layout;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets.Party;

namespace SandBox.GauntletUI.AutoGenerated0
{
	// Token: 0x020000C7 RID: 199
	public class EncyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaHeroPageVM_Dependency_4_EncyclopediaFilterGroup__InheritedPrefab : Widget
	{
		// Token: 0x06003A65 RID: 14949 RVA: 0x001D0AF8 File Offset: 0x001CECF8
		public EncyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaHeroPageVM_Dependency_4_EncyclopediaFilterGroup__InheritedPrefab(UIContext context)
			: base(context)
		{
		}

		// Token: 0x06003A66 RID: 14950 RVA: 0x001D0B04 File Offset: 0x001CED04
		public virtual void CreateWidgets()
		{
			this._widget = this;
			this._widget_0 = new NavigationScopeTargeter(base.Context);
			this._widget.AddChild(this._widget_0);
			this._widget_1 = new NavigationAutoScrollWidget(base.Context);
			this._widget.AddChild(this._widget_1);
			this._widget_2 = new PartyHeaderToggleWidget(base.Context);
			this._widget.AddChild(this._widget_2);
			this._widget_2_0 = new ListPanel(base.Context);
			this._widget_2.AddChild(this._widget_2_0);
			this._widget_2_0_0 = new ImageWidget(base.Context);
			this._widget_2_0.AddChild(this._widget_2_0_0);
			this._widget_2_0_1 = new TextWidget(base.Context);
			this._widget_2_0.AddChild(this._widget_2_0_1);
			this._widget_2_0_2 = new ImageWidget(base.Context);
			this._widget_2_0.AddChild(this._widget_2_0_2);
			this._widget_3 = new NavigatableListPanel(base.Context);
			this._widget.AddChild(this._widget_3);
		}

		// Token: 0x06003A67 RID: 14951 RVA: 0x001D0C28 File Offset: 0x001CEE28
		public virtual void SetIds()
		{
			this._widget_2.Id = "HeaderToggle";
			this._widget_2_0.Id = "Description";
			this._widget_2_0_0.Id = "CollapseIndicator";
			this._widget_3.Id = "Filters";
		}

		// Token: 0x06003A68 RID: 14952 RVA: 0x001D0C78 File Offset: 0x001CEE78
		public virtual void SetAttributes()
		{
			base.HeightSizePolicy = SizePolicy.CoverChildren;
			base.WidthSizePolicy = SizePolicy.StretchToParent;
			base.DoNotAcceptEvents = true;
			this._widget_0.ScopeID = "EncyclopediaFilterGroupScope";
			this._widget_0.ScopeParent = this._widget;
			this._widget_0.ScopeMovements = GamepadNavigationTypes.Vertical;
			this._widget_1.TrackedWidget = this._widget_2;
			this._widget_2.DoNotPassEventsToChildren = true;
			this._widget_2.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_2.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_2.HorizontalAlignment = HorizontalAlignment.Left;
			this._widget_2.VerticalAlignment = VerticalAlignment.Top;
			this._widget_2.CollapseIndicator = this._widget_2_0_0;
			this._widget_2.ListPanel = this._widget_3;
			this._widget_2.RenderLate = true;
			this._widget_2.WidgetToClose = this._widget_3;
			this._widget_2.UpdateChildrenStates = true;
			this._widget_2.GamepadNavigationIndex = 0;
			this._widget_2_0.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_2_0.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_2_0.HorizontalAlignment = HorizontalAlignment.Left;
			this._widget_2_0.VerticalAlignment = VerticalAlignment.Center;
			this._widget_2_0.DoNotAcceptEvents = true;
			this._widget_2_0.UpdateChildrenStates = true;
			this._widget_2_0.StackLayout.LayoutMethod = LayoutMethod.HorizontalLeftToRight;
			this._widget_2_0_0.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_2_0_0.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_2_0_0.SuggestedHeight = 19f;
			this._widget_2_0_0.SuggestedWidth = 19f;
			this._widget_2_0_0.VerticalAlignment = VerticalAlignment.Center;
			this._widget_2_0_0.PositionXOffset = -10f;
			this._widget_2_0_0.PositionYOffset = -3f;
			this._widget_2_0_0.Brush = base.Context.GetBrush("SPOptions.GameKeysgroup.ExpandIndicator");
			this._widget_2_0_0.OverrideDefaultStateSwitchingEnabled = true;
			this._widget_2_0_1.WidthSizePolicy = SizePolicy.CoverChildren;
			this._widget_2_0_1.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_2_0_1.Brush = base.Context.GetBrush("SPOptions.GameKeysGroup.Title.Text");
			this._widget_2_0_1.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_2_0_2.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_2_0_2.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_2_0_2.SuggestedHeight = 2f;
			this._widget_2_0_2.VerticalAlignment = VerticalAlignment.Center;
			this._widget_2_0_2.MarginLeft = 5f;
			this._widget_2_0_2.Brush = base.Context.GetBrush("SPOptions.CollapserLine");
			this._widget_3.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_3.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_3.StackLayout.LayoutMethod = LayoutMethod.VerticalBottomToTop;
			this._widget_3.MarginTop = 40f;
			this._widget_3.DoNotAcceptEvents = true;
			this._widget_3.MarginLeft = 5f;
			this._widget_3.MaxIndex = 10000;
		}

		// Token: 0x06003A69 RID: 14953 RVA: 0x001D0F54 File Offset: 0x001CF154
		public virtual void DestroyDataSource()
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget_2_0_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_2_0_1;
				this._widget_2_0_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_2_0_1;
				this._widget_2_0_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_2_0_1;
				this._widget_2_0_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_2_0_1;
				this._widget_2_0_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_2_0_1;
				this._widget_2_0_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_2_0_1;
				this._widget_2_0_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_2_0_1;
				this._widget_2_0_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_2_0_1;
				this._widget_2_0_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_2_0_1;
				if (this._datasource_Root_Filters != null)
				{
					this._datasource_Root_Filters.ListChanged -= this.OnList_datasource_Root_FiltersChanged;
					for (int i = this._widget_3.ChildCount - 1; i >= 0; i--)
					{
						Widget child = this._widget_3.GetChild(i);
						((EncyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaHeroPageVM_Dependency_7_ItemTemplate)child).OnBeforeRemovedChild(child);
						((EncyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaHeroPageVM_Dependency_7_ItemTemplate)this._widget_3.GetChild(i)).DestroyDataSource();
					}
					this._datasource_Root_Filters = null;
				}
				this._datasource_Root = null;
			}
		}

		// Token: 0x06003A6A RID: 14954 RVA: 0x001D117E File Offset: 0x001CF37E
		public virtual void SetDataSource(EncyclopediaFilterGroupVM dataSource)
		{
			this.RefreshDataSource_datasource_Root(dataSource);
		}

		// Token: 0x06003A6B RID: 14955 RVA: 0x001D1187 File Offset: 0x001CF387
		private void PropertyChangedListenerOf_widget_2_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2_0_1(propertyName);
		}

		// Token: 0x06003A6C RID: 14956 RVA: 0x001D1190 File Offset: 0x001CF390
		private void boolPropertyChangedListenerOf_widget_2_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2_0_1(propertyName);
		}

		// Token: 0x06003A6D RID: 14957 RVA: 0x001D1199 File Offset: 0x001CF399
		private void floatPropertyChangedListenerOf_widget_2_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2_0_1(propertyName);
		}

		// Token: 0x06003A6E RID: 14958 RVA: 0x001D11A2 File Offset: 0x001CF3A2
		private void Vec2PropertyChangedListenerOf_widget_2_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2_0_1(propertyName);
		}

		// Token: 0x06003A6F RID: 14959 RVA: 0x001D11AB File Offset: 0x001CF3AB
		private void Vector2PropertyChangedListenerOf_widget_2_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2_0_1(propertyName);
		}

		// Token: 0x06003A70 RID: 14960 RVA: 0x001D11B4 File Offset: 0x001CF3B4
		private void doublePropertyChangedListenerOf_widget_2_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2_0_1(propertyName);
		}

		// Token: 0x06003A71 RID: 14961 RVA: 0x001D11BD File Offset: 0x001CF3BD
		private void intPropertyChangedListenerOf_widget_2_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2_0_1(propertyName);
		}

		// Token: 0x06003A72 RID: 14962 RVA: 0x001D11C6 File Offset: 0x001CF3C6
		private void uintPropertyChangedListenerOf_widget_2_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2_0_1(propertyName);
		}

		// Token: 0x06003A73 RID: 14963 RVA: 0x001D11CF File Offset: 0x001CF3CF
		private void ColorPropertyChangedListenerOf_widget_2_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2_0_1(propertyName);
		}

		// Token: 0x06003A74 RID: 14964 RVA: 0x001D11D8 File Offset: 0x001CF3D8
		private void HandleWidgetPropertyChangeOf_widget_2_0_1(string propertyName)
		{
			if (propertyName == "Text")
			{
				this._datasource_Root.FilterName = this._widget_2_0_1.Text;
				return;
			}
		}

		// Token: 0x06003A75 RID: 14965 RVA: 0x001D11FE File Offset: 0x001CF3FE
		private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06003A76 RID: 14966 RVA: 0x001D120C File Offset: 0x001CF40C
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06003A77 RID: 14967 RVA: 0x001D121B File Offset: 0x001CF41B
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06003A78 RID: 14968 RVA: 0x001D122A File Offset: 0x001CF42A
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06003A79 RID: 14969 RVA: 0x001D1239 File Offset: 0x001CF439
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06003A7A RID: 14970 RVA: 0x001D1248 File Offset: 0x001CF448
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06003A7B RID: 14971 RVA: 0x001D1257 File Offset: 0x001CF457
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06003A7C RID: 14972 RVA: 0x001D1266 File Offset: 0x001CF466
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06003A7D RID: 14973 RVA: 0x001D1275 File Offset: 0x001CF475
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06003A7E RID: 14974 RVA: 0x001D1284 File Offset: 0x001CF484
		private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
		{
			if (propertyName == "Filters")
			{
				this.RefreshDataSource_datasource_Root_Filters(this._datasource_Root.Filters);
				return;
			}
			if (propertyName == "FilterName")
			{
				this._widget_2_0_1.Text = this._datasource_Root.FilterName;
				return;
			}
		}

		// Token: 0x06003A7F RID: 14975 RVA: 0x001D12D4 File Offset: 0x001CF4D4
		public void OnList_datasource_Root_FiltersChanged(object sender, ListChangedEventArgs e)
		{
			switch (e.ListChangedType)
			{
			case ListChangedType.Reset:
			{
				for (int i = this._widget_3.ChildCount - 1; i >= 0; i--)
				{
					Widget child = this._widget_3.GetChild(i);
					((EncyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaHeroPageVM_Dependency_7_ItemTemplate)child).OnBeforeRemovedChild(child);
					Widget child2 = this._widget_3.GetChild(i);
					((EncyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaHeroPageVM_Dependency_7_ItemTemplate)child2).SetDataSource(null);
					this._widget_3.RemoveChild(child2);
				}
				return;
			}
			case ListChangedType.Sorted:
			{
				for (int j = 0; j < this._datasource_Root_Filters.Count; j++)
				{
					EncyclopediaListFilterVM bindingObject = this._datasource_Root_Filters[j];
					this._widget_3.FindChild((Widget widget) => widget.GetComponent<GeneratedWidgetData>().Data == bindingObject).SetSiblingIndex(j, false);
				}
				return;
			}
			case ListChangedType.ItemAdded:
			{
				EncyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaHeroPageVM_Dependency_7_ItemTemplate encyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaHeroPageVM_Dependency_7_ItemTemplate = new EncyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaHeroPageVM_Dependency_7_ItemTemplate(base.Context);
				GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(encyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaHeroPageVM_Dependency_7_ItemTemplate);
				EncyclopediaListFilterVM encyclopediaListFilterVM = this._datasource_Root_Filters[e.NewIndex];
				generatedWidgetData.Data = encyclopediaListFilterVM;
				encyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaHeroPageVM_Dependency_7_ItemTemplate.AddComponent(generatedWidgetData);
				this._widget_3.AddChildAtIndex(encyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaHeroPageVM_Dependency_7_ItemTemplate, e.NewIndex);
				encyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaHeroPageVM_Dependency_7_ItemTemplate.CreateWidgets();
				encyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaHeroPageVM_Dependency_7_ItemTemplate.SetIds();
				encyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaHeroPageVM_Dependency_7_ItemTemplate.SetAttributes();
				encyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaHeroPageVM_Dependency_7_ItemTemplate.SetDataSource(encyclopediaListFilterVM);
				return;
			}
			case ListChangedType.ItemBeforeDeleted:
			{
				Widget child3 = this._widget_3.GetChild(e.NewIndex);
				((EncyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaHeroPageVM_Dependency_7_ItemTemplate)child3).OnBeforeRemovedChild(child3);
				return;
			}
			case ListChangedType.ItemDeleted:
			{
				Widget child4 = this._widget_3.GetChild(e.NewIndex);
				((EncyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaHeroPageVM_Dependency_7_ItemTemplate)child4).SetDataSource(null);
				this._widget_3.RemoveChild(child4);
				break;
			}
			case ListChangedType.ItemChanged:
				break;
			default:
				return;
			}
		}

		// Token: 0x06003A80 RID: 14976 RVA: 0x001D1470 File Offset: 0x001CF670
		private void RefreshDataSource_datasource_Root(EncyclopediaFilterGroupVM newDataSource)
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget_2_0_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_2_0_1;
				this._widget_2_0_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_2_0_1;
				this._widget_2_0_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_2_0_1;
				this._widget_2_0_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_2_0_1;
				this._widget_2_0_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_2_0_1;
				this._widget_2_0_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_2_0_1;
				this._widget_2_0_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_2_0_1;
				this._widget_2_0_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_2_0_1;
				this._widget_2_0_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_2_0_1;
				if (this._datasource_Root_Filters != null)
				{
					this._datasource_Root_Filters.ListChanged -= this.OnList_datasource_Root_FiltersChanged;
					for (int i = this._widget_3.ChildCount - 1; i >= 0; i--)
					{
						Widget child = this._widget_3.GetChild(i);
						((EncyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaHeroPageVM_Dependency_7_ItemTemplate)child).OnBeforeRemovedChild(child);
						Widget child2 = this._widget_3.GetChild(i);
						((EncyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaHeroPageVM_Dependency_7_ItemTemplate)child2).SetDataSource(null);
						this._widget_3.RemoveChild(child2);
					}
					this._datasource_Root_Filters = null;
				}
				this._datasource_Root = null;
			}
			this._datasource_Root = newDataSource;
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget_2_0_1.Text = this._datasource_Root.FilterName;
				this._widget_2_0_1.PropertyChanged += this.PropertyChangedListenerOf_widget_2_0_1;
				this._widget_2_0_1.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_2_0_1;
				this._widget_2_0_1.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_2_0_1;
				this._widget_2_0_1.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_2_0_1;
				this._widget_2_0_1.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_2_0_1;
				this._widget_2_0_1.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_2_0_1;
				this._widget_2_0_1.intPropertyChanged += this.intPropertyChangedListenerOf_widget_2_0_1;
				this._widget_2_0_1.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_2_0_1;
				this._widget_2_0_1.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_2_0_1;
				this._datasource_Root_Filters = this._datasource_Root.Filters;
				if (this._datasource_Root_Filters != null)
				{
					this._datasource_Root_Filters.ListChanged += this.OnList_datasource_Root_FiltersChanged;
					for (int j = 0; j < this._datasource_Root_Filters.Count; j++)
					{
						EncyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaHeroPageVM_Dependency_7_ItemTemplate encyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaHeroPageVM_Dependency_7_ItemTemplate = new EncyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaHeroPageVM_Dependency_7_ItemTemplate(base.Context);
						GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(encyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaHeroPageVM_Dependency_7_ItemTemplate);
						EncyclopediaListFilterVM encyclopediaListFilterVM = this._datasource_Root_Filters[j];
						generatedWidgetData.Data = encyclopediaListFilterVM;
						encyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaHeroPageVM_Dependency_7_ItemTemplate.AddComponent(generatedWidgetData);
						this._widget_3.AddChildAtIndex(encyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaHeroPageVM_Dependency_7_ItemTemplate, j);
						encyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaHeroPageVM_Dependency_7_ItemTemplate.CreateWidgets();
						encyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaHeroPageVM_Dependency_7_ItemTemplate.SetIds();
						encyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaHeroPageVM_Dependency_7_ItemTemplate.SetAttributes();
						encyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaHeroPageVM_Dependency_7_ItemTemplate.SetDataSource(encyclopediaListFilterVM);
					}
				}
			}
		}

		// Token: 0x06003A81 RID: 14977 RVA: 0x001D191C File Offset: 0x001CFB1C
		private void RefreshDataSource_datasource_Root_Filters(MBBindingList<EncyclopediaListFilterVM> newDataSource)
		{
			if (this._datasource_Root_Filters != null)
			{
				this._datasource_Root_Filters.ListChanged -= this.OnList_datasource_Root_FiltersChanged;
				for (int i = this._widget_3.ChildCount - 1; i >= 0; i--)
				{
					Widget child = this._widget_3.GetChild(i);
					((EncyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaHeroPageVM_Dependency_7_ItemTemplate)child).OnBeforeRemovedChild(child);
					Widget child2 = this._widget_3.GetChild(i);
					((EncyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaHeroPageVM_Dependency_7_ItemTemplate)child2).SetDataSource(null);
					this._widget_3.RemoveChild(child2);
				}
				this._datasource_Root_Filters = null;
			}
			this._datasource_Root_Filters = newDataSource;
			this._datasource_Root_Filters = this._datasource_Root.Filters;
			if (this._datasource_Root_Filters != null)
			{
				this._datasource_Root_Filters.ListChanged += this.OnList_datasource_Root_FiltersChanged;
				for (int j = 0; j < this._datasource_Root_Filters.Count; j++)
				{
					EncyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaHeroPageVM_Dependency_7_ItemTemplate encyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaHeroPageVM_Dependency_7_ItemTemplate = new EncyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaHeroPageVM_Dependency_7_ItemTemplate(base.Context);
					GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(encyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaHeroPageVM_Dependency_7_ItemTemplate);
					EncyclopediaListFilterVM encyclopediaListFilterVM = this._datasource_Root_Filters[j];
					generatedWidgetData.Data = encyclopediaListFilterVM;
					encyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaHeroPageVM_Dependency_7_ItemTemplate.AddComponent(generatedWidgetData);
					this._widget_3.AddChildAtIndex(encyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaHeroPageVM_Dependency_7_ItemTemplate, j);
					encyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaHeroPageVM_Dependency_7_ItemTemplate.CreateWidgets();
					encyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaHeroPageVM_Dependency_7_ItemTemplate.SetIds();
					encyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaHeroPageVM_Dependency_7_ItemTemplate.SetAttributes();
					encyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaHeroPageVM_Dependency_7_ItemTemplate.SetDataSource(encyclopediaListFilterVM);
				}
			}
		}

		// Token: 0x04000C17 RID: 3095
		private Widget _widget;

		// Token: 0x04000C18 RID: 3096
		private NavigationScopeTargeter _widget_0;

		// Token: 0x04000C19 RID: 3097
		private NavigationAutoScrollWidget _widget_1;

		// Token: 0x04000C1A RID: 3098
		private PartyHeaderToggleWidget _widget_2;

		// Token: 0x04000C1B RID: 3099
		private ListPanel _widget_2_0;

		// Token: 0x04000C1C RID: 3100
		private ImageWidget _widget_2_0_0;

		// Token: 0x04000C1D RID: 3101
		private TextWidget _widget_2_0_1;

		// Token: 0x04000C1E RID: 3102
		private ImageWidget _widget_2_0_2;

		// Token: 0x04000C1F RID: 3103
		private NavigatableListPanel _widget_3;

		// Token: 0x04000C20 RID: 3104
		private EncyclopediaFilterGroupVM _datasource_Root;

		// Token: 0x04000C21 RID: 3105
		private MBBindingList<EncyclopediaListFilterVM> _datasource_Root_Filters;
	}
}
