using System;
using System.ComponentModel;
using System.Numerics;
using TaleWorlds.CampaignSystem.ViewModelCollection.Input;
using TaleWorlds.CampaignSystem.ViewModelCollection.Party.PartyTroopManagerPopUp;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.GauntletUI.ExtraWidgets;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets;

namespace SandBox.GauntletUI.AutoGenerated0
{
	// Token: 0x02000138 RID: 312
	public class PartyScreen__TaleWorlds_CampaignSystem_ViewModelCollection_Party_PartyVM_Dependency_24_Standard_PopupCloseButton__DependendPrefab : Widget
	{
		// Token: 0x060063B7 RID: 25527 RVA: 0x0032004B File Offset: 0x0031E24B
		public PartyScreen__TaleWorlds_CampaignSystem_ViewModelCollection_Party_PartyVM_Dependency_24_Standard_PopupCloseButton__DependendPrefab(UIContext context)
			: base(context)
		{
		}

		// Token: 0x060063B8 RID: 25528 RVA: 0x00320054 File Offset: 0x0031E254
		public void CreateWidgets()
		{
			this._widget = this;
			this._widget_0 = new ButtonWidget(base.Context);
			this._widget.AddChild(this._widget_0);
			this._widget_0_0 = new TextWidget(base.Context);
			this._widget_0.AddChild(this._widget_0_0);
			this._widget_0_0_0 = new Widget(base.Context);
			this._widget_0_0.AddChild(this._widget_0_0_0);
			this._widget_0_0_0_0 = new InputKeyVisualWidget(base.Context);
			this._widget_0_0_0.AddChild(this._widget_0_0_0_0);
			this._widget_1 = new Widget(base.Context);
			this._widget.AddChild(this._widget_1);
			this._widget_1_0 = new HintWidget(base.Context);
			this._widget_1.AddChild(this._widget_1_0);
		}

		// Token: 0x060063B9 RID: 25529 RVA: 0x00320134 File Offset: 0x0031E334
		public void SetIds()
		{
			this._widget_0.Id = "ButtonWidget";
		}

		// Token: 0x060063BA RID: 25530 RVA: 0x00320148 File Offset: 0x0031E348
		public void SetAttributes()
		{
			base.WidthSizePolicy = SizePolicy.Fixed;
			base.HeightSizePolicy = SizePolicy.Fixed;
			base.SuggestedWidth = 286f;
			base.SuggestedHeight = 82f;
			base.HorizontalAlignment = HorizontalAlignment.Center;
			base.VerticalAlignment = VerticalAlignment.Top;
			this._widget_0.DoNotPassEventsToChildren = true;
			this._widget_0.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_0.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_0.IsEnabled = true;
			this._widget_0.Brush = base.Context.GetBrush("Standard.PopupCloseButton");
			this._widget_0.UpdateChildrenStates = true;
			this._widget_0_0.DoNotAcceptEvents = true;
			this._widget_0_0.WidthSizePolicy = SizePolicy.CoverChildren;
			this._widget_0_0.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_0_0.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_0_0.VerticalAlignment = VerticalAlignment.Center;
			this._widget_0_0.Brush = base.Context.GetBrush("Standard.DialogCloseButtons.ButtonText");
			this._widget_0_0_0.WidthSizePolicy = SizePolicy.CoverChildren;
			this._widget_0_0_0.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_0_0_0.HorizontalAlignment = HorizontalAlignment.Left;
			this._widget_0_0_0.VerticalAlignment = VerticalAlignment.Center;
			this._widget_0_0_0.PositionXOffset = -40f;
			this._widget_0_0_0.PositionYOffset = -1f;
			this._widget_0_0_0.IsVisible = true;
			this._widget_0_0_0_0.DoNotAcceptEvents = true;
			this._widget_0_0_0_0.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_0_0_0_0.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_0_0_0_0.SuggestedWidth = 40f;
			this._widget_0_0_0_0.SuggestedHeight = 40f;
			this._widget_1.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_1.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_1.IsDisabled = true;
			this._widget_1_0.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_1_0.HeightSizePolicy = SizePolicy.StretchToParent;
		}

		// Token: 0x060063BB RID: 25531 RVA: 0x00320314 File Offset: 0x0031E514
		public void DestroyDataSource()
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget_0.EventFire -= this.EventListenerOf_widget_0;
				this._widget_0_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_0;
				this._widget_1_0.EventFire -= this.EventListenerOf_widget_1_0;
				if (this._datasource_Root_DoneInputKey != null)
				{
					this._datasource_Root_DoneInputKey.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_DoneInputKey;
					this._datasource_Root_DoneInputKey.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_DoneInputKey;
					this._datasource_Root_DoneInputKey.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_DoneInputKey;
					this._datasource_Root_DoneInputKey.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_DoneInputKey;
					this._datasource_Root_DoneInputKey.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_DoneInputKey;
					this._datasource_Root_DoneInputKey.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_DoneInputKey;
					this._datasource_Root_DoneInputKey.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_DoneInputKey;
					this._datasource_Root_DoneInputKey.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_DoneInputKey;
					this._datasource_Root_DoneInputKey.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_DoneInputKey;
					this._widget_0_0_0_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_0_0_0;
					this._widget_0_0_0_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_0_0_0;
					this._widget_0_0_0_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_0_0_0;
					this._widget_0_0_0_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_0_0_0;
					this._widget_0_0_0_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_0_0_0;
					this._widget_0_0_0_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_0_0_0;
					this._widget_0_0_0_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_0_0_0;
					this._widget_0_0_0_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_0_0_0;
					this._widget_0_0_0_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_0_0_0;
					this._datasource_Root_DoneInputKey = null;
				}
				this._datasource_Root = null;
			}
		}

		// Token: 0x060063BC RID: 25532 RVA: 0x003206AF File Offset: 0x0031E8AF
		public void SetDataSource(PartyRecruitTroopVM dataSource)
		{
			this.RefreshDataSource_datasource_Root(dataSource);
		}

		// Token: 0x060063BD RID: 25533 RVA: 0x003206B8 File Offset: 0x0031E8B8
		private void EventListenerOf_widget_0(Widget widget, string commandName, object[] args)
		{
			if (commandName == "Click")
			{
				this._datasource_Root.ExecuteDone();
			}
		}

		// Token: 0x060063BE RID: 25534 RVA: 0x003206D2 File Offset: 0x0031E8D2
		private void EventListenerOf_widget_1_0(Widget widget, string commandName, object[] args)
		{
			commandName == "HoverBegin";
			commandName == "HoverEnd";
		}

		// Token: 0x060063BF RID: 25535 RVA: 0x003206EC File Offset: 0x0031E8EC
		private void PropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
		}

		// Token: 0x060063C0 RID: 25536 RVA: 0x003206F5 File Offset: 0x0031E8F5
		private void boolPropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
		}

		// Token: 0x060063C1 RID: 25537 RVA: 0x003206FE File Offset: 0x0031E8FE
		private void floatPropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
		}

		// Token: 0x060063C2 RID: 25538 RVA: 0x00320707 File Offset: 0x0031E907
		private void Vec2PropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
		}

		// Token: 0x060063C3 RID: 25539 RVA: 0x00320710 File Offset: 0x0031E910
		private void Vector2PropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
		}

		// Token: 0x060063C4 RID: 25540 RVA: 0x00320719 File Offset: 0x0031E919
		private void doublePropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
		}

		// Token: 0x060063C5 RID: 25541 RVA: 0x00320722 File Offset: 0x0031E922
		private void intPropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
		}

		// Token: 0x060063C6 RID: 25542 RVA: 0x0032072B File Offset: 0x0031E92B
		private void uintPropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
		}

		// Token: 0x060063C7 RID: 25543 RVA: 0x00320734 File Offset: 0x0031E934
		private void ColorPropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
		}

		// Token: 0x060063C8 RID: 25544 RVA: 0x0032073D File Offset: 0x0031E93D
		private void HandleWidgetPropertyChangeOf_widget_0_0(string propertyName)
		{
			if (propertyName == "Text")
			{
				this._datasource_Root.DoneLbl = this._widget_0_0.Text;
				return;
			}
		}

		// Token: 0x060063C9 RID: 25545 RVA: 0x00320763 File Offset: 0x0031E963
		private void PropertyChangedListenerOf_widget_0_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_0_0(propertyName);
		}

		// Token: 0x060063CA RID: 25546 RVA: 0x0032076C File Offset: 0x0031E96C
		private void boolPropertyChangedListenerOf_widget_0_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_0_0(propertyName);
		}

		// Token: 0x060063CB RID: 25547 RVA: 0x00320775 File Offset: 0x0031E975
		private void floatPropertyChangedListenerOf_widget_0_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_0_0(propertyName);
		}

		// Token: 0x060063CC RID: 25548 RVA: 0x0032077E File Offset: 0x0031E97E
		private void Vec2PropertyChangedListenerOf_widget_0_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_0_0(propertyName);
		}

		// Token: 0x060063CD RID: 25549 RVA: 0x00320787 File Offset: 0x0031E987
		private void Vector2PropertyChangedListenerOf_widget_0_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_0_0(propertyName);
		}

		// Token: 0x060063CE RID: 25550 RVA: 0x00320790 File Offset: 0x0031E990
		private void doublePropertyChangedListenerOf_widget_0_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_0_0(propertyName);
		}

		// Token: 0x060063CF RID: 25551 RVA: 0x00320799 File Offset: 0x0031E999
		private void intPropertyChangedListenerOf_widget_0_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_0_0(propertyName);
		}

		// Token: 0x060063D0 RID: 25552 RVA: 0x003207A2 File Offset: 0x0031E9A2
		private void uintPropertyChangedListenerOf_widget_0_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_0_0(propertyName);
		}

		// Token: 0x060063D1 RID: 25553 RVA: 0x003207AB File Offset: 0x0031E9AB
		private void ColorPropertyChangedListenerOf_widget_0_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_0_0(propertyName);
		}

		// Token: 0x060063D2 RID: 25554 RVA: 0x003207B4 File Offset: 0x0031E9B4
		private void HandleWidgetPropertyChangeOf_widget_0_0_0_0(string propertyName)
		{
			if (propertyName == "KeyID")
			{
				this._datasource_Root_DoneInputKey.KeyID = this._widget_0_0_0_0.KeyID;
				return;
			}
			if (propertyName == "IsVisible")
			{
				this._datasource_Root_DoneInputKey.IsVisible = this._widget_0_0_0_0.IsVisible;
				return;
			}
		}

		// Token: 0x060063D3 RID: 25555 RVA: 0x00320809 File Offset: 0x0031EA09
		private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060063D4 RID: 25556 RVA: 0x00320817 File Offset: 0x0031EA17
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060063D5 RID: 25557 RVA: 0x00320826 File Offset: 0x0031EA26
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060063D6 RID: 25558 RVA: 0x00320835 File Offset: 0x0031EA35
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060063D7 RID: 25559 RVA: 0x00320844 File Offset: 0x0031EA44
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060063D8 RID: 25560 RVA: 0x00320853 File Offset: 0x0031EA53
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060063D9 RID: 25561 RVA: 0x00320862 File Offset: 0x0031EA62
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060063DA RID: 25562 RVA: 0x00320871 File Offset: 0x0031EA71
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060063DB RID: 25563 RVA: 0x00320880 File Offset: 0x0031EA80
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060063DC RID: 25564 RVA: 0x00320890 File Offset: 0x0031EA90
		private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
		{
			if (propertyName == "DoneInputKey")
			{
				this.RefreshDataSource_datasource_Root_DoneInputKey(this._datasource_Root.DoneInputKey);
				return;
			}
			if (propertyName == "DoneLbl")
			{
				this._widget_0_0.Text = this._datasource_Root.DoneLbl;
				return;
			}
		}

		// Token: 0x060063DD RID: 25565 RVA: 0x003208E0 File Offset: 0x0031EAE0
		private void ViewModelPropertyChangedListenerOf_datasource_Root_DoneInputKey(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_DoneInputKey(e.PropertyName);
		}

		// Token: 0x060063DE RID: 25566 RVA: 0x003208EE File Offset: 0x0031EAEE
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_DoneInputKey(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_DoneInputKey(e.PropertyName);
		}

		// Token: 0x060063DF RID: 25567 RVA: 0x003208FD File Offset: 0x0031EAFD
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_DoneInputKey(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_DoneInputKey(e.PropertyName);
		}

		// Token: 0x060063E0 RID: 25568 RVA: 0x0032090C File Offset: 0x0031EB0C
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_DoneInputKey(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_DoneInputKey(e.PropertyName);
		}

		// Token: 0x060063E1 RID: 25569 RVA: 0x0032091B File Offset: 0x0031EB1B
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_DoneInputKey(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_DoneInputKey(e.PropertyName);
		}

		// Token: 0x060063E2 RID: 25570 RVA: 0x0032092A File Offset: 0x0031EB2A
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_DoneInputKey(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_DoneInputKey(e.PropertyName);
		}

		// Token: 0x060063E3 RID: 25571 RVA: 0x00320939 File Offset: 0x0031EB39
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_DoneInputKey(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_DoneInputKey(e.PropertyName);
		}

		// Token: 0x060063E4 RID: 25572 RVA: 0x00320948 File Offset: 0x0031EB48
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_DoneInputKey(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_DoneInputKey(e.PropertyName);
		}

		// Token: 0x060063E5 RID: 25573 RVA: 0x00320957 File Offset: 0x0031EB57
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_DoneInputKey(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_DoneInputKey(e.PropertyName);
		}

		// Token: 0x060063E6 RID: 25574 RVA: 0x00320968 File Offset: 0x0031EB68
		private void HandleViewModelPropertyChangeOf_datasource_Root_DoneInputKey(string propertyName)
		{
			if (propertyName == "KeyID")
			{
				this._widget_0_0_0_0.KeyID = this._datasource_Root_DoneInputKey.KeyID;
				return;
			}
			if (propertyName == "IsVisible")
			{
				this._widget_0_0_0_0.IsVisible = this._datasource_Root_DoneInputKey.IsVisible;
				return;
			}
		}

		// Token: 0x060063E7 RID: 25575 RVA: 0x003209C0 File Offset: 0x0031EBC0
		private void RefreshDataSource_datasource_Root(PartyRecruitTroopVM newDataSource)
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget_0.EventFire -= this.EventListenerOf_widget_0;
				this._widget_0_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_0;
				this._widget_1_0.EventFire -= this.EventListenerOf_widget_1_0;
				if (this._datasource_Root_DoneInputKey != null)
				{
					this._datasource_Root_DoneInputKey.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_DoneInputKey;
					this._datasource_Root_DoneInputKey.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_DoneInputKey;
					this._datasource_Root_DoneInputKey.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_DoneInputKey;
					this._datasource_Root_DoneInputKey.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_DoneInputKey;
					this._datasource_Root_DoneInputKey.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_DoneInputKey;
					this._datasource_Root_DoneInputKey.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_DoneInputKey;
					this._datasource_Root_DoneInputKey.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_DoneInputKey;
					this._datasource_Root_DoneInputKey.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_DoneInputKey;
					this._datasource_Root_DoneInputKey.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_DoneInputKey;
					this._widget_0_0_0_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_0_0_0;
					this._widget_0_0_0_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_0_0_0;
					this._widget_0_0_0_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_0_0_0;
					this._widget_0_0_0_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_0_0_0;
					this._widget_0_0_0_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_0_0_0;
					this._widget_0_0_0_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_0_0_0;
					this._widget_0_0_0_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_0_0_0;
					this._widget_0_0_0_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_0_0_0;
					this._widget_0_0_0_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_0_0_0;
					this._datasource_Root_DoneInputKey = null;
				}
				this._datasource_Root = null;
			}
			this._datasource_Root = newDataSource;
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget_0.EventFire += this.EventListenerOf_widget_0;
				this._widget_0_0.Text = this._datasource_Root.DoneLbl;
				this._widget_0_0.PropertyChanged += this.PropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.intPropertyChanged += this.intPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_0_0;
				this._widget_1_0.EventFire += this.EventListenerOf_widget_1_0;
				this._datasource_Root_DoneInputKey = this._datasource_Root.DoneInputKey;
				if (this._datasource_Root_DoneInputKey != null)
				{
					this._datasource_Root_DoneInputKey.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root_DoneInputKey;
					this._datasource_Root_DoneInputKey.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_DoneInputKey;
					this._datasource_Root_DoneInputKey.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_DoneInputKey;
					this._datasource_Root_DoneInputKey.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_DoneInputKey;
					this._datasource_Root_DoneInputKey.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_DoneInputKey;
					this._datasource_Root_DoneInputKey.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_DoneInputKey;
					this._datasource_Root_DoneInputKey.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_DoneInputKey;
					this._datasource_Root_DoneInputKey.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_DoneInputKey;
					this._datasource_Root_DoneInputKey.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_DoneInputKey;
					this._widget_0_0_0_0.KeyID = this._datasource_Root_DoneInputKey.KeyID;
					this._widget_0_0_0_0.IsVisible = this._datasource_Root_DoneInputKey.IsVisible;
					this._widget_0_0_0_0.PropertyChanged += this.PropertyChangedListenerOf_widget_0_0_0_0;
					this._widget_0_0_0_0.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_0_0_0_0;
					this._widget_0_0_0_0.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_0_0_0_0;
					this._widget_0_0_0_0.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_0_0_0_0;
					this._widget_0_0_0_0.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_0_0_0_0;
					this._widget_0_0_0_0.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_0_0_0_0;
					this._widget_0_0_0_0.intPropertyChanged += this.intPropertyChangedListenerOf_widget_0_0_0_0;
					this._widget_0_0_0_0.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_0_0_0_0;
					this._widget_0_0_0_0.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_0_0_0_0;
				}
			}
		}

		// Token: 0x060063E8 RID: 25576 RVA: 0x00321138 File Offset: 0x0031F338
		private void RefreshDataSource_datasource_Root_DoneInputKey(InputKeyItemVM newDataSource)
		{
			if (this._datasource_Root_DoneInputKey != null)
			{
				this._datasource_Root_DoneInputKey.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_DoneInputKey;
				this._datasource_Root_DoneInputKey.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_DoneInputKey;
				this._datasource_Root_DoneInputKey.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_DoneInputKey;
				this._datasource_Root_DoneInputKey.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_DoneInputKey;
				this._datasource_Root_DoneInputKey.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_DoneInputKey;
				this._datasource_Root_DoneInputKey.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_DoneInputKey;
				this._datasource_Root_DoneInputKey.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_DoneInputKey;
				this._datasource_Root_DoneInputKey.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_DoneInputKey;
				this._datasource_Root_DoneInputKey.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_DoneInputKey;
				this._widget_0_0_0_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_0_0_0;
				this._widget_0_0_0_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_0_0_0;
				this._widget_0_0_0_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_0_0_0;
				this._widget_0_0_0_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_0_0_0;
				this._widget_0_0_0_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_0_0_0;
				this._widget_0_0_0_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_0_0_0;
				this._widget_0_0_0_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_0_0_0;
				this._widget_0_0_0_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_0_0_0;
				this._widget_0_0_0_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_0_0_0;
				this._datasource_Root_DoneInputKey = null;
			}
			this._datasource_Root_DoneInputKey = newDataSource;
			this._datasource_Root_DoneInputKey = this._datasource_Root.DoneInputKey;
			if (this._datasource_Root_DoneInputKey != null)
			{
				this._datasource_Root_DoneInputKey.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root_DoneInputKey;
				this._datasource_Root_DoneInputKey.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_DoneInputKey;
				this._datasource_Root_DoneInputKey.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_DoneInputKey;
				this._datasource_Root_DoneInputKey.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_DoneInputKey;
				this._datasource_Root_DoneInputKey.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_DoneInputKey;
				this._datasource_Root_DoneInputKey.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_DoneInputKey;
				this._datasource_Root_DoneInputKey.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_DoneInputKey;
				this._datasource_Root_DoneInputKey.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_DoneInputKey;
				this._datasource_Root_DoneInputKey.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_DoneInputKey;
				this._widget_0_0_0_0.KeyID = this._datasource_Root_DoneInputKey.KeyID;
				this._widget_0_0_0_0.IsVisible = this._datasource_Root_DoneInputKey.IsVisible;
				this._widget_0_0_0_0.PropertyChanged += this.PropertyChangedListenerOf_widget_0_0_0_0;
				this._widget_0_0_0_0.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_0_0_0_0;
				this._widget_0_0_0_0.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_0_0_0_0;
				this._widget_0_0_0_0.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_0_0_0_0;
				this._widget_0_0_0_0.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_0_0_0_0;
				this._widget_0_0_0_0.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_0_0_0_0;
				this._widget_0_0_0_0.intPropertyChanged += this.intPropertyChangedListenerOf_widget_0_0_0_0;
				this._widget_0_0_0_0.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_0_0_0_0;
				this._widget_0_0_0_0.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_0_0_0_0;
			}
		}

		// Token: 0x0400140F RID: 5135
		private Widget _widget;

		// Token: 0x04001410 RID: 5136
		private ButtonWidget _widget_0;

		// Token: 0x04001411 RID: 5137
		private TextWidget _widget_0_0;

		// Token: 0x04001412 RID: 5138
		private Widget _widget_0_0_0;

		// Token: 0x04001413 RID: 5139
		private InputKeyVisualWidget _widget_0_0_0_0;

		// Token: 0x04001414 RID: 5140
		private Widget _widget_1;

		// Token: 0x04001415 RID: 5141
		private HintWidget _widget_1_0;

		// Token: 0x04001416 RID: 5142
		private PartyRecruitTroopVM _datasource_Root;

		// Token: 0x04001417 RID: 5143
		private InputKeyItemVM _datasource_Root_DoneInputKey;
	}
}
