using System;
using System.Collections.Generic;
using System.Linq;
using System.Xml;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.ObjectSystem;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.Core
{
	// Token: 0x0200002C RID: 44
	public class Equipment
	{
		// Token: 0x060002B9 RID: 697 RVA: 0x0000C04F File Offset: 0x0000A24F
		internal static void AutoGeneratedStaticCollectObjectsEquipment(object o, List<object> collectedObjects)
		{
			((Equipment)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x060002BA RID: 698 RVA: 0x0000C05D File Offset: 0x0000A25D
		protected virtual void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			collectedObjects.Add(this._itemSlots);
		}

		// Token: 0x060002BB RID: 699 RVA: 0x0000C06B File Offset: 0x0000A26B
		internal static object AutoGeneratedGetMemberValue_equipmentType(object o)
		{
			return ((Equipment)o)._equipmentType;
		}

		// Token: 0x060002BC RID: 700 RVA: 0x0000C07D File Offset: 0x0000A27D
		internal static object AutoGeneratedGetMemberValue_itemSlots(object o)
		{
			return ((Equipment)o)._itemSlots;
		}

		// Token: 0x170000CC RID: 204
		// (get) Token: 0x060002BD RID: 701 RVA: 0x0000C08A File Offset: 0x0000A28A
		public Equipment.EquipmentType ItemEquipmentType
		{
			get
			{
				return this._equipmentType;
			}
		}

		// Token: 0x170000CD RID: 205
		// (get) Token: 0x060002BE RID: 702 RVA: 0x0000C092 File Offset: 0x0000A292
		public bool IsCivilian
		{
			get
			{
				return this._equipmentType == Equipment.EquipmentType.Civilian;
			}
		}

		// Token: 0x170000CE RID: 206
		// (get) Token: 0x060002BF RID: 703 RVA: 0x0000C09D File Offset: 0x0000A29D
		public bool IsBattle
		{
			get
			{
				return this._equipmentType == Equipment.EquipmentType.Battle;
			}
		}

		// Token: 0x170000CF RID: 207
		// (get) Token: 0x060002C0 RID: 704 RVA: 0x0000C0A8 File Offset: 0x0000A2A8
		public bool IsStealth
		{
			get
			{
				return this._equipmentType == Equipment.EquipmentType.Stealth;
			}
		}

		// Token: 0x060002C1 RID: 705 RVA: 0x0000C0B3 File Offset: 0x0000A2B3
		public Equipment()
		{
			this._itemSlots = new EquipmentElement[12];
			this._equipmentType = Equipment.EquipmentType.Invalid;
		}

		// Token: 0x060002C2 RID: 706 RVA: 0x0000C0CF File Offset: 0x0000A2CF
		public Equipment(Equipment.EquipmentType equipmentType)
			: this()
		{
			this._itemSlots = new EquipmentElement[12];
			this._equipmentType = equipmentType;
		}

		// Token: 0x060002C3 RID: 707 RVA: 0x0000C0EC File Offset: 0x0000A2EC
		public Equipment(Equipment equipment)
		{
			this._itemSlots = new EquipmentElement[12];
			for (int i = 0; i < 12; i++)
			{
				this._itemSlots[i] = new EquipmentElement(equipment[i]);
			}
			this._equipmentType = equipment._equipmentType;
		}

		// Token: 0x170000D0 RID: 208
		public EquipmentElement this[int index]
		{
			get
			{
				return this._itemSlots[index];
			}
			set
			{
				Equipment.IsItemFitsToSlot((EquipmentIndex)index, value.Item);
				this._itemSlots[index] = value;
			}
		}

		// Token: 0x170000D1 RID: 209
		public EquipmentElement this[EquipmentIndex index]
		{
			get
			{
				return this._itemSlots[(int)index];
			}
			set
			{
				this[(int)index] = value;
			}
		}

		// Token: 0x170000D2 RID: 210
		// (get) Token: 0x060002C8 RID: 712 RVA: 0x0000C180 File Offset: 0x0000A380
		public EquipmentElement Horse
		{
			get
			{
				return this._itemSlots[10];
			}
		}

		// Token: 0x060002C9 RID: 713 RVA: 0x0000C18F File Offset: 0x0000A38F
		private void SetItem(int index, EquipmentElement element)
		{
			this[index] = element;
		}

		// Token: 0x060002CA RID: 714 RVA: 0x0000C19C File Offset: 0x0000A39C
		public Equipment Clone(bool cloneWithoutWeapons = false)
		{
			Equipment equipment = new Equipment(this._equipmentType);
			for (int i = 0; i < 12; i++)
			{
				bool flag = cloneWithoutWeapons && i >= 0 && i < 5;
				equipment.SetItem(i, flag ? EquipmentElement.Invalid : this[i]);
			}
			return equipment;
		}

		// Token: 0x060002CB RID: 715 RVA: 0x0000C1EC File Offset: 0x0000A3EC
		public void FillFrom(Equipment sourceEquipment, bool useSourceEquipmentType = true)
		{
			if (useSourceEquipmentType)
			{
				this._equipmentType = sourceEquipment._equipmentType;
			}
			for (int i = 0; i < 12; i++)
			{
				this[i] = sourceEquipment[i];
			}
		}

		// Token: 0x060002CC RID: 716 RVA: 0x0000C224 File Offset: 0x0000A424
		public void Deserialize(MBObjectManager objectManager, XmlNode node)
		{
			foreach (object obj in node.ChildNodes)
			{
				XmlNode xmlNode = (XmlNode)obj;
				this.DeserializeNode(objectManager, xmlNode);
			}
		}

		// Token: 0x060002CD RID: 717 RVA: 0x0000C280 File Offset: 0x0000A480
		public void DeserializeNode(MBObjectManager objectManager, XmlNode node)
		{
			if (node.NodeType == XmlNodeType.Comment)
			{
				return;
			}
			XmlAttributeCollection attributes = node.Attributes;
			XmlAttribute xmlAttribute = attributes["id"];
			XmlAttribute xmlAttribute2 = attributes["slot"];
			string text = (xmlAttribute.Value.Contains(".") ? xmlAttribute.Value.Split(new char[] { '.' })[1] : xmlAttribute.Value);
			EquipmentIndex equipmentIndexFromOldEquipmentIndexName = Equipment.GetEquipmentIndexFromOldEquipmentIndexName(xmlAttribute2.Value);
			ItemObject @object = MBObjectManager.Instance.GetObject<ItemObject>(text);
			if (Equipment.IsItemFitsToSlot(equipmentIndexFromOldEquipmentIndexName, @object))
			{
				this[equipmentIndexFromOldEquipmentIndexName] = new EquipmentElement(@object, null, null, false);
				return;
			}
			Debug.FailedAssert(((@object == null) ? TextObject.GetEmpty() : @object.Name) + " does not fit to slot " + equipmentIndexFromOldEquipmentIndexName, "C:\\BuildAgent\\work\\mb3\\Source\\Bannerlord\\TaleWorlds.Core\\Equipment.cs", "DeserializeNode", 171);
		}

		// Token: 0x060002CE RID: 718 RVA: 0x0000C354 File Offset: 0x0000A554
		public static EquipmentIndex GetEquipmentIndexFromOldEquipmentIndexName(string oldEquipmentIndexName)
		{
			string text;
			if (!(oldEquipmentIndexName == "Item0"))
			{
				if (!(oldEquipmentIndexName == "Item1"))
				{
					if (!(oldEquipmentIndexName == "Item2"))
					{
						if (!(oldEquipmentIndexName == "Item3"))
						{
							if (!(oldEquipmentIndexName == "Item4"))
							{
								text = oldEquipmentIndexName;
							}
							else
							{
								text = "ExtraWeaponSlot";
							}
						}
						else
						{
							text = "Weapon3";
						}
					}
					else
					{
						text = "Weapon2";
					}
				}
				else
				{
					text = "Weapon1";
				}
			}
			else
			{
				text = "Weapon0";
			}
			return (EquipmentIndex)Enum.Parse(typeof(EquipmentIndex), text);
		}

		// Token: 0x060002CF RID: 719 RVA: 0x0000C3E3 File Offset: 0x0000A5E3
		public bool IsEmpty()
		{
			return this._itemSlots.All<EquipmentElement>((EquipmentElement itemRosterElement) => itemRosterElement.Item == null);
		}

		// Token: 0x060002D0 RID: 720 RVA: 0x0000C410 File Offset: 0x0000A610
		public float GetTotalWeightOfArmor(bool forHuman)
		{
			float num = 0f;
			for (EquipmentIndex equipmentIndex = (forHuman ? EquipmentIndex.NumAllWeaponSlots : EquipmentIndex.HorseHarness); equipmentIndex < (forHuman ? EquipmentIndex.ArmorItemEndSlot : EquipmentIndex.NumEquipmentSetSlots); equipmentIndex++)
			{
				EquipmentElement equipmentElement = this[equipmentIndex];
				if (!equipmentElement.IsEmpty)
				{
					num += equipmentElement.GetEquipmentElementWeight();
				}
			}
			return num;
		}

		// Token: 0x060002D1 RID: 721 RVA: 0x0000C45C File Offset: 0x0000A65C
		public float GetTotalWeightOfWeapons()
		{
			float num = 0f;
			for (EquipmentIndex equipmentIndex = EquipmentIndex.WeaponItemBeginSlot; equipmentIndex < EquipmentIndex.NumAllWeaponSlots; equipmentIndex++)
			{
				EquipmentElement equipmentElement = this[equipmentIndex];
				if (!equipmentElement.IsEmpty)
				{
					num += equipmentElement.GetEquipmentElementWeight();
				}
			}
			return num;
		}

		// Token: 0x060002D2 RID: 722 RVA: 0x0000C498 File Offset: 0x0000A698
		public float GetHeadArmorSum()
		{
			float num = 0f;
			for (EquipmentIndex equipmentIndex = EquipmentIndex.NumAllWeaponSlots; equipmentIndex < EquipmentIndex.ArmorItemEndSlot; equipmentIndex++)
			{
				EquipmentElement equipmentElement = this[equipmentIndex];
				if (equipmentElement.Item != null)
				{
					num += (float)equipmentElement.GetModifiedHeadArmor();
				}
			}
			return num;
		}

		// Token: 0x060002D3 RID: 723 RVA: 0x0000C4D8 File Offset: 0x0000A6D8
		public float GetHumanBodyArmorSum()
		{
			float num = 0f;
			for (EquipmentIndex equipmentIndex = EquipmentIndex.NumAllWeaponSlots; equipmentIndex < EquipmentIndex.ArmorItemEndSlot; equipmentIndex++)
			{
				EquipmentElement equipmentElement = this[equipmentIndex];
				if (equipmentElement.Item != null)
				{
					num += (float)equipmentElement.GetModifiedBodyArmor();
				}
			}
			return num;
		}

		// Token: 0x060002D4 RID: 724 RVA: 0x0000C518 File Offset: 0x0000A718
		public float GetLegArmorSum()
		{
			float num = 0f;
			for (EquipmentIndex equipmentIndex = EquipmentIndex.NumAllWeaponSlots; equipmentIndex < EquipmentIndex.ArmorItemEndSlot; equipmentIndex++)
			{
				EquipmentElement equipmentElement = this[equipmentIndex];
				if (equipmentElement.Item != null)
				{
					num += (float)equipmentElement.GetModifiedLegArmor();
				}
			}
			return num;
		}

		// Token: 0x060002D5 RID: 725 RVA: 0x0000C558 File Offset: 0x0000A758
		public float GetArmArmorSum()
		{
			float num = 0f;
			for (EquipmentIndex equipmentIndex = EquipmentIndex.NumAllWeaponSlots; equipmentIndex < EquipmentIndex.ArmorItemEndSlot; equipmentIndex++)
			{
				EquipmentElement equipmentElement = this[equipmentIndex];
				if (equipmentElement.Item != null)
				{
					num += (float)equipmentElement.GetModifiedArmArmor();
				}
			}
			return num;
		}

		// Token: 0x060002D6 RID: 726 RVA: 0x0000C598 File Offset: 0x0000A798
		public float GetHorseArmorSum()
		{
			float num = 0f;
			EquipmentIndex equipmentIndex = EquipmentIndex.HorseHarness;
			EquipmentElement equipmentElement = this[equipmentIndex];
			if (equipmentElement.Item != null)
			{
				num += (float)equipmentElement.GetModifiedMountBodyArmor();
			}
			return num;
		}

		// Token: 0x170000D3 RID: 211
		// (get) Token: 0x060002D7 RID: 727 RVA: 0x0000C5CC File Offset: 0x0000A7CC
		public ArmorComponent.HairCoverTypes HairCoverType
		{
			get
			{
				ArmorComponent.HairCoverTypes hairCoverTypes = ArmorComponent.HairCoverTypes.None;
				ItemObject itemObject = this[EquipmentIndex.NumAllWeaponSlots].CosmeticItem ?? this[EquipmentIndex.NumAllWeaponSlots].Item;
				if (itemObject != null)
				{
					ArmorComponent armorComponent = itemObject.ArmorComponent;
					hairCoverTypes = ((armorComponent != null) ? armorComponent.HairCoverType : ArmorComponent.HairCoverTypes.None);
				}
				else if (this[EquipmentIndex.Body].Item == null)
				{
					hairCoverTypes = ArmorComponent.HairCoverTypes.Type4;
				}
				return hairCoverTypes;
			}
		}

		// Token: 0x170000D4 RID: 212
		// (get) Token: 0x060002D8 RID: 728 RVA: 0x0000C628 File Offset: 0x0000A828
		public ArmorComponent.BeardCoverTypes BeardCoverType
		{
			get
			{
				ItemObject itemObject = this[EquipmentIndex.NumAllWeaponSlots].CosmeticItem ?? this[EquipmentIndex.NumAllWeaponSlots].Item;
				ArmorComponent.BeardCoverTypes? beardCoverTypes;
				if (itemObject == null)
				{
					beardCoverTypes = null;
				}
				else
				{
					ArmorComponent armorComponent = itemObject.ArmorComponent;
					beardCoverTypes = ((armorComponent != null) ? new ArmorComponent.BeardCoverTypes?(armorComponent.BeardCoverType) : null);
				}
				ArmorComponent.BeardCoverTypes? beardCoverTypes2 = beardCoverTypes;
				if (beardCoverTypes2 == null)
				{
					return ArmorComponent.BeardCoverTypes.None;
				}
				return beardCoverTypes2.GetValueOrDefault();
			}
		}

		// Token: 0x170000D5 RID: 213
		// (get) Token: 0x060002D9 RID: 729 RVA: 0x0000C694 File Offset: 0x0000A894
		public ArmorComponent.HorseHarnessCoverTypes ManeCoverType
		{
			get
			{
				ItemObject itemObject = this[EquipmentIndex.HorseHarness].CosmeticItem ?? this[EquipmentIndex.HorseHarness].Item;
				ArmorComponent.HorseHarnessCoverTypes? horseHarnessCoverTypes;
				if (itemObject == null)
				{
					horseHarnessCoverTypes = null;
				}
				else
				{
					ArmorComponent armorComponent = itemObject.ArmorComponent;
					horseHarnessCoverTypes = ((armorComponent != null) ? new ArmorComponent.HorseHarnessCoverTypes?(armorComponent.ManeCoverType) : null);
				}
				ArmorComponent.HorseHarnessCoverTypes? horseHarnessCoverTypes2 = horseHarnessCoverTypes;
				if (horseHarnessCoverTypes2 == null)
				{
					return ArmorComponent.HorseHarnessCoverTypes.None;
				}
				return horseHarnessCoverTypes2.GetValueOrDefault();
			}
		}

		// Token: 0x170000D6 RID: 214
		// (get) Token: 0x060002DA RID: 730 RVA: 0x0000C704 File Offset: 0x0000A904
		public string ReinsMeshName
		{
			get
			{
				ItemObject item = this[EquipmentIndex.HorseHarness].Item;
				string text;
				if (item == null)
				{
					text = null;
				}
				else
				{
					ArmorComponent armorComponent = item.ArmorComponent;
					text = ((armorComponent != null) ? armorComponent.ReinsMesh : null);
				}
				return text ?? "";
			}
		}

		// Token: 0x170000D7 RID: 215
		// (get) Token: 0x060002DB RID: 731 RVA: 0x0000C742 File Offset: 0x0000A942
		public bool EarsAreHidden
		{
			get
			{
				return this.HairCoverType != ArmorComponent.HairCoverTypes.None && this.HairCoverType != ArmorComponent.HairCoverTypes.Type1 && this.HairCoverType != ArmorComponent.HairCoverTypes.Type4;
			}
		}

		// Token: 0x170000D8 RID: 216
		// (get) Token: 0x060002DC RID: 732 RVA: 0x0000C763 File Offset: 0x0000A963
		public bool MouthIsHidden
		{
			get
			{
				return this.BeardCoverType == ArmorComponent.BeardCoverTypes.All;
			}
		}

		// Token: 0x170000D9 RID: 217
		// (get) Token: 0x060002DD RID: 733 RVA: 0x0000C770 File Offset: 0x0000A970
		public ArmorComponent.BodyMeshTypes BodyMeshType
		{
			get
			{
				ItemObject item = this[EquipmentIndex.Body].Item;
				ArmorComponent.BodyMeshTypes? bodyMeshTypes;
				if (item == null)
				{
					bodyMeshTypes = null;
				}
				else
				{
					ArmorComponent armorComponent = item.ArmorComponent;
					bodyMeshTypes = ((armorComponent != null) ? new ArmorComponent.BodyMeshTypes?(armorComponent.BodyMeshType) : null);
				}
				ArmorComponent.BodyMeshTypes? bodyMeshTypes2 = bodyMeshTypes;
				if (bodyMeshTypes2 == null)
				{
					return ArmorComponent.BodyMeshTypes.Normal;
				}
				return bodyMeshTypes2.GetValueOrDefault();
			}
		}

		// Token: 0x170000DA RID: 218
		// (get) Token: 0x060002DE RID: 734 RVA: 0x0000C7CC File Offset: 0x0000A9CC
		public ArmorComponent.BodyDeformTypes BodyDeformType
		{
			get
			{
				ItemObject item = this[EquipmentIndex.Body].Item;
				ArmorComponent.BodyDeformTypes? bodyDeformTypes;
				if (item == null)
				{
					bodyDeformTypes = null;
				}
				else
				{
					ArmorComponent armorComponent = item.ArmorComponent;
					bodyDeformTypes = ((armorComponent != null) ? new ArmorComponent.BodyDeformTypes?(armorComponent.BodyDeformType) : null);
				}
				ArmorComponent.BodyDeformTypes? bodyDeformTypes2 = bodyDeformTypes;
				if (bodyDeformTypes2 == null)
				{
					return ArmorComponent.BodyDeformTypes.Medium;
				}
				return bodyDeformTypes2.GetValueOrDefault();
			}
		}

		// Token: 0x060002DF RID: 735 RVA: 0x0000C828 File Offset: 0x0000AA28
		public Equipment.UnderwearTypes GetUnderwearType(bool isFemale)
		{
			ItemObject item = this[EquipmentIndex.Body].Item;
			Equipment.UnderwearTypes underwearTypes;
			if (item == null)
			{
				underwearTypes = Equipment.UnderwearTypes.FullUnderwear;
			}
			else if (isFemale && item.DoesNotHideChest)
			{
				underwearTypes = Equipment.UnderwearTypes.OnlyTop;
			}
			else
			{
				underwearTypes = Equipment.UnderwearTypes.NoUnderwear;
			}
			return underwearTypes;
		}

		// Token: 0x060002E0 RID: 736 RVA: 0x0000C860 File Offset: 0x0000AA60
		public bool HasWeapon()
		{
			for (int i = 0; i < 5; i++)
			{
				EquipmentElement equipmentElement = this._itemSlots[i];
				if (!equipmentElement.IsEmpty && equipmentElement.Item.ItemType != ItemObject.ItemTypeEnum.Invalid && equipmentElement.Item.PrimaryWeapon.WeaponFlags.HasAnyFlag(WeaponFlags.WeaponMask))
				{
					return true;
				}
			}
			return false;
		}

		// Token: 0x060002E1 RID: 737 RVA: 0x0000C8BC File Offset: 0x0000AABC
		public bool HasWeaponOfClass(WeaponClass weaponClass)
		{
			for (int i = 0; i < 5; i++)
			{
				EquipmentElement equipmentElement = this._itemSlots[i];
				if (!equipmentElement.IsEmpty && equipmentElement.Item.PrimaryWeapon.WeaponClass == weaponClass)
				{
					return true;
				}
			}
			return false;
		}

		// Token: 0x060002E2 RID: 738 RVA: 0x0000C904 File Offset: 0x0000AB04
		public static Equipment CreateFromEquipmentCode(string equipmentCode)
		{
			Equipment equipment = new Equipment();
			for (int i = 0; i < 12; i++)
			{
				equipment[i] = default(EquipmentElement);
			}
			string[] array = equipmentCode.Split(new char[] { '+' }, StringSplitOptions.RemoveEmptyEntries);
			for (int j = 0; j < array.Length; j++)
			{
				string[] array2 = array[j].Split(new char[] { '-' }, StringSplitOptions.RemoveEmptyEntries);
				int num = Convert.ToInt32(array2[0]);
				string text = array2[1];
				if (text != "@null")
				{
					ItemObject @object = MBObjectManager.Instance.GetObject<ItemObject>(text);
					string text2 = array2[2];
					ItemModifier itemModifier = null;
					if (text2 != "@null")
					{
						itemModifier = MBObjectManager.Instance.GetObject<ItemModifier>(text2);
					}
					EquipmentElement equipmentElement = new EquipmentElement(@object, itemModifier, null, false);
					equipment[num] = equipmentElement;
				}
			}
			return equipment;
		}

		// Token: 0x060002E3 RID: 739 RVA: 0x0000C9E0 File Offset: 0x0000ABE0
		public string CalculateEquipmentCode()
		{
			MBStringBuilder mbstringBuilder = default(MBStringBuilder);
			mbstringBuilder.Initialize(16, "CalculateEquipmentCode");
			for (int i = 0; i < 12; i++)
			{
				EquipmentElement equipmentElement = this[i];
				string text = ((equipmentElement.Item != null) ? equipmentElement.Item.StringId : "@null");
				string text2 = ((equipmentElement.ItemModifier != null) ? equipmentElement.ItemModifier.StringId : "@null");
				if (string.IsNullOrEmpty(text))
				{
					text = "@null";
				}
				if (string.IsNullOrEmpty(text2))
				{
					text2 = "@null";
				}
				mbstringBuilder.Append('+');
				mbstringBuilder.Append(i);
				mbstringBuilder.Append('-');
				mbstringBuilder.Append<string>(text);
				mbstringBuilder.Append('-');
				mbstringBuilder.Append<string>(text2);
			}
			return mbstringBuilder.ToStringAndRelease();
		}

		// Token: 0x060002E4 RID: 740 RVA: 0x0000CAB8 File Offset: 0x0000ACB8
		public void AddEquipmentToSlotWithoutAgent(EquipmentIndex equipmentIndex, EquipmentElement itemRosterElement)
		{
			this[equipmentIndex] = itemRosterElement;
		}

		// Token: 0x060002E5 RID: 741 RVA: 0x0000CAC2 File Offset: 0x0000ACC2
		public EquipmentElement GetEquipmentFromSlot(EquipmentIndex equipmentIndex)
		{
			return this[equipmentIndex];
		}

		// Token: 0x060002E6 RID: 742 RVA: 0x0000CACC File Offset: 0x0000ACCC
		public static bool IsItemFitsToSlot(EquipmentIndex slotIndex, ItemObject item)
		{
			bool flag = false;
			if (item == null)
			{
				flag = true;
			}
			else
			{
				switch (item.ItemType)
				{
				case ItemObject.ItemTypeEnum.Invalid:
					flag = false;
					break;
				case ItemObject.ItemTypeEnum.Horse:
					flag = slotIndex == EquipmentIndex.ArmorItemEndSlot;
					break;
				case ItemObject.ItemTypeEnum.OneHandedWeapon:
				case ItemObject.ItemTypeEnum.TwoHandedWeapon:
				case ItemObject.ItemTypeEnum.Polearm:
				case ItemObject.ItemTypeEnum.Arrows:
				case ItemObject.ItemTypeEnum.Bolts:
				case ItemObject.ItemTypeEnum.SlingStones:
				case ItemObject.ItemTypeEnum.Shield:
				case ItemObject.ItemTypeEnum.Bow:
				case ItemObject.ItemTypeEnum.Crossbow:
				case ItemObject.ItemTypeEnum.Sling:
				case ItemObject.ItemTypeEnum.Thrown:
				case ItemObject.ItemTypeEnum.Pistol:
				case ItemObject.ItemTypeEnum.Musket:
				case ItemObject.ItemTypeEnum.Bullets:
				case ItemObject.ItemTypeEnum.Banner:
					if (item.ItemFlags.HasAnyFlag(ItemFlags.DropOnWeaponChange | ItemFlags.DropOnAnyAction))
					{
						flag = slotIndex == EquipmentIndex.ExtraWeaponSlot;
					}
					else
					{
						flag = slotIndex == EquipmentIndex.WeaponItemBeginSlot || slotIndex == EquipmentIndex.Weapon1 || slotIndex == EquipmentIndex.Weapon2 || slotIndex == EquipmentIndex.Weapon3;
					}
					break;
				case ItemObject.ItemTypeEnum.HeadArmor:
					flag = slotIndex == EquipmentIndex.NumAllWeaponSlots;
					break;
				case ItemObject.ItemTypeEnum.BodyArmor:
					flag = slotIndex == EquipmentIndex.Body;
					break;
				case ItemObject.ItemTypeEnum.LegArmor:
					flag = slotIndex == EquipmentIndex.Leg;
					break;
				case ItemObject.ItemTypeEnum.HandArmor:
					flag = slotIndex == EquipmentIndex.Gloves;
					break;
				case ItemObject.ItemTypeEnum.Animal:
					flag = slotIndex == EquipmentIndex.ArmorItemEndSlot;
					break;
				case ItemObject.ItemTypeEnum.Book:
					flag = false;
					break;
				case ItemObject.ItemTypeEnum.Cape:
					flag = slotIndex == EquipmentIndex.Cape;
					break;
				case ItemObject.ItemTypeEnum.HorseHarness:
					flag = slotIndex == EquipmentIndex.HorseHarness;
					break;
				}
			}
			return flag;
		}

		// Token: 0x060002E7 RID: 743 RVA: 0x0000CBD4 File Offset: 0x0000ADD4
		public EquipmentIndex GetWeaponPickUpSlotIndex(EquipmentElement itemRosterElement, bool isStuckMissile)
		{
			if (itemRosterElement.Item.ItemFlags.HasAnyFlag(ItemFlags.DropOnWeaponChange | ItemFlags.DropOnAnyAction))
			{
				return EquipmentIndex.ExtraWeaponSlot;
			}
			EquipmentIndex equipmentIndex = EquipmentIndex.None;
			if (equipmentIndex == EquipmentIndex.None)
			{
				for (EquipmentIndex equipmentIndex2 = EquipmentIndex.WeaponItemBeginSlot; equipmentIndex2 < EquipmentIndex.ExtraWeaponSlot; equipmentIndex2++)
				{
					if (this[(int)equipmentIndex2].Item == null)
					{
						equipmentIndex = equipmentIndex2;
						break;
					}
				}
			}
			return equipmentIndex;
		}

		// Token: 0x060002E8 RID: 744 RVA: 0x0000CC24 File Offset: 0x0000AE24
		public bool IsEquipmentEqualTo(Equipment other)
		{
			if (other == null)
			{
				return false;
			}
			for (int i = 0; i < 12; i++)
			{
				if (!this[i].IsEqualTo(other[i]))
				{
					return false;
				}
			}
			return other.IsStealth == this.IsStealth && other.IsCivilian == this.IsCivilian && other.IsBattle == this.IsBattle;
		}

		// Token: 0x060002E9 RID: 745 RVA: 0x0000CC8C File Offset: 0x0000AE8C
		public static Equipment GetRandomEquipmentElements(BasicCharacterObject character, bool randomEquipmentModifier, Equipment.EquipmentType equipmentType, int seed = -1)
		{
			Equipment equipment = new Equipment(equipmentType);
			List<Equipment> list = new List<Equipment>();
			if (equipmentType == Equipment.EquipmentType.Battle)
			{
				list = character.BattleEquipments.ToList<Equipment>();
			}
			else if (equipmentType == Equipment.EquipmentType.Civilian)
			{
				list = character.CivilianEquipments.ToList<Equipment>();
			}
			if (list.IsEmpty<Equipment>())
			{
				return equipment;
			}
			int count = list.Count;
			Random random = new Random(seed);
			int num = MBRandom.RandomInt(count);
			int num2 = MBRandom.RandomInt(count);
			int num3 = MBRandom.RandomInt(count);
			for (int i = 0; i < 12; i++)
			{
				if (seed != -1)
				{
					num = random.Next() % count;
					num2 = random.Next() % count;
					num3 = random.Next() % count;
				}
				if (i > 1)
				{
					if (i - 2 > 1)
					{
						equipment[i] = Equipment.GetRandomizedEquipment(list, (EquipmentIndex)i, num3, randomEquipmentModifier);
					}
					else
					{
						equipment[i] = Equipment.GetRandomizedEquipment(list, (EquipmentIndex)i, num2, randomEquipmentModifier);
					}
				}
				else
				{
					equipment[i] = Equipment.GetRandomizedEquipment(list, (EquipmentIndex)i, num, randomEquipmentModifier);
				}
			}
			return equipment;
		}

		// Token: 0x060002EA RID: 746 RVA: 0x0000CD78 File Offset: 0x0000AF78
		public static void SwapWeapons(Equipment equipment, EquipmentIndex index1, EquipmentIndex index2)
		{
			EquipmentElement equipmentElement = equipment[index1];
			equipment[index1] = equipment[index2];
			equipment[index2] = equipmentElement;
		}

		// Token: 0x060002EB RID: 747 RVA: 0x0000CDA4 File Offset: 0x0000AFA4
		private static EquipmentElement GetRandomizedEquipment(List<Equipment> equipmentSets, EquipmentIndex weaponSlot, int weaponSetNo, bool randomEquipmentModifier)
		{
			EquipmentElement equipmentFromSlot = equipmentSets[weaponSetNo].GetEquipmentFromSlot(weaponSlot);
			if (randomEquipmentModifier)
			{
				ItemObject item = equipmentFromSlot.Item;
				ItemModifier itemModifier;
				if (item == null)
				{
					itemModifier = null;
				}
				else
				{
					ItemComponent itemComponent = item.ItemComponent;
					if (itemComponent == null)
					{
						itemModifier = null;
					}
					else
					{
						ItemModifierGroup itemModifierGroup = itemComponent.ItemModifierGroup;
						itemModifier = ((itemModifierGroup != null) ? itemModifierGroup.GetRandomItemModifierLootScoreBased() : null);
					}
				}
				ItemModifier itemModifier2 = itemModifier;
				if (itemModifier2 != null)
				{
					equipmentFromSlot.SetModifier(itemModifier2);
				}
			}
			return equipmentFromSlot;
		}

		// Token: 0x060002EC RID: 748 RVA: 0x0000CDFC File Offset: 0x0000AFFC
		public void GetInitialWeaponIndicesToEquip(out EquipmentIndex mainHandWeaponIndex, out EquipmentIndex offHandWeaponIndex, out bool isMainHandNotUsableWithOneHand, Equipment.InitialWeaponEquipPreference initialWeaponEquipPreference = Equipment.InitialWeaponEquipPreference.Any)
		{
			mainHandWeaponIndex = EquipmentIndex.None;
			offHandWeaponIndex = EquipmentIndex.None;
			isMainHandNotUsableWithOneHand = false;
			EquipmentIndex[] array = new EquipmentIndex[]
			{
				EquipmentIndex.ExtraWeaponSlot,
				EquipmentIndex.WeaponItemBeginSlot,
				EquipmentIndex.Weapon1,
				EquipmentIndex.Weapon2,
				EquipmentIndex.Weapon3
			};
			bool flag = false;
			bool flag2 = false;
			foreach (EquipmentIndex equipmentIndex in array)
			{
				if (!this[equipmentIndex].IsEmpty)
				{
					ItemObject item = this[equipmentIndex].Item;
					if ((mainHandWeaponIndex == EquipmentIndex.None || (initialWeaponEquipPreference == Equipment.InitialWeaponEquipPreference.MeleeForMainHand && !flag) || (initialWeaponEquipPreference == Equipment.InitialWeaponEquipPreference.RangedForMainHand && !flag2)) && !item.ItemFlags.HasAnyFlag(ItemFlags.HeldInOffHand))
					{
						mainHandWeaponIndex = equipmentIndex;
						isMainHandNotUsableWithOneHand = item.PrimaryWeapon.WeaponFlags.HasAnyFlag(WeaponFlags.NotUsableWithOneHand);
						flag = item.PrimaryWeapon.WeaponFlags.HasAnyFlag(WeaponFlags.MeleeWeapon);
						flag2 = item.PrimaryWeapon.WeaponFlags.HasAnyFlag(WeaponFlags.RangedWeapon);
					}
					else if (offHandWeaponIndex == EquipmentIndex.None && item.ItemFlags.HasAnyFlag(ItemFlags.HeldInOffHand))
					{
						offHandWeaponIndex = equipmentIndex;
					}
				}
			}
		}

		// Token: 0x040001D1 RID: 465
		[SaveableField(1)]
		private Equipment.EquipmentType _equipmentType;

		// Token: 0x040001D2 RID: 466
		public const int EquipmentSlotLength = 12;

		// Token: 0x040001D3 RID: 467
		[SaveableField(2)]
		private readonly EquipmentElement[] _itemSlots;

		// Token: 0x040001D4 RID: 468
		public bool SyncEquipments;

		// Token: 0x040001D5 RID: 469
		public const string NullCode = "@null";

		// Token: 0x020000FD RID: 253
		public enum EquipmentType
		{
			// Token: 0x0400071D RID: 1821
			Invalid = -1,
			// Token: 0x0400071E RID: 1822
			Battle,
			// Token: 0x0400071F RID: 1823
			Civilian,
			// Token: 0x04000720 RID: 1824
			Stealth
		}

		// Token: 0x020000FE RID: 254
		public enum UnderwearTypes
		{
			// Token: 0x04000722 RID: 1826
			NoUnderwear,
			// Token: 0x04000723 RID: 1827
			FullUnderwear,
			// Token: 0x04000724 RID: 1828
			OnlyTop
		}

		// Token: 0x020000FF RID: 255
		public enum InitialWeaponEquipPreference
		{
			// Token: 0x04000726 RID: 1830
			Any,
			// Token: 0x04000727 RID: 1831
			MeleeForMainHand,
			// Token: 0x04000728 RID: 1832
			RangedForMainHand
		}
	}
}
