using System;
using System.Collections.Generic;
using Helpers;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.Encounters;
using TaleWorlds.CampaignSystem.GameMenus;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core;

namespace TaleWorlds.CampaignSystem.MapEvents
{
	// Token: 0x02000329 RID: 809
	public class ForceVolunteersEventComponent : MapEventComponent
	{
		// Token: 0x06003093 RID: 12435 RVA: 0x000CA48C File Offset: 0x000C868C
		internal static void AutoGeneratedStaticCollectObjectsForceVolunteersEventComponent(object o, List<object> collectedObjects)
		{
			((ForceVolunteersEventComponent)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x06003094 RID: 12436 RVA: 0x000CA49A File Offset: 0x000C869A
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x06003095 RID: 12437 RVA: 0x000CA4A3 File Offset: 0x000C86A3
		private ForceVolunteersEventComponent(MapEvent mapEvent)
			: base(mapEvent)
		{
		}

		// Token: 0x06003096 RID: 12438 RVA: 0x000CA4AC File Offset: 0x000C86AC
		public static ForceVolunteersEventComponent CreateForceSuppliesEvent(PartyBase attackerParty, PartyBase defenderParty)
		{
			MapEvent mapEvent = new MapEvent();
			ForceVolunteersEventComponent forceVolunteersEventComponent = new ForceVolunteersEventComponent(mapEvent);
			mapEvent.Initialize(attackerParty, defenderParty, forceVolunteersEventComponent);
			Settlement settlement = defenderParty.Settlement;
			if (((settlement != null) ? settlement.MilitiaPartyComponent : null) != null)
			{
				defenderParty.Settlement.MilitiaPartyComponent.MobileParty.MapEventSide = mapEvent.DefenderSide;
			}
			Campaign.Current.MapEventManager.OnMapEventCreated(mapEvent);
			return forceVolunteersEventComponent;
		}

		// Token: 0x06003097 RID: 12439 RVA: 0x000CA50F File Offset: 0x000C870F
		public static ForceVolunteersEventComponent CreateComponentForOldSaves(MapEvent mapEvent)
		{
			return new ForceVolunteersEventComponent(mapEvent);
		}

		// Token: 0x06003098 RID: 12440 RVA: 0x000CA517 File Offset: 0x000C8717
		public override MapEvent.BattleTypes GetBattleType()
		{
			return MapEvent.BattleTypes.IsForcingVolunteers;
		}

		// Token: 0x17000BD8 RID: 3032
		// (get) Token: 0x06003099 RID: 12441 RVA: 0x000CA51A File Offset: 0x000C871A
		public override MapEvent.PowerCalculationContext SimulationContext
		{
			get
			{
				if (!MapEventHelper.IsNavalRaid(base.MapEvent))
				{
					return MapEvent.PowerCalculationContext.Village;
				}
				return MapEvent.PowerCalculationContext.NavalRaid;
			}
		}

		// Token: 0x0600309A RID: 12442 RVA: 0x000CA530 File Offset: 0x000C8730
		public override void OnBeforeMapEventFinalize()
		{
			if (base.MapEvent.EndedByRetreat && base.MapEvent.RetreatingSide == BattleSideEnum.Attacker)
			{
				foreach (MapEventParty mapEventParty in base.MapEvent.AttackerSide.Parties)
				{
					if (mapEventParty.Party.IsMobile && mapEventParty.Party.IsActive)
					{
						mapEventParty.Party.MobileParty.SetMoveModeHold();
						mapEventParty.Party.MobileParty.Ai.ForceDefaultBehaviorUpdate();
					}
				}
			}
			CampaignEventDispatcher.Instance.ForceVolunteersCompleted((base.MapEvent.BattleState == BattleState.AttackerVictory) ? BattleSideEnum.Attacker : BattleSideEnum.Defender, this);
		}

		// Token: 0x0600309B RID: 12443 RVA: 0x000CA600 File Offset: 0x000C8800
		public override void AddInsideSettlementParties()
		{
			MapEventComponentHelper.AddInsideSettlementParties(base.MapEvent);
		}

		// Token: 0x0600309C RID: 12444 RVA: 0x000CA610 File Offset: 0x000C8810
		public override bool TryHandlePlayerEncounterEnd(bool isPlayerAttacker)
		{
			PartyBase leaderParty = base.MapEvent.AttackerSide.LeaderParty;
			if ((!leaderParty.IsMobile || leaderParty.MobileParty.Army == null || leaderParty.MobileParty.Army.LeaderParty == leaderParty.MobileParty) && leaderParty == MobileParty.MainParty.Party)
			{
				EncounterManager.StartSettlementEncounter(MobileParty.MainParty, base.MapEventSettlement);
				PlayerEncounter.Current.ForceVolunteers = true;
				BeHostileAction.ApplyEncounterHostileAction(PartyBase.MainParty, Settlement.CurrentSettlement.Party);
				GameMenu.SwitchToMenu("force_volunteers_village");
				PlayerEncounter.Current.ForceVolunteers = false;
			}
			return true;
		}

		// Token: 0x0600309D RID: 12445 RVA: 0x000CA6AD File Offset: 0x000C88AD
		public override PlayerEncounterState GetPlayerEncounterStateOnMapEventEnd()
		{
			if (base.MapEvent.WinningSide == PartyBase.MainParty.Side)
			{
				return PlayerEncounterState.PlayerVictory;
			}
			if (base.MapEvent.DefeatedSide == PartyBase.MainParty.Side)
			{
				return PlayerEncounterState.PlayerTotalDefeat;
			}
			return PlayerEncounterState.End;
		}

		// Token: 0x0600309E RID: 12446 RVA: 0x000CA6E3 File Offset: 0x000C88E3
		public override bool CheckIfBattleShouldContinueAfterBattleMission(CampaignBattleResult campaignBattleResult)
		{
			return MapEventComponentHelper.CheckIfBattleShouldContinueAfterBattleMissionCommonCondition(base.MapEvent, campaignBattleResult);
		}

		// Token: 0x0600309F RID: 12447 RVA: 0x000CA6F1 File Offset: 0x000C88F1
		public override void UpdatePlayerEncounterState(CampaignBattleResult campaignBattleResult, out PlayerEncounterState encounterState, out bool stateHandled)
		{
			MapEventComponentHelper.PlayerEncounterDoWaitCommon(base.MapEvent, campaignBattleResult, out encounterState, out stateHandled);
		}

		// Token: 0x060030A0 RID: 12448 RVA: 0x000CA701 File Offset: 0x000C8901
		public override void OnPlayerEncounterContinueBattle(CampaignBattleResult campaignBattleResult, out PlayerEncounterState nextEncounterState, out bool stateHandled)
		{
			MapEventComponentHelper.OnPlayerEncounterContinueBattleCommon(base.MapEvent, campaignBattleResult, out nextEncounterState, out stateHandled);
		}

		// Token: 0x060030A1 RID: 12449 RVA: 0x000CA711 File Offset: 0x000C8911
		public override void UpdateMapEventSettlement()
		{
			base.MapEventSettlement = base.MapEvent.DefenderSide.LeaderParty.Settlement;
		}

		// Token: 0x060030A2 RID: 12450 RVA: 0x000CA72E File Offset: 0x000C892E
		public override void OnPlayerEncounterFinalizeBattle()
		{
			if (base.MapEvent.HasWinner || base.MapEvent.DiplomaticallyFinished)
			{
				PlayerEncounter.Current.FinalizeBattleFromComponent();
				return;
			}
			PlayerEncounter.LeaveBattle();
		}

		// Token: 0x060030A3 RID: 12451 RVA: 0x000CA75A File Offset: 0x000C895A
		public override CampaignVec2 GetMapEventPosition()
		{
			return base.MapEvent.DefenderSide.LeaderParty.Position;
		}

		// Token: 0x060030A4 RID: 12452 RVA: 0x000CA771 File Offset: 0x000C8971
		protected override void OnInitialize()
		{
			ChangeVillageStateAction.ApplyBySettingToBeingForcedForVolunteers(base.MapEventSettlement, base.MapEvent.AttackerSide.LeaderParty.MobileParty);
		}

		// Token: 0x060030A5 RID: 12453 RVA: 0x000CA793 File Offset: 0x000C8993
		protected override void OnFinalize()
		{
			ChangeVillageStateAction.ApplyBySettingToNormal(base.MapEventSettlement);
		}
	}
}
