using System;
using System.Collections.Generic;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.Localization;

namespace TaleWorlds.CampaignSystem.Party.PartyComponents
{
	// Token: 0x02000319 RID: 793
	public abstract class PartyComponent
	{
		// Token: 0x06002E3F RID: 11839 RVA: 0x000C1E70 File Offset: 0x000C0070
		protected virtual void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
		}

		// Token: 0x17000B44 RID: 2884
		// (get) Token: 0x06002E40 RID: 11840 RVA: 0x000C1E72 File Offset: 0x000C0072
		// (set) Token: 0x06002E41 RID: 11841 RVA: 0x000C1E7A File Offset: 0x000C007A
		public MobileParty MobileParty { get; private set; }

		// Token: 0x17000B45 RID: 2885
		// (get) Token: 0x06002E42 RID: 11842 RVA: 0x000C1E83 File Offset: 0x000C0083
		public PartyBase Party
		{
			get
			{
				return this.MobileParty.Party;
			}
		}

		// Token: 0x17000B46 RID: 2886
		// (get) Token: 0x06002E43 RID: 11843
		public abstract Hero PartyOwner { get; }

		// Token: 0x17000B47 RID: 2887
		// (get) Token: 0x06002E44 RID: 11844
		public abstract TextObject Name { get; }

		// Token: 0x17000B48 RID: 2888
		// (get) Token: 0x06002E45 RID: 11845
		public abstract Settlement HomeSettlement { get; }

		// Token: 0x17000B49 RID: 2889
		// (get) Token: 0x06002E46 RID: 11846 RVA: 0x000C1E90 File Offset: 0x000C0090
		public virtual bool AvoidHostileActions
		{
			get
			{
				return false;
			}
		}

		// Token: 0x17000B4A RID: 2890
		// (get) Token: 0x06002E47 RID: 11847 RVA: 0x000C1E93 File Offset: 0x000C0093
		public virtual int WagePaymentLimit
		{
			get
			{
				return Campaign.Current.Models.PartyWageModel.MaxWagePaymentLimit;
			}
		}

		// Token: 0x06002E48 RID: 11848 RVA: 0x000C1EA9 File Offset: 0x000C00A9
		public virtual void SetWagePaymentLimit(int newLimit)
		{
			Debug.FailedAssert("Invalid set wage payment limit function usage!", "C:\\BuildAgent\\work\\mb3\\Source\\Bannerlord\\TaleWorlds.CampaignSystem\\Party\\PartyComponents\\PartyComponent.cs", "SetWagePaymentLimit", 30);
		}

		// Token: 0x17000B4B RID: 2891
		// (get) Token: 0x06002E49 RID: 11849 RVA: 0x000C1EC1 File Offset: 0x000C00C1
		public virtual Hero Leader
		{
			get
			{
				return null;
			}
		}

		// Token: 0x17000B4C RID: 2892
		// (get) Token: 0x06002E4A RID: 11850 RVA: 0x000C1EC4 File Offset: 0x000C00C4
		public Banner Banner
		{
			get
			{
				return this.MobileParty.Banner;
			}
		}

		// Token: 0x06002E4B RID: 11851
		public abstract Banner GetDefaultComponentBanner();

		// Token: 0x17000B4D RID: 2893
		// (get) Token: 0x06002E4C RID: 11852 RVA: 0x000C1ED1 File Offset: 0x000C00D1
		public virtual bool CanHaveNavalNavigationCapability
		{
			get
			{
				Clan actualClan = this.MobileParty.ActualClan;
				return actualClan != null && actualClan.HasNavalNavigationCapability;
			}
		}

		// Token: 0x17000B4E RID: 2894
		// (get) Token: 0x06002E4D RID: 11853 RVA: 0x000C1EE9 File Offset: 0x000C00E9
		public virtual bool CanHaveLandNavigationCapability
		{
			get
			{
				return true;
			}
		}

		// Token: 0x06002E4E RID: 11854 RVA: 0x000C1EEC File Offset: 0x000C00EC
		internal void Create(MobileParty party)
		{
			this.MobileParty = party;
			this.OnMobilePartySetOnCreation();
		}

		// Token: 0x06002E4F RID: 11855 RVA: 0x000C1EFB File Offset: 0x000C00FB
		internal void Initialize(MobileParty party)
		{
			this.MobileParty = party;
			this.OnInitialize();
		}

		// Token: 0x06002E50 RID: 11856 RVA: 0x000C1F0A File Offset: 0x000C010A
		internal void Finish()
		{
			this.OnFinalize();
		}

		// Token: 0x06002E51 RID: 11857 RVA: 0x000C1F12 File Offset: 0x000C0112
		protected virtual void OnMobilePartySetOnCreation()
		{
		}

		// Token: 0x06002E52 RID: 11858 RVA: 0x000C1F14 File Offset: 0x000C0114
		protected virtual void OnInitialize()
		{
		}

		// Token: 0x06002E53 RID: 11859 RVA: 0x000C1F16 File Offset: 0x000C0116
		protected virtual void OnFinalize()
		{
		}

		// Token: 0x06002E54 RID: 11860 RVA: 0x000C1F18 File Offset: 0x000C0118
		public virtual void ClearCachedName()
		{
		}

		// Token: 0x06002E55 RID: 11861 RVA: 0x000C1F1C File Offset: 0x000C011C
		public void ChangePartyLeader(Hero newLeader)
		{
			if (newLeader != null && !this.MobileParty.MemberRoster.Contains(newLeader.CharacterObject))
			{
				Debug.FailedAssert(string.Concat(new object[]
				{
					(newLeader != null) ? newLeader.Name : null,
					" is not a member of ",
					this.Name,
					"!\nParty leader did not change."
				}), "C:\\BuildAgent\\work\\mb3\\Source\\Bannerlord\\TaleWorlds.CampaignSystem\\Party\\PartyComponents\\PartyComponent.cs", "ChangePartyLeader", 67);
				return;
			}
			Hero leader = this.Leader;
			this.OnChangePartyLeader(newLeader);
			if (newLeader == null && this.MobileParty.MapEvent == null)
			{
				this.MobileParty.SetMoveModeHold();
			}
			if (leader != this.Leader)
			{
				CampaignEventDispatcher.Instance.OnPartyLeaderChanged(this.MobileParty, leader);
			}
		}

		// Token: 0x06002E56 RID: 11862 RVA: 0x000C1FCC File Offset: 0x000C01CC
		protected virtual void OnChangePartyLeader(Hero newLeader)
		{
		}

		// Token: 0x06002E57 RID: 11863 RVA: 0x000C1FCE File Offset: 0x000C01CE
		public virtual void GetMountAndHarnessVisualIdsForPartyIcon(PartyBase party, out string mountStringId, out string harnessStringId)
		{
			mountStringId = "";
			harnessStringId = "";
		}

		// Token: 0x020006F0 RID: 1776
		// (Invoke) Token: 0x060056B4 RID: 22196
		public delegate void OnPartyComponentCreatedDelegate(MobileParty mobileParty);
	}
}
