using System;
using System.ComponentModel;
using System.Numerics;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.GauntletUI.Data;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets;
using TaleWorlds.MountAndBlade.Multiplayer.ViewModelCollection.TeamSelection;

namespace TaleWorlds.MountAndBlade.GauntletUI.AutoGenerated0
{
	// Token: 0x02000057 RID: 87
	public class MultiplayerTeamSelection__TaleWorlds_MountAndBlade_Multiplayer_ViewModelCollection_TeamSelection_MultiplayerTeamSelectVM : Widget, IGeneratedGauntletMovieRoot
	{
		// Token: 0x06001C5D RID: 7261 RVA: 0x000DF357 File Offset: 0x000DD557
		public MultiplayerTeamSelection__TaleWorlds_MountAndBlade_Multiplayer_ViewModelCollection_TeamSelection_MultiplayerTeamSelectVM(UIContext context)
			: base(context)
		{
		}

		// Token: 0x06001C5E RID: 7262 RVA: 0x000DF360 File Offset: 0x000DD560
		public void CreateWidgets()
		{
			this._widget = this;
			this._widget_0 = new Widget(base.Context);
			this._widget.AddChild(this._widget_0);
			this._widget_0_0 = new Widget(base.Context);
			this._widget_0.AddChild(this._widget_0_0);
			this._widget_0_0_0 = new Widget(base.Context);
			this._widget_0_0.AddChild(this._widget_0_0_0);
			this._widget_0_1 = new TextWidget(base.Context);
			this._widget_0.AddChild(this._widget_0_1);
			this._widget_0_2 = new Widget(base.Context);
			this._widget_0.AddChild(this._widget_0_2);
			this._widget_0_3 = new TextWidget(base.Context);
			this._widget_0.AddChild(this._widget_0_3);
			this._widget_0_4 = new TextWidget(base.Context);
			this._widget_0.AddChild(this._widget_0_4);
			this._widget_0_5 = new MultiplayerTeamSelection__TaleWorlds_MountAndBlade_Multiplayer_ViewModelCollection_TeamSelection_MultiplayerTeamSelectVM_Dependency_1_MultiplayerTeamSelectionItem__DependendPrefab(base.Context);
			this._widget_0.AddChild(this._widget_0_5);
			this._widget_0_5.CreateWidgets();
			this._widget_0_6 = new MultiplayerTeamSelection__TaleWorlds_MountAndBlade_Multiplayer_ViewModelCollection_TeamSelection_MultiplayerTeamSelectVM_Dependency_2_MultiplayerTeamSelectionItem__DependendPrefab(base.Context);
			this._widget_0.AddChild(this._widget_0_6);
			this._widget_0_6.CreateWidgets();
			this._widget_0_7 = new NavigationScopeTargeter(base.Context);
			this._widget_0.AddChild(this._widget_0_7);
			this._widget_0_8 = new ButtonWidget(base.Context);
			this._widget_0.AddChild(this._widget_0_8);
			this._widget_0_8_0 = new TextWidget(base.Context);
			this._widget_0_8.AddChild(this._widget_0_8_0);
			this._widget_0_9 = new NavigationScopeTargeter(base.Context);
			this._widget_0.AddChild(this._widget_0_9);
			this._widget_0_10 = new ButtonWidget(base.Context);
			this._widget_0.AddChild(this._widget_0_10);
			this._widget_0_10_0 = new TextWidget(base.Context);
			this._widget_0_10.AddChild(this._widget_0_10_0);
			this._widget_0_11 = new NavigationScopeTargeter(base.Context);
			this._widget_0.AddChild(this._widget_0_11);
			this._widget_0_12 = new ButtonWidget(base.Context);
			this._widget_0.AddChild(this._widget_0_12);
		}

		// Token: 0x06001C5F RID: 7263 RVA: 0x000DF5CC File Offset: 0x000DD7CC
		public void SetIds()
		{
			this._widget_0_5.SetIds();
			this._widget_0_6.SetIds();
			this._widget_0_8.Id = "AutoAssignButton";
			this._widget_0_10.Id = "SelectSpectatorButton";
			this._widget_0_12.Id = "CancelButton";
		}

		// Token: 0x06001C60 RID: 7264 RVA: 0x000DF620 File Offset: 0x000DD820
		public void SetAttributes()
		{
			base.WidthSizePolicy = SizePolicy.StretchToParent;
			base.HeightSizePolicy = SizePolicy.StretchToParent;
			base.Sprite = base.Context.SpriteData.GetSprite("BlankWhiteSquare_9");
			base.Color = new Color(0f, 0f, 0f, 0.8000001f);
			this._widget_0.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_0.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_0.SuggestedWidth = 880f;
			this._widget_0.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_0.Sprite = base.Context.SpriteData.GetSprite("flat_panel_9");
			this._widget_0_0.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_0_0.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_0_0.SuggestedHeight = 533f;
			this._widget_0_0.MarginLeft = 60f;
			this._widget_0_0.MarginRight = 60f;
			this._widget_0_0.VerticalAlignment = VerticalAlignment.Bottom;
			this._widget_0_0.ClipContents = true;
			this._widget_0_0_0.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_0_0_0.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_0_0_0.SuggestedWidth = 1377f;
			this._widget_0_0_0.Sprite = base.Context.SpriteData.GetSprite("StdAssets\\flat_panel_texture");
			this._widget_0_1.WidthSizePolicy = SizePolicy.CoverChildren;
			this._widget_0_1.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_0_1.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_0_1.VerticalAlignment = VerticalAlignment.Top;
			this._widget_0_1.MarginTop = 20f;
			this._widget_0_1.Brush = base.Context.GetBrush("MPTeamSelection.HeaderText");
			this._widget_0_2.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_0_2.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_0_2.SuggestedWidth = 664f;
			this._widget_0_2.SuggestedHeight = 20f;
			this._widget_0_2.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_0_2.MarginTop = 70f;
			this._widget_0_2.Sprite = base.Context.SpriteData.GetSprite("MPTeamSelection\\divider_notched");
			this._widget_0_3.WidthSizePolicy = SizePolicy.CoverChildren;
			this._widget_0_3.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_0_3.VerticalAlignment = VerticalAlignment.Top;
			this._widget_0_3.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_0_3.MarginTop = 87f;
			this._widget_0_3.Brush = base.Context.GetBrush("MPTeamSelection.SubHeaderText");
			this._widget_0_4.WidthSizePolicy = SizePolicy.CoverChildren;
			this._widget_0_4.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_0_4.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_0_4.MarginTop = 140f;
			this._widget_0_4.Brush = base.Context.GetBrush("MPHUD.CountdownText");
			this._widget_0_5.SetAttributes();
			this._widget_0_5.VerticalAlignment = VerticalAlignment.Top;
			this._widget_0_5.HorizontalAlignment = HorizontalAlignment.Left;
			this._widget_0_5.MarginTop = 164f;
			this._widget_0_5.MarginLeft = 60f;
			this._widget_0_6.SetAttributes();
			this._widget_0_6.VerticalAlignment = VerticalAlignment.Top;
			this._widget_0_6.HorizontalAlignment = HorizontalAlignment.Right;
			this._widget_0_6.MarginTop = 164f;
			this._widget_0_6.MarginRight = 60f;
			this._widget_0_7.ScopeID = "AutoAssignButtonScope";
			this._widget_0_7.ScopeParent = this._widget_0_8;
			this._widget_0_8.DoNotPassEventsToChildren = true;
			this._widget_0_8.UpdateChildrenStates = true;
			this._widget_0_8.SuggestedWidth = 86f;
			this._widget_0_8.SuggestedHeight = 86f;
			this._widget_0_8.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_0_8.VerticalAlignment = VerticalAlignment.Bottom;
			this._widget_0_8.MarginBottom = 120f;
			this._widget_0_8.Brush = base.Context.GetBrush("MPTeamSelection.AutoAssignButton");
			this._widget_0_8.GamepadNavigationIndex = 0;
			this._widget_0_8_0.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_0_8_0.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_0_8_0.SuggestedWidth = 200f;
			this._widget_0_8_0.SuggestedHeight = 100f;
			this._widget_0_8_0.VerticalAlignment = VerticalAlignment.Bottom;
			this._widget_0_8_0.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_0_8_0.PositionYOffset = 60f;
			this._widget_0_8_0.Brush = base.Context.GetBrush("MPTeamSelection.AutoAssignButton.Text");
			this._widget_0_9.ScopeID = "SelectSpectatorButtonScope";
			this._widget_0_9.ScopeParent = this._widget_0_10;
			this._widget_0_10.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_0_10.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_0_10.SuggestedWidth = 342f;
			this._widget_0_10.SuggestedHeight = 69f;
			this._widget_0_10.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_0_10.VerticalAlignment = VerticalAlignment.Bottom;
			this._widget_0_10.MarginBottom = 5f;
			this._widget_0_10.Brush = base.Context.GetBrush("WideButton.Flat");
			this._widget_0_10.DoNotPassEventsToChildren = true;
			this._widget_0_10.UpdateChildrenStates = true;
			this._widget_0_10.GamepadNavigationIndex = 0;
			this._widget_0_10_0.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_0_10_0.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_0_10_0.SuggestedWidth = 200f;
			this._widget_0_10_0.SuggestedHeight = 50f;
			this._widget_0_10_0.VerticalAlignment = VerticalAlignment.Center;
			this._widget_0_10_0.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_0_10_0.Brush = base.Context.GetBrush("MPTeamSelection.SpectateButton.Text");
			this._widget_0_11.ScopeID = "CancelButtonScope";
			this._widget_0_11.ScopeParent = this._widget_0_12;
			this._widget_0_12.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_0_12.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_0_12.SuggestedWidth = 67f;
			this._widget_0_12.SuggestedHeight = 67f;
			this._widget_0_12.HorizontalAlignment = HorizontalAlignment.Right;
			this._widget_0_12.VerticalAlignment = VerticalAlignment.Top;
			this._widget_0_12.MarginTop = 10f;
			this._widget_0_12.MarginRight = 55f;
			this._widget_0_12.Brush = base.Context.GetBrush("CloseButton.Flat");
			this._widget_0_12.DoNotPassEventsToChildren = true;
			this._widget_0_12.GamepadNavigationIndex = 0;
		}

		// Token: 0x06001C61 RID: 7265 RVA: 0x000DFC84 File Offset: 0x000DDE84
		public void RefreshBindingWithChildren()
		{
			MultiplayerTeamSelectVM datasource_Root = this._datasource_Root;
			this.SetDataSource(null);
			this.SetDataSource(datasource_Root);
		}

		// Token: 0x06001C62 RID: 7266 RVA: 0x000DFCA8 File Offset: 0x000DDEA8
		public void DestroyDataSource()
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget_0_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_1;
				this._widget_0_3.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_3;
				this._widget_0_4.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_4;
				this._widget_0_4.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_4;
				this._widget_0_4.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_4;
				this._widget_0_4.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_4;
				this._widget_0_4.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_4;
				this._widget_0_4.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_4;
				this._widget_0_4.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_4;
				this._widget_0_4.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_4;
				this._widget_0_4.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_4;
				this._widget_0_8.EventFire -= this.EventListenerOf_widget_0_8;
				this._widget_0_8_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_8_0;
				this._widget_0_8_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_8_0;
				this._widget_0_8_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_8_0;
				this._widget_0_8_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_8_0;
				this._widget_0_8_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_8_0;
				this._widget_0_8_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_8_0;
				this._widget_0_8_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_8_0;
				this._widget_0_8_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_8_0;
				this._widget_0_8_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_8_0;
				this._widget_0_12.EventFire -= this.EventListenerOf_widget_0_12;
				this._widget_0_12.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_12;
				this._widget_0_12.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_12;
				this._widget_0_12.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_12;
				this._widget_0_12.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_12;
				this._widget_0_12.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_12;
				this._widget_0_12.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_12;
				this._widget_0_12.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_12;
				this._widget_0_12.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_12;
				this._widget_0_12.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_12;
				if (this._datasource_Root_Team1 != null)
				{
					this._widget_0_5.DestroyDataSource();
					this._datasource_Root_Team1.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_Team1;
					this._datasource_Root_Team1.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Team1;
					this._datasource_Root_Team1.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Team1;
					this._datasource_Root_Team1.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Team1;
					this._datasource_Root_Team1.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Team1;
					this._datasource_Root_Team1.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Team1;
					this._datasource_Root_Team1.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Team1;
					this._datasource_Root_Team1.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Team1;
					this._datasource_Root_Team1.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Team1;
					this._datasource_Root_Team1 = null;
				}
				if (this._datasource_Root_Team2 != null)
				{
					this._widget_0_6.DestroyDataSource();
					this._datasource_Root_Team2.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_Team2;
					this._datasource_Root_Team2.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Team2;
					this._datasource_Root_Team2.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Team2;
					this._datasource_Root_Team2.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Team2;
					this._datasource_Root_Team2.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Team2;
					this._datasource_Root_Team2.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Team2;
					this._datasource_Root_Team2.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Team2;
					this._datasource_Root_Team2.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Team2;
					this._datasource_Root_Team2.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Team2;
					this._datasource_Root_Team2 = null;
				}
				if (this._datasource_Root_TeamSpectators != null)
				{
					this._datasource_Root_TeamSpectators.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_TeamSpectators;
					this._datasource_Root_TeamSpectators.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_TeamSpectators;
					this._datasource_Root_TeamSpectators.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_TeamSpectators;
					this._datasource_Root_TeamSpectators.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_TeamSpectators;
					this._datasource_Root_TeamSpectators.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_TeamSpectators;
					this._datasource_Root_TeamSpectators.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_TeamSpectators;
					this._datasource_Root_TeamSpectators.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_TeamSpectators;
					this._datasource_Root_TeamSpectators.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_TeamSpectators;
					this._datasource_Root_TeamSpectators.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_TeamSpectators;
					this._widget_0_10.EventFire -= this.EventListenerOf_widget_0_10;
					this._widget_0_10_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_10_0;
					this._widget_0_10_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_10_0;
					this._widget_0_10_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_10_0;
					this._widget_0_10_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_10_0;
					this._widget_0_10_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_10_0;
					this._widget_0_10_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_10_0;
					this._widget_0_10_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_10_0;
					this._widget_0_10_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_10_0;
					this._widget_0_10_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_10_0;
					this._datasource_Root_TeamSpectators = null;
				}
				this._datasource_Root = null;
			}
		}

		// Token: 0x06001C63 RID: 7267 RVA: 0x000E056E File Offset: 0x000DE76E
		public void SetDataSource(MultiplayerTeamSelectVM dataSource)
		{
			this.RefreshDataSource_datasource_Root(dataSource);
		}

		// Token: 0x06001C64 RID: 7268 RVA: 0x000E0577 File Offset: 0x000DE777
		private void EventListenerOf_widget_0_8(Widget widget, string commandName, object[] args)
		{
			if (commandName == "Click")
			{
				this._datasource_Root.ExecuteAutoAssign();
			}
		}

		// Token: 0x06001C65 RID: 7269 RVA: 0x000E0591 File Offset: 0x000DE791
		private void EventListenerOf_widget_0_12(Widget widget, string commandName, object[] args)
		{
			if (commandName == "Click")
			{
				this._datasource_Root.ExecuteCancel();
			}
		}

		// Token: 0x06001C66 RID: 7270 RVA: 0x000E05AB File Offset: 0x000DE7AB
		private void EventListenerOf_widget_0_10(Widget widget, string commandName, object[] args)
		{
			if (commandName == "Click")
			{
				this._datasource_Root_TeamSpectators.ExecuteSelectTeam();
			}
		}

		// Token: 0x06001C67 RID: 7271 RVA: 0x000E05C5 File Offset: 0x000DE7C5
		private void PropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
		}

		// Token: 0x06001C68 RID: 7272 RVA: 0x000E05CE File Offset: 0x000DE7CE
		private void boolPropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
		}

		// Token: 0x06001C69 RID: 7273 RVA: 0x000E05D7 File Offset: 0x000DE7D7
		private void floatPropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
		}

		// Token: 0x06001C6A RID: 7274 RVA: 0x000E05E0 File Offset: 0x000DE7E0
		private void Vec2PropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
		}

		// Token: 0x06001C6B RID: 7275 RVA: 0x000E05E9 File Offset: 0x000DE7E9
		private void Vector2PropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
		}

		// Token: 0x06001C6C RID: 7276 RVA: 0x000E05F2 File Offset: 0x000DE7F2
		private void doublePropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
		}

		// Token: 0x06001C6D RID: 7277 RVA: 0x000E05FB File Offset: 0x000DE7FB
		private void intPropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
		}

		// Token: 0x06001C6E RID: 7278 RVA: 0x000E0604 File Offset: 0x000DE804
		private void uintPropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
		}

		// Token: 0x06001C6F RID: 7279 RVA: 0x000E060D File Offset: 0x000DE80D
		private void ColorPropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
		}

		// Token: 0x06001C70 RID: 7280 RVA: 0x000E0616 File Offset: 0x000DE816
		private void HandleWidgetPropertyChangeOf_widget_0_1(string propertyName)
		{
			if (propertyName == "Text")
			{
				this._datasource_Root.TeamSelectTitle = this._widget_0_1.Text;
				return;
			}
		}

		// Token: 0x06001C71 RID: 7281 RVA: 0x000E063C File Offset: 0x000DE83C
		private void PropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
		}

		// Token: 0x06001C72 RID: 7282 RVA: 0x000E0645 File Offset: 0x000DE845
		private void boolPropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
		}

		// Token: 0x06001C73 RID: 7283 RVA: 0x000E064E File Offset: 0x000DE84E
		private void floatPropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
		}

		// Token: 0x06001C74 RID: 7284 RVA: 0x000E0657 File Offset: 0x000DE857
		private void Vec2PropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
		}

		// Token: 0x06001C75 RID: 7285 RVA: 0x000E0660 File Offset: 0x000DE860
		private void Vector2PropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
		}

		// Token: 0x06001C76 RID: 7286 RVA: 0x000E0669 File Offset: 0x000DE869
		private void doublePropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
		}

		// Token: 0x06001C77 RID: 7287 RVA: 0x000E0672 File Offset: 0x000DE872
		private void intPropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
		}

		// Token: 0x06001C78 RID: 7288 RVA: 0x000E067B File Offset: 0x000DE87B
		private void uintPropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
		}

		// Token: 0x06001C79 RID: 7289 RVA: 0x000E0684 File Offset: 0x000DE884
		private void ColorPropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
		}

		// Token: 0x06001C7A RID: 7290 RVA: 0x000E068D File Offset: 0x000DE88D
		private void HandleWidgetPropertyChangeOf_widget_0_3(string propertyName)
		{
			if (propertyName == "Text")
			{
				this._datasource_Root.GamemodeLbl = this._widget_0_3.Text;
				return;
			}
		}

		// Token: 0x06001C7B RID: 7291 RVA: 0x000E06B3 File Offset: 0x000DE8B3
		private void PropertyChangedListenerOf_widget_0_4(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_4(propertyName);
		}

		// Token: 0x06001C7C RID: 7292 RVA: 0x000E06BC File Offset: 0x000DE8BC
		private void boolPropertyChangedListenerOf_widget_0_4(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_4(propertyName);
		}

		// Token: 0x06001C7D RID: 7293 RVA: 0x000E06C5 File Offset: 0x000DE8C5
		private void floatPropertyChangedListenerOf_widget_0_4(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_4(propertyName);
		}

		// Token: 0x06001C7E RID: 7294 RVA: 0x000E06CE File Offset: 0x000DE8CE
		private void Vec2PropertyChangedListenerOf_widget_0_4(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_4(propertyName);
		}

		// Token: 0x06001C7F RID: 7295 RVA: 0x000E06D7 File Offset: 0x000DE8D7
		private void Vector2PropertyChangedListenerOf_widget_0_4(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_4(propertyName);
		}

		// Token: 0x06001C80 RID: 7296 RVA: 0x000E06E0 File Offset: 0x000DE8E0
		private void doublePropertyChangedListenerOf_widget_0_4(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_4(propertyName);
		}

		// Token: 0x06001C81 RID: 7297 RVA: 0x000E06E9 File Offset: 0x000DE8E9
		private void intPropertyChangedListenerOf_widget_0_4(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_4(propertyName);
		}

		// Token: 0x06001C82 RID: 7298 RVA: 0x000E06F2 File Offset: 0x000DE8F2
		private void uintPropertyChangedListenerOf_widget_0_4(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_4(propertyName);
		}

		// Token: 0x06001C83 RID: 7299 RVA: 0x000E06FB File Offset: 0x000DE8FB
		private void ColorPropertyChangedListenerOf_widget_0_4(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_4(propertyName);
		}

		// Token: 0x06001C84 RID: 7300 RVA: 0x000E0704 File Offset: 0x000DE904
		private void HandleWidgetPropertyChangeOf_widget_0_4(string propertyName)
		{
			if (propertyName == "IsVisible")
			{
				this._datasource_Root.IsRoundCountdownAvailable = this._widget_0_4.IsVisible;
				return;
			}
			if (propertyName == "Text")
			{
				this._datasource_Root.RemainingRoundTime = this._widget_0_4.Text;
				return;
			}
		}

		// Token: 0x06001C85 RID: 7301 RVA: 0x000E0759 File Offset: 0x000DE959
		private void PropertyChangedListenerOf_widget_0_8_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_8_0(propertyName);
		}

		// Token: 0x06001C86 RID: 7302 RVA: 0x000E0762 File Offset: 0x000DE962
		private void boolPropertyChangedListenerOf_widget_0_8_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_8_0(propertyName);
		}

		// Token: 0x06001C87 RID: 7303 RVA: 0x000E076B File Offset: 0x000DE96B
		private void floatPropertyChangedListenerOf_widget_0_8_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_8_0(propertyName);
		}

		// Token: 0x06001C88 RID: 7304 RVA: 0x000E0774 File Offset: 0x000DE974
		private void Vec2PropertyChangedListenerOf_widget_0_8_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_8_0(propertyName);
		}

		// Token: 0x06001C89 RID: 7305 RVA: 0x000E077D File Offset: 0x000DE97D
		private void Vector2PropertyChangedListenerOf_widget_0_8_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_8_0(propertyName);
		}

		// Token: 0x06001C8A RID: 7306 RVA: 0x000E0786 File Offset: 0x000DE986
		private void doublePropertyChangedListenerOf_widget_0_8_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_8_0(propertyName);
		}

		// Token: 0x06001C8B RID: 7307 RVA: 0x000E078F File Offset: 0x000DE98F
		private void intPropertyChangedListenerOf_widget_0_8_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_8_0(propertyName);
		}

		// Token: 0x06001C8C RID: 7308 RVA: 0x000E0798 File Offset: 0x000DE998
		private void uintPropertyChangedListenerOf_widget_0_8_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_8_0(propertyName);
		}

		// Token: 0x06001C8D RID: 7309 RVA: 0x000E07A1 File Offset: 0x000DE9A1
		private void ColorPropertyChangedListenerOf_widget_0_8_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_8_0(propertyName);
		}

		// Token: 0x06001C8E RID: 7310 RVA: 0x000E07AA File Offset: 0x000DE9AA
		private void HandleWidgetPropertyChangeOf_widget_0_8_0(string propertyName)
		{
			if (propertyName == "Text")
			{
				this._datasource_Root.AutoassignLbl = this._widget_0_8_0.Text;
				return;
			}
		}

		// Token: 0x06001C8F RID: 7311 RVA: 0x000E07D0 File Offset: 0x000DE9D0
		private void PropertyChangedListenerOf_widget_0_12(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_12(propertyName);
		}

		// Token: 0x06001C90 RID: 7312 RVA: 0x000E07D9 File Offset: 0x000DE9D9
		private void boolPropertyChangedListenerOf_widget_0_12(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_12(propertyName);
		}

		// Token: 0x06001C91 RID: 7313 RVA: 0x000E07E2 File Offset: 0x000DE9E2
		private void floatPropertyChangedListenerOf_widget_0_12(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_12(propertyName);
		}

		// Token: 0x06001C92 RID: 7314 RVA: 0x000E07EB File Offset: 0x000DE9EB
		private void Vec2PropertyChangedListenerOf_widget_0_12(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_12(propertyName);
		}

		// Token: 0x06001C93 RID: 7315 RVA: 0x000E07F4 File Offset: 0x000DE9F4
		private void Vector2PropertyChangedListenerOf_widget_0_12(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_12(propertyName);
		}

		// Token: 0x06001C94 RID: 7316 RVA: 0x000E07FD File Offset: 0x000DE9FD
		private void doublePropertyChangedListenerOf_widget_0_12(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_12(propertyName);
		}

		// Token: 0x06001C95 RID: 7317 RVA: 0x000E0806 File Offset: 0x000DEA06
		private void intPropertyChangedListenerOf_widget_0_12(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_12(propertyName);
		}

		// Token: 0x06001C96 RID: 7318 RVA: 0x000E080F File Offset: 0x000DEA0F
		private void uintPropertyChangedListenerOf_widget_0_12(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_12(propertyName);
		}

		// Token: 0x06001C97 RID: 7319 RVA: 0x000E0818 File Offset: 0x000DEA18
		private void ColorPropertyChangedListenerOf_widget_0_12(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_12(propertyName);
		}

		// Token: 0x06001C98 RID: 7320 RVA: 0x000E0821 File Offset: 0x000DEA21
		private void HandleWidgetPropertyChangeOf_widget_0_12(string propertyName)
		{
			if (propertyName == "IsHidden")
			{
				this._datasource_Root.IsCancelDisabled = this._widget_0_12.IsHidden;
				return;
			}
		}

		// Token: 0x06001C99 RID: 7321 RVA: 0x000E0847 File Offset: 0x000DEA47
		private void PropertyChangedListenerOf_widget_0_10_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_10_0(propertyName);
		}

		// Token: 0x06001C9A RID: 7322 RVA: 0x000E0850 File Offset: 0x000DEA50
		private void boolPropertyChangedListenerOf_widget_0_10_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_10_0(propertyName);
		}

		// Token: 0x06001C9B RID: 7323 RVA: 0x000E0859 File Offset: 0x000DEA59
		private void floatPropertyChangedListenerOf_widget_0_10_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_10_0(propertyName);
		}

		// Token: 0x06001C9C RID: 7324 RVA: 0x000E0862 File Offset: 0x000DEA62
		private void Vec2PropertyChangedListenerOf_widget_0_10_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_10_0(propertyName);
		}

		// Token: 0x06001C9D RID: 7325 RVA: 0x000E086B File Offset: 0x000DEA6B
		private void Vector2PropertyChangedListenerOf_widget_0_10_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_10_0(propertyName);
		}

		// Token: 0x06001C9E RID: 7326 RVA: 0x000E0874 File Offset: 0x000DEA74
		private void doublePropertyChangedListenerOf_widget_0_10_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_10_0(propertyName);
		}

		// Token: 0x06001C9F RID: 7327 RVA: 0x000E087D File Offset: 0x000DEA7D
		private void intPropertyChangedListenerOf_widget_0_10_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_10_0(propertyName);
		}

		// Token: 0x06001CA0 RID: 7328 RVA: 0x000E0886 File Offset: 0x000DEA86
		private void uintPropertyChangedListenerOf_widget_0_10_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_10_0(propertyName);
		}

		// Token: 0x06001CA1 RID: 7329 RVA: 0x000E088F File Offset: 0x000DEA8F
		private void ColorPropertyChangedListenerOf_widget_0_10_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_10_0(propertyName);
		}

		// Token: 0x06001CA2 RID: 7330 RVA: 0x000E0898 File Offset: 0x000DEA98
		private void HandleWidgetPropertyChangeOf_widget_0_10_0(string propertyName)
		{
			if (propertyName == "Text")
			{
				this._datasource_Root_TeamSpectators.DisplayedPrimary = this._widget_0_10_0.Text;
				return;
			}
		}

		// Token: 0x06001CA3 RID: 7331 RVA: 0x000E08BE File Offset: 0x000DEABE
		private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001CA4 RID: 7332 RVA: 0x000E08CC File Offset: 0x000DEACC
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001CA5 RID: 7333 RVA: 0x000E08DB File Offset: 0x000DEADB
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001CA6 RID: 7334 RVA: 0x000E08EA File Offset: 0x000DEAEA
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001CA7 RID: 7335 RVA: 0x000E08F9 File Offset: 0x000DEAF9
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001CA8 RID: 7336 RVA: 0x000E0908 File Offset: 0x000DEB08
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001CA9 RID: 7337 RVA: 0x000E0917 File Offset: 0x000DEB17
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001CAA RID: 7338 RVA: 0x000E0926 File Offset: 0x000DEB26
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001CAB RID: 7339 RVA: 0x000E0935 File Offset: 0x000DEB35
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06001CAC RID: 7340 RVA: 0x000E0944 File Offset: 0x000DEB44
		private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
		{
			if (propertyName == "Team1")
			{
				this.RefreshDataSource_datasource_Root_Team1(this._datasource_Root.Team1);
				return;
			}
			if (propertyName == "Team2")
			{
				this.RefreshDataSource_datasource_Root_Team2(this._datasource_Root.Team2);
				return;
			}
			if (propertyName == "TeamSpectators")
			{
				this.RefreshDataSource_datasource_Root_TeamSpectators(this._datasource_Root.TeamSpectators);
				return;
			}
			if (propertyName == "TeamSelectTitle")
			{
				this._widget_0_1.Text = this._datasource_Root.TeamSelectTitle;
				return;
			}
			if (propertyName == "GamemodeLbl")
			{
				this._widget_0_3.Text = this._datasource_Root.GamemodeLbl;
				return;
			}
			if (propertyName == "IsRoundCountdownAvailable")
			{
				this._widget_0_4.IsVisible = this._datasource_Root.IsRoundCountdownAvailable;
				return;
			}
			if (propertyName == "RemainingRoundTime")
			{
				this._widget_0_4.Text = this._datasource_Root.RemainingRoundTime;
				return;
			}
			if (propertyName == "AutoassignLbl")
			{
				this._widget_0_8_0.Text = this._datasource_Root.AutoassignLbl;
				return;
			}
			if (propertyName == "IsCancelDisabled")
			{
				this._widget_0_12.IsHidden = this._datasource_Root.IsCancelDisabled;
				return;
			}
		}

		// Token: 0x06001CAD RID: 7341 RVA: 0x000E0A86 File Offset: 0x000DEC86
		private void ViewModelPropertyChangedListenerOf_datasource_Root_Team1(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_Team1(e.PropertyName);
		}

		// Token: 0x06001CAE RID: 7342 RVA: 0x000E0A94 File Offset: 0x000DEC94
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Team1(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_Team1(e.PropertyName);
		}

		// Token: 0x06001CAF RID: 7343 RVA: 0x000E0AA3 File Offset: 0x000DECA3
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Team1(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_Team1(e.PropertyName);
		}

		// Token: 0x06001CB0 RID: 7344 RVA: 0x000E0AB2 File Offset: 0x000DECB2
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Team1(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_Team1(e.PropertyName);
		}

		// Token: 0x06001CB1 RID: 7345 RVA: 0x000E0AC1 File Offset: 0x000DECC1
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Team1(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_Team1(e.PropertyName);
		}

		// Token: 0x06001CB2 RID: 7346 RVA: 0x000E0AD0 File Offset: 0x000DECD0
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Team1(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_Team1(e.PropertyName);
		}

		// Token: 0x06001CB3 RID: 7347 RVA: 0x000E0ADF File Offset: 0x000DECDF
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Team1(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_Team1(e.PropertyName);
		}

		// Token: 0x06001CB4 RID: 7348 RVA: 0x000E0AEE File Offset: 0x000DECEE
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Team1(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_Team1(e.PropertyName);
		}

		// Token: 0x06001CB5 RID: 7349 RVA: 0x000E0AFD File Offset: 0x000DECFD
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Team1(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_Team1(e.PropertyName);
		}

		// Token: 0x06001CB6 RID: 7350 RVA: 0x000E0B0C File Offset: 0x000DED0C
		private void HandleViewModelPropertyChangeOf_datasource_Root_Team1(string propertyName)
		{
		}

		// Token: 0x06001CB7 RID: 7351 RVA: 0x000E0B0E File Offset: 0x000DED0E
		private void ViewModelPropertyChangedListenerOf_datasource_Root_Team2(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_Team2(e.PropertyName);
		}

		// Token: 0x06001CB8 RID: 7352 RVA: 0x000E0B1C File Offset: 0x000DED1C
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Team2(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_Team2(e.PropertyName);
		}

		// Token: 0x06001CB9 RID: 7353 RVA: 0x000E0B2B File Offset: 0x000DED2B
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Team2(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_Team2(e.PropertyName);
		}

		// Token: 0x06001CBA RID: 7354 RVA: 0x000E0B3A File Offset: 0x000DED3A
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Team2(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_Team2(e.PropertyName);
		}

		// Token: 0x06001CBB RID: 7355 RVA: 0x000E0B49 File Offset: 0x000DED49
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Team2(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_Team2(e.PropertyName);
		}

		// Token: 0x06001CBC RID: 7356 RVA: 0x000E0B58 File Offset: 0x000DED58
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Team2(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_Team2(e.PropertyName);
		}

		// Token: 0x06001CBD RID: 7357 RVA: 0x000E0B67 File Offset: 0x000DED67
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Team2(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_Team2(e.PropertyName);
		}

		// Token: 0x06001CBE RID: 7358 RVA: 0x000E0B76 File Offset: 0x000DED76
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Team2(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_Team2(e.PropertyName);
		}

		// Token: 0x06001CBF RID: 7359 RVA: 0x000E0B85 File Offset: 0x000DED85
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Team2(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_Team2(e.PropertyName);
		}

		// Token: 0x06001CC0 RID: 7360 RVA: 0x000E0B94 File Offset: 0x000DED94
		private void HandleViewModelPropertyChangeOf_datasource_Root_Team2(string propertyName)
		{
		}

		// Token: 0x06001CC1 RID: 7361 RVA: 0x000E0B96 File Offset: 0x000DED96
		private void ViewModelPropertyChangedListenerOf_datasource_Root_TeamSpectators(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_TeamSpectators(e.PropertyName);
		}

		// Token: 0x06001CC2 RID: 7362 RVA: 0x000E0BA4 File Offset: 0x000DEDA4
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_TeamSpectators(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_TeamSpectators(e.PropertyName);
		}

		// Token: 0x06001CC3 RID: 7363 RVA: 0x000E0BB3 File Offset: 0x000DEDB3
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_TeamSpectators(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_TeamSpectators(e.PropertyName);
		}

		// Token: 0x06001CC4 RID: 7364 RVA: 0x000E0BC2 File Offset: 0x000DEDC2
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_TeamSpectators(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_TeamSpectators(e.PropertyName);
		}

		// Token: 0x06001CC5 RID: 7365 RVA: 0x000E0BD1 File Offset: 0x000DEDD1
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_TeamSpectators(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_TeamSpectators(e.PropertyName);
		}

		// Token: 0x06001CC6 RID: 7366 RVA: 0x000E0BE0 File Offset: 0x000DEDE0
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_TeamSpectators(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_TeamSpectators(e.PropertyName);
		}

		// Token: 0x06001CC7 RID: 7367 RVA: 0x000E0BEF File Offset: 0x000DEDEF
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_TeamSpectators(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_TeamSpectators(e.PropertyName);
		}

		// Token: 0x06001CC8 RID: 7368 RVA: 0x000E0BFE File Offset: 0x000DEDFE
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_TeamSpectators(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_TeamSpectators(e.PropertyName);
		}

		// Token: 0x06001CC9 RID: 7369 RVA: 0x000E0C0D File Offset: 0x000DEE0D
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_TeamSpectators(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_TeamSpectators(e.PropertyName);
		}

		// Token: 0x06001CCA RID: 7370 RVA: 0x000E0C1C File Offset: 0x000DEE1C
		private void HandleViewModelPropertyChangeOf_datasource_Root_TeamSpectators(string propertyName)
		{
			if (propertyName == "DisplayedPrimary")
			{
				this._widget_0_10_0.Text = this._datasource_Root_TeamSpectators.DisplayedPrimary;
				return;
			}
		}

		// Token: 0x06001CCB RID: 7371 RVA: 0x000E0C44 File Offset: 0x000DEE44
		private void RefreshDataSource_datasource_Root(MultiplayerTeamSelectVM newDataSource)
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget_0_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_1;
				this._widget_0_3.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_3;
				this._widget_0_4.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_4;
				this._widget_0_4.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_4;
				this._widget_0_4.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_4;
				this._widget_0_4.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_4;
				this._widget_0_4.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_4;
				this._widget_0_4.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_4;
				this._widget_0_4.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_4;
				this._widget_0_4.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_4;
				this._widget_0_4.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_4;
				this._widget_0_8.EventFire -= this.EventListenerOf_widget_0_8;
				this._widget_0_8_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_8_0;
				this._widget_0_8_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_8_0;
				this._widget_0_8_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_8_0;
				this._widget_0_8_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_8_0;
				this._widget_0_8_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_8_0;
				this._widget_0_8_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_8_0;
				this._widget_0_8_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_8_0;
				this._widget_0_8_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_8_0;
				this._widget_0_8_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_8_0;
				this._widget_0_12.EventFire -= this.EventListenerOf_widget_0_12;
				this._widget_0_12.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_12;
				this._widget_0_12.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_12;
				this._widget_0_12.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_12;
				this._widget_0_12.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_12;
				this._widget_0_12.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_12;
				this._widget_0_12.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_12;
				this._widget_0_12.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_12;
				this._widget_0_12.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_12;
				this._widget_0_12.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_12;
				if (this._datasource_Root_Team1 != null)
				{
					this._widget_0_5.SetDataSource(null);
					this._datasource_Root_Team1.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_Team1;
					this._datasource_Root_Team1.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Team1;
					this._datasource_Root_Team1.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Team1;
					this._datasource_Root_Team1.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Team1;
					this._datasource_Root_Team1.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Team1;
					this._datasource_Root_Team1.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Team1;
					this._datasource_Root_Team1.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Team1;
					this._datasource_Root_Team1.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Team1;
					this._datasource_Root_Team1.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Team1;
					this._datasource_Root_Team1 = null;
				}
				if (this._datasource_Root_Team2 != null)
				{
					this._widget_0_6.SetDataSource(null);
					this._datasource_Root_Team2.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_Team2;
					this._datasource_Root_Team2.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Team2;
					this._datasource_Root_Team2.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Team2;
					this._datasource_Root_Team2.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Team2;
					this._datasource_Root_Team2.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Team2;
					this._datasource_Root_Team2.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Team2;
					this._datasource_Root_Team2.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Team2;
					this._datasource_Root_Team2.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Team2;
					this._datasource_Root_Team2.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Team2;
					this._datasource_Root_Team2 = null;
				}
				if (this._datasource_Root_TeamSpectators != null)
				{
					this._datasource_Root_TeamSpectators.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_TeamSpectators;
					this._datasource_Root_TeamSpectators.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_TeamSpectators;
					this._datasource_Root_TeamSpectators.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_TeamSpectators;
					this._datasource_Root_TeamSpectators.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_TeamSpectators;
					this._datasource_Root_TeamSpectators.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_TeamSpectators;
					this._datasource_Root_TeamSpectators.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_TeamSpectators;
					this._datasource_Root_TeamSpectators.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_TeamSpectators;
					this._datasource_Root_TeamSpectators.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_TeamSpectators;
					this._datasource_Root_TeamSpectators.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_TeamSpectators;
					this._widget_0_10.EventFire -= this.EventListenerOf_widget_0_10;
					this._widget_0_10_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_10_0;
					this._widget_0_10_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_10_0;
					this._widget_0_10_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_10_0;
					this._widget_0_10_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_10_0;
					this._widget_0_10_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_10_0;
					this._widget_0_10_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_10_0;
					this._widget_0_10_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_10_0;
					this._widget_0_10_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_10_0;
					this._widget_0_10_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_10_0;
					this._datasource_Root_TeamSpectators = null;
				}
				this._datasource_Root = null;
			}
			this._datasource_Root = newDataSource;
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget_0_1.Text = this._datasource_Root.TeamSelectTitle;
				this._widget_0_1.PropertyChanged += this.PropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.intPropertyChanged += this.intPropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_0_1;
				this._widget_0_3.Text = this._datasource_Root.GamemodeLbl;
				this._widget_0_3.PropertyChanged += this.PropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.intPropertyChanged += this.intPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_0_3;
				this._widget_0_3.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_0_3;
				this._widget_0_4.IsVisible = this._datasource_Root.IsRoundCountdownAvailable;
				this._widget_0_4.Text = this._datasource_Root.RemainingRoundTime;
				this._widget_0_4.PropertyChanged += this.PropertyChangedListenerOf_widget_0_4;
				this._widget_0_4.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_0_4;
				this._widget_0_4.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_0_4;
				this._widget_0_4.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_0_4;
				this._widget_0_4.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_0_4;
				this._widget_0_4.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_0_4;
				this._widget_0_4.intPropertyChanged += this.intPropertyChangedListenerOf_widget_0_4;
				this._widget_0_4.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_0_4;
				this._widget_0_4.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_0_4;
				this._widget_0_8.EventFire += this.EventListenerOf_widget_0_8;
				this._widget_0_8_0.Text = this._datasource_Root.AutoassignLbl;
				this._widget_0_8_0.PropertyChanged += this.PropertyChangedListenerOf_widget_0_8_0;
				this._widget_0_8_0.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_0_8_0;
				this._widget_0_8_0.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_0_8_0;
				this._widget_0_8_0.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_0_8_0;
				this._widget_0_8_0.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_0_8_0;
				this._widget_0_8_0.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_0_8_0;
				this._widget_0_8_0.intPropertyChanged += this.intPropertyChangedListenerOf_widget_0_8_0;
				this._widget_0_8_0.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_0_8_0;
				this._widget_0_8_0.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_0_8_0;
				this._widget_0_12.IsHidden = this._datasource_Root.IsCancelDisabled;
				this._widget_0_12.EventFire += this.EventListenerOf_widget_0_12;
				this._widget_0_12.PropertyChanged += this.PropertyChangedListenerOf_widget_0_12;
				this._widget_0_12.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_0_12;
				this._widget_0_12.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_0_12;
				this._widget_0_12.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_0_12;
				this._widget_0_12.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_0_12;
				this._widget_0_12.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_0_12;
				this._widget_0_12.intPropertyChanged += this.intPropertyChangedListenerOf_widget_0_12;
				this._widget_0_12.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_0_12;
				this._widget_0_12.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_0_12;
				this._datasource_Root_Team1 = this._datasource_Root.Team1;
				if (this._datasource_Root_Team1 != null)
				{
					this._datasource_Root_Team1.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root_Team1;
					this._datasource_Root_Team1.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Team1;
					this._datasource_Root_Team1.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Team1;
					this._datasource_Root_Team1.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Team1;
					this._datasource_Root_Team1.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Team1;
					this._datasource_Root_Team1.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Team1;
					this._datasource_Root_Team1.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Team1;
					this._datasource_Root_Team1.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Team1;
					this._datasource_Root_Team1.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Team1;
					this._widget_0_5.SetDataSource(this._datasource_Root_Team1);
				}
				this._datasource_Root_Team2 = this._datasource_Root.Team2;
				if (this._datasource_Root_Team2 != null)
				{
					this._datasource_Root_Team2.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root_Team2;
					this._datasource_Root_Team2.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Team2;
					this._datasource_Root_Team2.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Team2;
					this._datasource_Root_Team2.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Team2;
					this._datasource_Root_Team2.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Team2;
					this._datasource_Root_Team2.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Team2;
					this._datasource_Root_Team2.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Team2;
					this._datasource_Root_Team2.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Team2;
					this._datasource_Root_Team2.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Team2;
					this._widget_0_6.SetDataSource(this._datasource_Root_Team2);
				}
				this._datasource_Root_TeamSpectators = this._datasource_Root.TeamSpectators;
				if (this._datasource_Root_TeamSpectators != null)
				{
					this._datasource_Root_TeamSpectators.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root_TeamSpectators;
					this._datasource_Root_TeamSpectators.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_TeamSpectators;
					this._datasource_Root_TeamSpectators.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_TeamSpectators;
					this._datasource_Root_TeamSpectators.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_TeamSpectators;
					this._datasource_Root_TeamSpectators.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_TeamSpectators;
					this._datasource_Root_TeamSpectators.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_TeamSpectators;
					this._datasource_Root_TeamSpectators.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_TeamSpectators;
					this._datasource_Root_TeamSpectators.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_TeamSpectators;
					this._datasource_Root_TeamSpectators.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_TeamSpectators;
					this._widget_0_10.EventFire += this.EventListenerOf_widget_0_10;
					this._widget_0_10_0.Text = this._datasource_Root_TeamSpectators.DisplayedPrimary;
					this._widget_0_10_0.PropertyChanged += this.PropertyChangedListenerOf_widget_0_10_0;
					this._widget_0_10_0.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_0_10_0;
					this._widget_0_10_0.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_0_10_0;
					this._widget_0_10_0.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_0_10_0;
					this._widget_0_10_0.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_0_10_0;
					this._widget_0_10_0.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_0_10_0;
					this._widget_0_10_0.intPropertyChanged += this.intPropertyChangedListenerOf_widget_0_10_0;
					this._widget_0_10_0.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_0_10_0;
					this._widget_0_10_0.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_0_10_0;
				}
			}
		}

		// Token: 0x06001CCC RID: 7372 RVA: 0x000E1E8C File Offset: 0x000E008C
		private void RefreshDataSource_datasource_Root_Team1(TeamSelectTeamInstanceVM newDataSource)
		{
			if (this._datasource_Root_Team1 != null)
			{
				this._widget_0_5.SetDataSource(null);
				this._datasource_Root_Team1.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_Team1;
				this._datasource_Root_Team1.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Team1;
				this._datasource_Root_Team1.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Team1;
				this._datasource_Root_Team1.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Team1;
				this._datasource_Root_Team1.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Team1;
				this._datasource_Root_Team1.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Team1;
				this._datasource_Root_Team1.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Team1;
				this._datasource_Root_Team1.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Team1;
				this._datasource_Root_Team1.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Team1;
				this._datasource_Root_Team1 = null;
			}
			this._datasource_Root_Team1 = newDataSource;
			this._datasource_Root_Team1 = this._datasource_Root.Team1;
			if (this._datasource_Root_Team1 != null)
			{
				this._datasource_Root_Team1.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root_Team1;
				this._datasource_Root_Team1.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Team1;
				this._datasource_Root_Team1.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Team1;
				this._datasource_Root_Team1.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Team1;
				this._datasource_Root_Team1.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Team1;
				this._datasource_Root_Team1.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Team1;
				this._datasource_Root_Team1.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Team1;
				this._datasource_Root_Team1.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Team1;
				this._datasource_Root_Team1.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Team1;
				this._widget_0_5.SetDataSource(this._datasource_Root_Team1);
			}
		}

		// Token: 0x06001CCD RID: 7373 RVA: 0x000E208C File Offset: 0x000E028C
		private void RefreshDataSource_datasource_Root_Team2(TeamSelectTeamInstanceVM newDataSource)
		{
			if (this._datasource_Root_Team2 != null)
			{
				this._widget_0_6.SetDataSource(null);
				this._datasource_Root_Team2.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_Team2;
				this._datasource_Root_Team2.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Team2;
				this._datasource_Root_Team2.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Team2;
				this._datasource_Root_Team2.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Team2;
				this._datasource_Root_Team2.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Team2;
				this._datasource_Root_Team2.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Team2;
				this._datasource_Root_Team2.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Team2;
				this._datasource_Root_Team2.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Team2;
				this._datasource_Root_Team2.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Team2;
				this._datasource_Root_Team2 = null;
			}
			this._datasource_Root_Team2 = newDataSource;
			this._datasource_Root_Team2 = this._datasource_Root.Team2;
			if (this._datasource_Root_Team2 != null)
			{
				this._datasource_Root_Team2.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root_Team2;
				this._datasource_Root_Team2.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Team2;
				this._datasource_Root_Team2.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Team2;
				this._datasource_Root_Team2.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Team2;
				this._datasource_Root_Team2.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Team2;
				this._datasource_Root_Team2.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Team2;
				this._datasource_Root_Team2.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Team2;
				this._datasource_Root_Team2.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Team2;
				this._datasource_Root_Team2.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Team2;
				this._widget_0_6.SetDataSource(this._datasource_Root_Team2);
			}
		}

		// Token: 0x06001CCE RID: 7374 RVA: 0x000E228C File Offset: 0x000E048C
		private void RefreshDataSource_datasource_Root_TeamSpectators(TeamSelectTeamInstanceVM newDataSource)
		{
			if (this._datasource_Root_TeamSpectators != null)
			{
				this._datasource_Root_TeamSpectators.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_TeamSpectators;
				this._datasource_Root_TeamSpectators.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_TeamSpectators;
				this._datasource_Root_TeamSpectators.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_TeamSpectators;
				this._datasource_Root_TeamSpectators.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_TeamSpectators;
				this._datasource_Root_TeamSpectators.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_TeamSpectators;
				this._datasource_Root_TeamSpectators.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_TeamSpectators;
				this._datasource_Root_TeamSpectators.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_TeamSpectators;
				this._datasource_Root_TeamSpectators.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_TeamSpectators;
				this._datasource_Root_TeamSpectators.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_TeamSpectators;
				this._widget_0_10.EventFire -= this.EventListenerOf_widget_0_10;
				this._widget_0_10_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_10_0;
				this._widget_0_10_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_10_0;
				this._widget_0_10_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_10_0;
				this._widget_0_10_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_10_0;
				this._widget_0_10_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_10_0;
				this._widget_0_10_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_10_0;
				this._widget_0_10_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_10_0;
				this._widget_0_10_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_10_0;
				this._widget_0_10_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_10_0;
				this._datasource_Root_TeamSpectators = null;
			}
			this._datasource_Root_TeamSpectators = newDataSource;
			this._datasource_Root_TeamSpectators = this._datasource_Root.TeamSpectators;
			if (this._datasource_Root_TeamSpectators != null)
			{
				this._datasource_Root_TeamSpectators.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root_TeamSpectators;
				this._datasource_Root_TeamSpectators.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_TeamSpectators;
				this._datasource_Root_TeamSpectators.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_TeamSpectators;
				this._datasource_Root_TeamSpectators.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_TeamSpectators;
				this._datasource_Root_TeamSpectators.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_TeamSpectators;
				this._datasource_Root_TeamSpectators.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_TeamSpectators;
				this._datasource_Root_TeamSpectators.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_TeamSpectators;
				this._datasource_Root_TeamSpectators.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_TeamSpectators;
				this._datasource_Root_TeamSpectators.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_TeamSpectators;
				this._widget_0_10.EventFire += this.EventListenerOf_widget_0_10;
				this._widget_0_10_0.Text = this._datasource_Root_TeamSpectators.DisplayedPrimary;
				this._widget_0_10_0.PropertyChanged += this.PropertyChangedListenerOf_widget_0_10_0;
				this._widget_0_10_0.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_0_10_0;
				this._widget_0_10_0.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_0_10_0;
				this._widget_0_10_0.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_0_10_0;
				this._widget_0_10_0.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_0_10_0;
				this._widget_0_10_0.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_0_10_0;
				this._widget_0_10_0.intPropertyChanged += this.intPropertyChangedListenerOf_widget_0_10_0;
				this._widget_0_10_0.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_0_10_0;
				this._widget_0_10_0.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_0_10_0;
			}
		}

		// Token: 0x04000483 RID: 1155
		private Widget _widget;

		// Token: 0x04000484 RID: 1156
		private Widget _widget_0;

		// Token: 0x04000485 RID: 1157
		private Widget _widget_0_0;

		// Token: 0x04000486 RID: 1158
		private Widget _widget_0_0_0;

		// Token: 0x04000487 RID: 1159
		private TextWidget _widget_0_1;

		// Token: 0x04000488 RID: 1160
		private Widget _widget_0_2;

		// Token: 0x04000489 RID: 1161
		private TextWidget _widget_0_3;

		// Token: 0x0400048A RID: 1162
		private TextWidget _widget_0_4;

		// Token: 0x0400048B RID: 1163
		private MultiplayerTeamSelection__TaleWorlds_MountAndBlade_Multiplayer_ViewModelCollection_TeamSelection_MultiplayerTeamSelectVM_Dependency_1_MultiplayerTeamSelectionItem__DependendPrefab _widget_0_5;

		// Token: 0x0400048C RID: 1164
		private MultiplayerTeamSelection__TaleWorlds_MountAndBlade_Multiplayer_ViewModelCollection_TeamSelection_MultiplayerTeamSelectVM_Dependency_2_MultiplayerTeamSelectionItem__DependendPrefab _widget_0_6;

		// Token: 0x0400048D RID: 1165
		private NavigationScopeTargeter _widget_0_7;

		// Token: 0x0400048E RID: 1166
		private ButtonWidget _widget_0_8;

		// Token: 0x0400048F RID: 1167
		private TextWidget _widget_0_8_0;

		// Token: 0x04000490 RID: 1168
		private NavigationScopeTargeter _widget_0_9;

		// Token: 0x04000491 RID: 1169
		private ButtonWidget _widget_0_10;

		// Token: 0x04000492 RID: 1170
		private TextWidget _widget_0_10_0;

		// Token: 0x04000493 RID: 1171
		private NavigationScopeTargeter _widget_0_11;

		// Token: 0x04000494 RID: 1172
		private ButtonWidget _widget_0_12;

		// Token: 0x04000495 RID: 1173
		private MultiplayerTeamSelectVM _datasource_Root;

		// Token: 0x04000496 RID: 1174
		private TeamSelectTeamInstanceVM _datasource_Root_Team1;

		// Token: 0x04000497 RID: 1175
		private TeamSelectTeamInstanceVM _datasource_Root_Team2;

		// Token: 0x04000498 RID: 1176
		private TeamSelectTeamInstanceVM _datasource_Root_TeamSpectators;
	}
}
